### ISSUE TITLE
[deckhouse] research huge amount on list actions

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#10020]
https://loop.flant.ru/flant/pl/uq3aqh6ijp8t5e7ctzysa5n67w

command `cat /var/log/kube-audit/*.log | grep -v namespace | jq '. | select(.verb == "list" and .objectRef.resource == "grafanadashboarddefinitions") | .user.username' | sort | uniq -c | sort -bgr` gives 
```
  3150 "system:serviceaccount:d8-system:deckhouse"
```
even in the test cluster. Have to figure out, who is making such amount of requests. I assume it's [the hook](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/hooks/deprecate_outdated_grafana_dashboard_crd.go#L52) but it runs once per hour

**Comment by miklezzzz** [comment]
fixed in https://github.com/flant/addon-operator/pull/514
