### ISSUE TITLE
[local-path-provisioner] problem with installing

### ISSUE THREAD

**Issue by ox7a59** [deckhouse/deckhouse#1008]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

alpha, beta, early-access, stable

### Expected Behavior

Local Path Provisioner module should be installed correctly

### Actual Behavior

I have error when installing:
```
local-path-provisioner/taskRunner: ModuleRun failed. Requeue task to retry after delay. Failed count is 1. Error: run monitor: apiVersion 'deckhouse.io/v1alpha1', kind 'LocalPathProvisioner' is not supported by cluster
```

### Steps To Reproduce

1. Install environment with Deckhouse image with various tags: from alpha to stable
2. Configure in `config.yml` release channel
3. Run the installation
4. Install needed debian packages when script is running (`virt-what` + `conntrack`)
5. Replace kernel version in `032_install_kernel`
6. And I obtain this error

### Additional Information

In my os-release I have:
```
ID=debian
VERSION_ID=9
```

### Logs

```shell
http://ix.io/3Rju
```

**Comment by kvaps** [comment]
Hi, sorry for late answer, is problem still persists?
If so, could you also provide logs of deckhouse-controller?

```
kubectl logs -n d8-system deploy/deckhouse
```

**Comment by kvaps** [comment]
Unfortunately I can't reproduce this.
If you still facing with this issue, please write here, I'll reopen the issue.

**Comment by lysyy** [comment]
I have the same problem.
     Module "vertical-pod-autoscaler-crd" run successfully
│ │     Module "kube-proxy" run successfully
│ │     local-path-provisioner/: ModuleRun failed in phase 'QueueSynchronizationTasks'. Requeue task to retry after delay. Failed count is    ↵
│ │ 1. Error: run monitor: apiVersion 'deckhouse.io/v1alpha1', kind 'LocalPathProvisioner' is not supported by cluster
│ │     Module "local-path-provisioner" run successfully
│ │     Module "cni-flannel" run successfully
