### ISSUE TITLE
[user-authn] Add ability to set custom labels on autogenerated DexClient secret

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/deckhouse#10172]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are some cases that I would like focus on:
* Role/ClusterRole can grant access only to secrets with specific labels.
* Software can rely on listing secrets using a label selector.

In my case, I encountered an issue where I couldn’t set Deckhouse Dex as SSO in ArgoCD because the autogenerated secret did not contain the required label `app.kubernetes.io/part-of=argocd`. 

There is no workaround for this issue, and I had to resolve it by patching ArgoCD.

### Proposed Solution

Inherit custom labels from the DexClient resource or provide the ability to explicitly define them.

### Additional Information

rel https://deckhouse.io/products/kubernetes-platform/documentation/v1/modules/150-user-authn/usage.html#configuring-the-oauth2-client-in-dex-for-connecting-an-application

**Comment by nabokihms** [comment]
1. copy labels and annotation from DexClient to a secret
2. ignore if there are helm labels and annotations
3. ignore if there are werf annotations
4. ignore if there are argocd annotations

you may find annotations and labels for the 2-4 here
https://github.com/deckhouse/deckhouse/blob/56f0bb02b7bd9a3c16dcbf8239685b913a955869/modules/600-secret-copier/hooks/handler.go#L82-L88
