### ISSUE TITLE
[Changelog] Simplify setting changes for multiple modules

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#1041]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to have changes sorted in sections correctly. Thus we avoid "global" section or alike.

It is a little cumbersome to write multiple change blocks in PRs. E.g. there is a common change for all cloud providers (we have 6 of them for the time of writing), or there is auth-related change that affects hooks in multiple modules. 

To have valid and helpful changelog, one needs to copy-and-paste the same change for many modules in a row. Or to collect by hand, which sections to mention. That is not convenient, especially when all the changes are the same, and one needs to change a word or fix a typo in multiple section descriptions.

### Proposed Solution

Two things

- support multiple sections in a single change block
- collect affected sections automatically

#### Multiple sections support

First, we can add a new field (`sections`) that accepts a list of sections. Like this

````
```changes
sections:
- upmeter
- node-manager
- prometheus
type: fix
summary: changed something
```
````

Or there can be a single line with comma-separated sections (probably less readable), which could be the same field as is it now

````
```changes
section: upmeter,node-manager,prometheus
type: fix
summary: changed something
```
````

#### Sections collection

In a PR, we can have a command that helps to define the set of changes sections. Depending on the chosen contract above, it can return the list of sections

> /changelog-sections
> ````
> ```changes
> sections: 
> - upmeter
> - node-manager
> - prometheus
>```
> ````

or 

> /changelog-sections
> ````
> ```changes
> section: upmeter,node-manager,prometheus
>```
> ````

The script for the command action is as simple as this (and probably can be even easier)

```bash
cat <<EOF
sections:
$(gh pr diff 762 |
        egrep "([+]{3}|[-]{3}) [ab]/" |
        cut -d/ -f2- |
        sed 's#^ee/##' |
        sed 's#^fe/##' |
        sed 's#^modules/##' |
        sed 's#[0-9][0-9][0-9]-##' |
        cut -d/ -f1 |
        sort |
        uniq |
        xargs -n 1 -- echo -
)
EOF
```

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/changelog-action/pull/40
