### ISSUE TITLE
[monitoring-kubernetes] Make it possible to choose Namespace 'All' in the "Main / Namespace" dashboard

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#1049]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30

### Expected Behavior

There should be option "All" in Namespace selector.

### Actual Behavior

There is dashboard "Main / Namespace" where I can choose any Namespace but I can't choose all of them at once.

**Comment by nabokihms** [comment]
It is not possible to select all namespaces, because there is a dedicated dashboard for that - `Main / Namespaces`
