### ISSUE TITLE
[prometheus] Preserve time-range on switching between dashboards from the Main folder

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#106]
We have links to other dashboards in `Main: Namespace` and `Main: Namespace/Controller` dashboards (maybe there are more).

Links look like this:
```
/d/m41rB4yiz1/pod?var-ds_prometheus=${ds_prometheus}&var-namespace=${namespace}&var-pod=${__cell}
```
To add a timestamp to this link we only need to append `&from=${__from}&to=${__to}` to query arguments. After that, we will have a redirect to an URL with a proper time-range.

**Comment by diafour** [comment]
https://grafana.com/docs/grafana/latest/linking/data-link-variables/#time-range-panel-variables

There is a shortcut for interval: `{__url_time_range}`

**Comment by nabokihms** [comment]
Fixed in https://github.com/deckhouse/deckhouse/commit/799b00d091189cf43fd70c683c1168ba2731dedf
