### ISSUE TITLE
[external-modules] Add Alerts for Update Approvals

### ISSUE THREAD

**Issue by cds111** [deckhouse/deckhouse#10715]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When updates are set to manual mode, we do not receive any notifications regarding available updates, which may result in missing important updates.

### Proposed Solution

Add alert about manual update approval

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/pull/10268
