### ISSUE TITLE
[deckhouse-controller]  requirements k8s is not created in all bundle type

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#10862]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When using `bundle: Minimal` no requirements k8s are created. Under such conditions, a dkp update may occur when the kube version is unsupported by control-plane-manager. This is not a problem in itself, but api versions of other components are likely to be supported in the same range of kube versions.

### Proposed Solution

 To prevent such situations it is better to limit dkp update.

**Comment by raabdullaev** [comment]
This behaivor is by design.

**Comment by raabdullaev** [comment]
We don't plan to do this.
