### ISSUE TITLE
[log-shipper] Vector stops collecting logs when connection to the kube-apiserver is lost

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1093]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.31.0

### Expected Behavior

There is a problem that Vector stops collecting logs from new pods if kube-apiserver is restarted.

### Actual Behavior

Vector continues working normally after kube-apiserver restart.

### Steps To Reproduce

1. Set up log collecting pipeline
2. Kill the kube-apiserver pods
3. Check whether log-shipper collects logs from new pods created after restarting kube-apiserver

### Additional Information

https://github.com/vectordotdev/vector/issues/8616

**Comment by EvgenySamoylov** [comment]
Waiting for vector's migration to kube-rs: https://github.com/vectordotdev/vector/issues/8616#issuecomment-1039609703

**Comment by nabokihms** [comment]
https://vector.dev/highlights/2022-03-28-kube-for-kubernetes_logs/|

Vector 0.21 is out including the new kube-rs client.

**Comment by nabokihms** [comment]
Still waiting...
