### ISSUE TITLE
Update Grafana to 8.3+

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#1164]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Grafana has new features requested by users

### Proposed Solution

Update version in dockerfile and ensure dashboards work as expected

**Comment by EvgenySamoylov** [comment]
Fixed at #1536
