### ISSUE TITLE
[log-shipper] Inject labels from message

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#125]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This is important for Elasticsearch and Loki to improve search speed.

### Proposed Solution

It will be a new option for ClusterLoggingConfig (and PodLoggingConfig).

**Comment by konstantin-axenov** [comment]
Closed in 23b584d668a7b9173305acf7158e728d55583447.
