### ISSUE TITLE
[cloud-provider-yandex] Get external network ids from master and static nodes and pass them to cloud controller manager

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#1265]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If we need to add ExternalIP for control-plane node or static-nodes into node status, we should manually add `cloudProviderYandex.additionalExternalNetworkIDs` with network id, where subnets for nodes located.

We can automatize this.

### Proposed Solution

- Collect all subnets from all static node in terraform.

- Lookup network ids with [yandex_vpc_subnet](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs/data-sources/datasource_vpc_subnet#network_id) data source and output them with cloudDiscoveryData or nodes output.

- Join cloudProviderYandex.additionalExternalNetworkIDs and networks from terraform output in cloud-provider-yandex hook and save array to internal values

- Pass new array from internal values to [Cloud Controller Manager](https://github.com/deckhouse/deckhouse/blob/83b932cd7aada8f95221cc65196760b0dd89ee24/modules/030-cloud-provider-yandex/templates/cloud-controller-manager/deployment.yaml#L107)

**Comment by name212** [comment]
@zuzzas Please check me and fyi

**Comment by zuzzas** [comment]
Exactly as I envisioned. Thanks!
