### ISSUE TITLE
Add vSphere to Getting Started

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#128]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse supports vSphere and users want to test it in their private clouds.

### Proposed Solution

Write the docs and publish them on deckhouse.io.

**Comment by z9r5** [comment]
[Done](https://github.com/deckhouse/deckhouse/commit/9c51d51c1a75aa9d242dd02f3a31ac52dfb7ff53)
