### ISSUE TITLE
[docs] Add a full list of modules to the sidebar

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#1284]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The sidebar on the site contains groups of topics, and sometimes it is not easy to find a module by its name (the best way now is to use search).

It will be helpful to have an alphabetically sorted list of modules in the sidebar, additionally to the existing structure. It will help to find a concrete module by its name faster.

### Proposed Solution

Add an alphabetically sorted list of modules to the existing structure in the sidebar.

**Comment by EvgenySamoylov** [comment]
I suppose the problem may be fixed by #1467. Lets skip it for now.

**Comment by z9r5** [comment]
The full list of modules is available [here](https://deckhouse.io/en/documentation/v1/revision-comparison.html). But it is not in the sidebar.
