### ISSUE TITLE
[deckhouse] Improve startup speed

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#132]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

From creating the pod to readiness, Deckhouse spends like 8-10 minutes doing modules provisioning. It is looking extremely excessive. 

### Proposed Solution

We have to analyze deckhouse metrics and logs first to find the bottleneck and then fix it.

**Comment by konstantin-axenov** [comment]
Closed in 5b2e5be26a9bd3fd5d531e237423e877f2c7e951.
