### ISSUE TITLE
Add cluster's available web interfaces list at grafana home screen

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1341]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is no easy way to see the list of all available in cluster web interfaces (like kubernetes dashboard etc) visually in one place.

### Proposed Solution

We need to add such a list in grafana dashboard (at home screen). Only active modules UIs should be presented.

**Comment by nabokihms** [comment]
There was an idea how to implement this without struggling:
1. Expose metrics in Deckhouse via hooks. Each module has its own hook. Exposed metrics have two labels: name and url.
2. Use Grafana table panel against these metrics to draw a tables with names and links.
