### ISSUE TITLE
Add monitoring for linstor node

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#1366]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

After ([this](https://github.com/deckhouse/deckhouse/pull/1358)) problem (evicted nodes due to long master and system node unavailable)  it looks that it will be good idea to get alert about evicted linstor node(s)

### Proposed Solution

Add prom alert about evicted nodes

**Comment by EvgenySamoylov** [comment]
@kvaps could you please check if it's still valid case?

**Comment by kvaps** [comment]
This should be already fixed in 1.32 by https://github.com/deckhouse/deckhouse/pull/1035

here is alrert:
https://github.com/deckhouse/deckhouse/blob/82ab75598855f0fa9370e8f2864b7eb9a8d9fab3/modules/031-linstor/monitoring/prometheus-rules/linstor-node.yaml#L1-L17

**Comment by EvgenySamoylov** [comment]
Then I prefer to close it as duplicate.
