### ISSUE TITLE
[deckhouse] Installation on managed Kubernetes

### ISSUE THREAD

**Issue by Nitive** [deckhouse/deckhouse#137]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It would be useful to install Deckhouse on existing cluster with managed Kubernetes so the deckhouse modules could be used

### Proposed Solution

1. Add ability to disable control plane related modules
2. Add installation instructions to Getting Started guide

### Additional Information

As far as I know it is already on the roadmap, but I haven't found an issue to subscribe and vote so I decided to create one

**Comment by z9r5** [comment]
Ref: https://github.com/deckhouse/deckhouse/issues/216

**Comment by Nitive** [comment]
🎉
