### ISSUE TITLE
[prometheus] expose Prometheus external labels (instance and replica name) at least for remote_writes 

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#139]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For now, if the user requested `remote_write` to Thanos receiver by deploying a PrometheusRemoteWrite resource in the cluster with two instances of Prometheus (HA mode). We getting errors in the log of one Prometheus instance:
```
caller=dedupe.go:112 component=remote level=error remote_name=ebdb02 url=https://thanos-receive.domain.com/api/v1/receive msg="non-recoverable error" count=100 err="server returned HTTP status 409 Conflict: store locally for endpoint 127.0.0.1:10901: conflict"
```.
That happens because exported series are not containing required labels and the receiver can't deduplicate series properly.

### Proposed Solution

We should set the following parameters to nulls in the Prometheus resource ([here](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/prometheus/prometheus.yaml#L95-L96)):
```
  prometheusExternalLabelName: ""
  replicaExternalLabelName: ""
```
And rely on the default prometheus-operator logic. By default, Prometheus will add `prometheus` and `prometheus_replica` labels.

### Additional Information

We have to implement some additional logic in our alert receiving backend. It can simply drop those two new labels.

**Comment by nabokihms** [comment]
related https://github.com/deckhouse/deckhouse/issues/53
