### ISSUE TITLE
[ingress-istio] native ingress module for istio

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#140]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There isn't native ingress-isito module. But ingress-nginx with optional istio flag.

### Proposed Solution

Make a ingress-istio module with native istio ingress gateway on the edge.

**Comment by EvgenySamoylov** [comment]
Will be realized here: #2898
