### ISSUE TITLE
[node-manager] Get rid of node_lease_handler hook

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#142]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

After merging registry-packages MR from Denis we will be able to distribute right version of curl to all nodes.
The hook node_lease_handler was implemented because i could not patch the Node status directly from centos distributions. 

### Proposed Solution

Distribute the right version of curl and patch Node status directly from 099_reboot bashible step instead of deleting Lease resource.

**Comment by EvgenySamoylov** [comment]
Done at 5059090b86af4fe12e76f2e1ea599d8e72aa2f9b
