### ISSUE TITLE
[log-shipper] Add VPA limit for vector-agent

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#145]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

VPA can scale Vector to huge request numbers. It can cause resource pressure in nodes. 

### Proposed Solution

Add limits to VPA. We have VPA limits in prometheus module.

**Comment by konstantin-axenov** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/a22e29df03d312c14820e57d687e60a87083bda7
