### ISSUE TITLE
[docs][getting-started] Add ssh params for 'bootstrap-phase abort' command after release 1.25

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#146]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have improvements for `dhctl bootstrap-phase abort` command. This  improvements need additional ssh params now.

"Getting started" deployed from main branch now.

We can not add parameters in "Getting started" right now, because we don't release this improvements and abortion command from "Getting started" does not work 

We need to add ssh parameters on "Getting started" page after release. 

### Proposed Solution

Just add it on "Getting started" page or add versioning on "Getting started" page

**Comment by EvgenySamoylov** [comment]
Done at 5393f9b36f94774c32ac139cc6fe763c2d313899
