### ISSUE TITLE
[deckhouse] Custom changelog

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#151]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

200+ Kubernetes clusters are running with Deckhouse, and Deckhouse has 50+ modules. The problem is that the current changelog consumes a lot of information about changes in various modules.

It would be better to show only relevant information for the cluster.

### Proposed Solution

1. We should store the changelog on the Deckhouse git repo (probably in YAML format).
     * On building, it will be added to the container.
     * On release, some script will convert it to markdown to publish it on Github.
2. Deckhouse with a hook will filter this file based on the `global.enabledModules` and store the result to the `Release` custom resource (cluster scoped).
3. The `Release`s quantity will be limited to 10 by default with overriding through deckhouse configmap.

**Comment by EvgenySamoylov** [comment]
Done at 20c8d8cf978f4e27972e2dfb7ff09ab6a3165ca0
