### ISSUE TITLE
Change KubeEtcdHighNumberOfFailedProposals query?

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#152]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is alert for KubeEtcdHighNumberOfFailedProposals, with prometheus query
`max by(node) (increase(etcd_server_proposals_failed_total{job="kube-etcd3"}[10m]) > 5)`
With this query, even for very short events, like R/W time peak for 15-20 seconds, we have a mostly useless alert. It looks very scary, but in fact only distracts from really serious problems.

### Proposed Solution

Maybe change to avg for shorter amount of time, like 5m?

**Comment by Nitive** [comment]
Hi @duckhawk! Flant uses its own alert-management system which keeps alerts in pending state for some time, we can see that by alert annotation `plk_pending_until_firing_for = 10m`. It makes alerts too sensitive for alertmanager users. I've created an issue #34 about that. Please upvote it so Deckhouse team could prioritise it over other issues

**Comment by EvgenySamoylov** [comment]
Alert was deleted in b3a6ba0d1bed196a80bcb72bb3b6bb68b37846e5
