### ISSUE TITLE
Allow deeper customization of created StorageClasses

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#1545]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We are missing a lot of important CSI parameters in the StorageClasses created by deckhouse.

### Proposed Solution

Review existing customizations and add new ones.

**Comment by EvgenySamoylov** [comment]
More detailed here: #1595

**Comment by EvgenySamoylov** [comment]
We need more special cases to get it into work. This one is too general.
