### ISSUE TITLE
[web][getting-started] The installation page should not be reloaded after entering an EE token

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#158]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.*

### Expected Behavior

The installation page should not be reloaded after entering an EE token

### Actual Behavior

The installation page is reloaded after entering an EE token

### Steps To Reproduce

1. Go to the Installation step of the Getting started
2. Choose the Enterprise Edition tab
3. Enter any text in the License key field
4. The page has reloaded

**Comment by konstantin-axenov** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/46c239fe4ce075fff8b9ad4de5bcf0a3531dd713
