### ISSUE TITLE
Add centos8/el8 support, including RockyLinux/AlmaLinux/OracleLinux

### ISSUE THREAD

**Issue by admin5-southbridge** [deckhouse/deckhouse#16]
Subj.

**Comment by nabokihms** [comment]
This one can be closed. Now we [distinguish](https://github.com/deckhouse/deckhouse/blob/e49a7bb3c9df63d9f14afae22bae19a9d44b0daa/candi/bashible/detect_bundle.sh#L37-L40) centos-based distributives and debian-based. The support for [rhel/centos 8.*](https://github.com/deckhouse/deckhouse/blob/e49a7bb3c9df63d9f14afae22bae19a9d44b0daa/candi/bashible/detect_bundle.sh#L19) is also provided.
