### ISSUE TITLE
[web] Select the default site language based on the user's geodata

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#161]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

English is the default language now. But there are two possible languages. 

It is convenient if the language is selected taking into account the user's geodata (IP of course).

### Proposed Solution

Redirect to the appropriate language version of the site using GeoIP

**Comment by konstantin-axenov** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/a44485628c4e1c967f4de63da6ba968c14ebb027
