### ISSUE TITLE
[grafana] Errors during rolling update

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#1623]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.32

### Expected Behavior

The pods must be recreated one by one. The second replica should be up and running correctly.

### Actual Behavior

During a rolling update, the second replica starts recreating while the first replica is not yet fully available (the pod is ready, but the grafana responds with an error).

**Comment by nabokihms** [comment]
There should be a correct readiness probe that will return HTTP Ok only if all dashboards were loaded.
