### ISSUE TITLE
[linter][monitoring] check prometheus rules

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#163]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For now, we are not testing Prometheus rules. And if we merge misformatted rules to the main branch it will break the Deckhouse queue because Helm won't be able to deploy rules to the cluster.

### Proposed Solution

Consider implementing unit tests of Prometheus rules using the [promtool](https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/).

**Comment by nabokihms** [comment]
We can use a dedicated go.mod file for matrix tests and import Prometheus to validate rules.
