### ISSUE TITLE
[dhctl] Prevent ruining existing cluster

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#1657]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When running `dhctl bootstrap` one can use host with existing cluster and dhctl will replace existing resources, especially cm/deckhouse, so cluster may become unusable:

![screen](https://user-images.githubusercontent.com/1055474/171007469-8f7150c1-c9a8-4715-8156-339d87467935.png)

### Proposed Solution

`dhctl bootstrap` should check for existing resources after successful connect to KubernetesAPI. Confirmation dialog or force flag can prevent disasters.

**Comment by nabokihms** [comment]
The idea for the fix is to check the `cluster-is-bootstrap` configmap to avoid bootstrapping bootstrapped clusters.
