### ISSUE TITLE
We need a way to accurately identify all the alerts about futher feature deprecation

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#166]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For the deprecation notification we have either `D8.*Deprecated` or `D8Deprecated.*` alerts. It makes it hard to find/remap/operate over them.

### Proposed Solution

We need some way to identify the deprecation notification alerts uniquely, for example by the separate label.

**Comment by nabokihms** [comment]
@EvgenySamoylov we can add this to the alerts refactoring epic.
