### ISSUE TITLE
[log-shipper] Add user-authz role mappings for log-shipper CRD

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#168]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to create logging configs and log destinations by user-authz roles. 

### Proposed Solution

Add role binding for this CRDs.

**Comment by nabokihms** [comment]
It has already been done.
