### ISSUE TITLE
[candi] Change build process for registry packages

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#1693]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When we build registry packages, for packet downloading we use curl - something like
```
curl -sL https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ $version }}.rpm --output /containerd.io.x86_64.rpm
```
If file is absent in repo, curl writes to output file something like 
```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title> 404 File was not found in NIC </title>
</head>
<body bgcolor="#ffffff">
```
But return code of curl is zero, so we dont see any errors, and builded packet is incorrect.

### Proposed Solution

1. Use wget instead of curl.
2. Use curl flag `-f`.

**Comment by nabokihms** [comment]
Does the '-f' flag solve the problem?

**Comment by RomanenkoDenys** [comment]
> Does the '-f' flag solve the problem?

Yes, it is a good solution
