### ISSUE TITLE
[upmeter] Authenticate agent using client certificate

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#170]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25.0

### Expected Behavior

Upmeter hook [`order_certificate`](https://github.com/deckhouse/deckhouse/blob/release-1.25/modules/500-upmeter/hooks/order_certificate) should generate client certificate that is mounted to agent for authentication elsewhere. 

### Actual Behavior

The certificate secret does not generate and is not used in agent templates.

**Comment by nabokihms** [comment]
We migrated everywhere to use tokens for authentication. Let's delete the hook https://github.com/deckhouse/deckhouse/blob/main/modules/500-upmeter/hooks/order_certificate.go

**Comment by EvgenySamoylov** [comment]
Was fixed here #2019
