### ISSUE TITLE
Manage kernel install on bootstrap

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#176]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases, especially in closed contours, we wants to install specific kernel versions on nodes, approved by security officers. For node groups it isn't problem - we have parameters to disable manage kernels on nodes. But this parameters doesn't work for master node group in bootstrap process.

### Proposed Solution

add kernel manage parameters to bootstrap process.

**Comment by konstantin-axenov** [comment]
Now you can configure Deckhouse to not manage kernel and use new feature custom NodeGroupConfiguration (https://github.com/deckhouse/deckhouse/pull/492).
