### ISSUE TITLE
[docs] Add parameter names to the search index 

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#1773]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.33

### Expected Behavior

The search on the site should also search by the name of the parameters from OpenAPI specifications.

### Actual Behavior

The search does not search by name of a parameter from CRD or resource.

### Steps To Reproduce

Examples of a search query that does not give results:
- enableIngressGateway
- pushToClientRoutes

**Comment by EvgenySamoylov** [comment]
Lets consider to migrate to another search engine, for example Google.

**Comment by z9r5** [comment]
I think we should focus on search issues (what we want from the search and what we want to improve), but not on a tool. 
An example of the werf.io website allows us to assume that using Google will not give something significant.
