### ISSUE TITLE
[ci] Deploy images using sha digests instead werf tags

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#1825]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Werf content tagging are convinient to use during building process to avoid rebuilding images if it is unnecessary. However, we cannot be 100% sure, that images used in the cluster is the same as we expected them to be. Teoretically, frauders can take control over deckhouse registry (lower chances, but still) and substitute images.

### Proposed Solution

SHA256 digest is an [`immutable identifier`](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier) of a container image. We can be sure that this is the same image by pulling it using a digest.

We use werf report to specify images tags. It looks like this:
```json
{
  "moduleName": {
     "image": "tag"
   }
}
```

After building process is finished, we can collect all digests using crane and convert report to the following structure:
```json
{
  "moduleName": {
    "image": {
      "tag": "tag",
      "sha256": "sha256"
    }
  }
}
```

Then we can use it to deploy our images to the cluster.

NOTE: We also need to add a listing rule to check that all images have a sha.

**Comment by duckhawk** [comment]
We are waiting for the implementation of generating the RepoDigests list while building with werf.
