### ISSUE TITLE
Local Helm tests do not work

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#183]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.17

### Expected Behavior

Helm tests work when running go test in the template_tests directories.

### Actual Behavior

Tests fail on modules that are split into multiple editions.

### Additional Information

This behavior has emerged when we split the deckhouse into multiple editions. We build them into one container via [this](https://github.com/deckhouse/deckhouse/blob/main/tools/build.go) logic. Consider abstracting this logic enough to be used inside the helm tests runner to perform necessary relocations before running tests.

**Comment by konstantin-axenov** [comment]
We consider making while Deckhouse OpenSource so there won't be any ee and fe folders
