### ISSUE TITLE
[go_lib] implement general generate_admission_webhook_cert hook

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#184]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For now, we are using the same code twise.

### Proposed Solution

Move `generate_admission_webhook_cert` hook to `go_lib`.

### Additional Information

Consider implementing additional checks:
- that certificate stored in secret is not expired
- that certificate stored in secret has proper Names and Hosts defined

**Comment by name212** [comment]
This hook is similar to the following hooks:
- [one](https://github.com/deckhouse/deckhouse/blob/main/modules/040-node-manager/hooks/gen_bashible_apiserver_certs.go)
- [two](https://github.com/deckhouse/deckhouse/blob/main/modules/101-cert-manager/hooks/generate_webhook_certs.go) (here we save CA private key, but is bad idea, and we can rewrite it)
- [three](https://github.com/deckhouse/deckhouse/blob/main/modules/301-prometheus-metrics-adapter/hooks/order_certificate)
- probably, we have more similar hook

All hooks generate TLS certificate  with long live time for in-cluster communications with http-services (webhooks, bashible-api-server, etc..) .

When I was rewriting [this hook](https://github.com/deckhouse/deckhouse/blob/main/modules/301-prometheus-metrics-adapter/hooks/order_certificate) I created new hook in go_lib with `internal_tls` name (maybe we find better name for it)
This hook is now on review. I want add issue with refactoring all similar hooks on new hook after merge my pull request.

But you got ahead of me :-)

**Comment by nabokihms** [comment]
I think it was implemented. Leaving it closed then.
