### ISSUE TITLE
[control-plane-manager] Backup etcd 

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#1854]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Simplify the backup process etcd

### Proposed Solution

Make daemonset with backup script, which uses restic

**Comment by EvgenySamoylov** [comment]
Closed in favor of #1441
