### ISSUE TITLE
Prometheus expired certificate

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#1860]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.33

### Expected Behavior

When prometheus certificate updates, it is used for connection with kube-apiserver

### Actual Behavior

The connection between prometheus and kube-apiserver uses expired certificate which leads to alerts.

### Additional Information

The fix requires refactoring of 340-monitoring-kubernetes module.

**Comment by nabokihms** [comment]
> The fix requires refactoring of 340-monitoring-kubernetes module.

The module was refactored. Now it uses tokens for authentication.
