### ISSUE TITLE
[deckhouse][helm] handle "has no deployed releases" helm error

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#187]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Rarely we can see the following messages in deckhouse logs:
```
Error: UPGRADE FAILED: "moduleName" has no deployed releases
```
When it happens deckhouse queue processing is stuck.

To resolve that in place we can delete all helm Secrets of `moduleName` releases:
```bash
kubectl -n d8-system get secrets | grep moduleName | awk '{ print $1 }' | xargs kubectl -n d8-system delete secret
```

### Proposed Solution

Implement a special handler that automatically resolves such situations.

**Comment by nabokihms** [comment]
Should be fixed by new embeded helm executor in addon-operator
https://github.com/flant/addon-operator/pull/234

https://github.com/flant/addon-operator/blob/8f66c95f5caa39fba8d2419c4c6f6e4c521ba3a9/pkg/helm/helm3lib/helm3lib.go#L178-L186
