### ISSUE TITLE
[extended-monitoring] Enable cert-exporter by default

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#1876]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to be sure that certificates are valid in namespaces that have extended-monitoring enabled.

### Proposed Solution

Enable cert-exporter by default.

**Comment by EvgenySamoylov** [comment]
Looks like we have enough certificates monitoring at a time.
