### ISSUE TITLE
[istio] switching off istio module doesn't remove iop resource

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#188]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main branch

### Expected Behavior

After disabling module there shouldn't be any signs of module except CRD.

### Actual Behavior

The d8-istio namespace can't be deleted due to iop resource in it/

**Comment by 31337Ghost** [comment]
In addition there is one more resource preventing namespace deletion:
```console
# kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n d8-istio
NAME                                                      MODE   CPU   MEM   PROVIDED   AGE
verticalpodautoscaler.autoscaling.k8s.io/istiod-v1x10x1   Auto               False      14m

NAME                                     REVISION   STATUS    AGE
istiooperator.install.istio.io/v1x10x1   v1x10x1    HEALTHY   15m
```

It is [VPA](https://github.com/deckhouse/deckhouse/blob/main/ee/modules/110-istio/templates/control-plane/iop.yaml#L9-L10) which also has a finalizer:
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  finalizers:
  - istio-finalizer.install.istio.io     <<<<-----
```

**Comment by apolovov** [comment]
Need an experiment to make sure that istio module switches off properly.
If in isn't — add some afterDeleteHelm hooks.

**Comment by apolovov** [comment]
[The fix](https://github.com/deckhouse/deckhouse/pull/6906) is in 1.57.
