### ISSUE TITLE
[cloud-provider-*] Add opportunity creating additional disks for static-node-group  

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#1891]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases clients need to create additional disks for their own requirements.

### Proposed Solution

Add into openapi specs.
Add creating disks to terraform modules

**Comment by EvgenySamoylov** [comment]
We need to know the exact use case of the feature request. It's unclear from the description.
