### ISSUE TITLE
[dhctl] Join static node command

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#1910]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Often we bootstrap nodes for static clusters. For it we need do the following:
- login to node
- check node is empty (not used in the current or another clusters)
- login to control-plane node 
- get bootstrap script from secret `kubectl -n d8-cloud-instance-manager get secret manual-bootstrap-for-ng`
- login to node and run bootstrap script.
- for master node groups we should wait when control plane manager is ready.

We can replace it with one command `dhctl node join-to-node-group --node-group=node-group-name node-host-1 node-host-2... node-host-N`

### Proposed Solution

Create handler for `dhctl node join`
In the handler:
- check node-group is exists and static
- get bootstrap script for node group
- for master node in order for another can do it in parallel:
- connect to node
- get hostname for node
- check node is empty (not run on the node: kubelet, CRI, bashible, can check that open only openssh port)
- run bootstrap script on node
For master node group wait control-plane-manager is ready.

Wait all nodes is ready by hostnames.

**Comment by EvgenySamoylov** [comment]
It's possible to use ansible playbook for bulk bootstrap as a workaround: https://deckhouse.io/en/documentation/v1/modules/040-node-manager/faq.html#how-do-i-add-a-batch-of-static-nodes-to-a-cluster
