### ISSUE TITLE
Make it possible to schedule long-term prometheus to the separate node

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1919]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Long-term Prometheus is always launched in a single instance, while the system Node Group consists of a minimum of two nodes. Therefore, one out of two nodes is always underutilized.

### Proposed Solution

Create a separate node group for scheduling the long-term Prometheus instead of scheduling it to the system nodes.

**Comment by nabokihms** [comment]
Closing as a duplicate of https://github.com/deckhouse/deckhouse/issues/3352
