### ISSUE TITLE
Make it possible to schedule deckhouse pod to the separate node

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#1921]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse is always launched in a single instance, while the master Node Group consists of three nodes as a rule. Therefore, two out of three nodes are always underutilized.

### Proposed Solution

Create a separate node group for scheduling Deckhouse pod instead of scheduling it to the master nodes.

**Comment by konstantin-axenov** [comment]
This is documented [here](https://deckhouse.io/en/documentation/v1/deckhouse-faq.html#how-do-i-run-deckhouse-on-a-particular-node).
