### ISSUE TITLE
[ingress-nginx] HostPortWithFailover bug with failover controller

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#193]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.17

### Expected Behavior

Traffic goes through the failover controller only when a primary controller is not available

### Actual Behavior

TCP connections stuck in keepalive sessions and also CONNMARK couldn't mark connections in a nat table. This leads to wrong sessions when traffic goes to a failover controller while a primary controller is alive.

**Comment by konstantin-axenov** [comment]
Closed in dec403ca948de9f2c93cd1966352681dafeca2b3
