### ISSUE TITLE
[ceph-csi] orphan rbd image monitoring

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#1932]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It would be nice to detect orphan rbd images which aren't mounted anywhere. So we could save the disk space.

### Proposed Solution

:shr

**Comment by konstantin-axenov** [comment]
Seems that it have to be done on ceph side.
