### ISSUE TITLE
[bashible] install registry packages fails, if registryDockerCFG in old format

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#194]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24

### Expected Behavior

if registryDockerCfg don't contain "auth" field, bashible-apiserver must use username and password fields to  construct registry.auth parameter for bashible.

### Actual Behavior

if registryDockerCfg don't contain "auth" field, bashible-apiserver cannot parse this record properly, and bashible don't get proper formed registry.auth parameter.

### Steps To Reproduce

Run cluster with registryDockerCfg without auth field.

**Comment by konstantin-axenov** [comment]
@RomanenkoDenys Is this issue still valid? Maybe it is fixed in https://github.com/deckhouse/deckhouse/pull/397?

**Comment by RomanenkoDenys** [comment]
This issie was resolved in https://github.com/deckhouse/deckhouse/pull/521.
