### ISSUE TITLE
no matches for kind "IngressNginxController" in version "deckhouse.io/v1"

### ISSUE THREAD

**Issue by ox7a59** [deckhouse/deckhouse#1958]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.33.12

### Expected Behavior

```
Ingress Nginx controller is created
```

### Actual Behavior

```
no matches for kind "IngressNginxController" in version "deckhouse.io/v1"
```

### Steps To Reproduce

```
1. Install Ubuntu 20.04
2. I have two virtual machines (one deploy and one master)
3. I just run installation with Stable branch.
4. Some errors occured during install + cannot create Ingress Nginx at the end.
```

### Additional Information

Installed on bare metal using [this](https://deckhouse.io/en/gs/bm/step2.html) instruction.

### Logs

```shell
https://pastebin.com/KiRDkPDB
```

**Comment by ox7a59** [comment]
Need to run:
```
kubectl patch nodegroup master --type json -p '[{"op": "remove", "path": "/spec/nodeTemplate/taints"}]'
```

And wait for 10 minutes approximately

**Comment by Nirvandil** [comment]
Same here.
It does not work neither after 10 minutes nor after 1 hour, why this issue is closed? 
Reboots and rollout restart for deckhouse didn't helps either.

**Comment by Nirvandil** [comment]
It's fixed after removing taints from master node 
`kubectl patch node $NODE_NAME_HERE --type json -p '[{"op": "remove", "path": "/spec/taints"}]'`
Removing them from master nodegroup does not propagates to node for some reason.
