### ISSUE TITLE
[deckhouse][helm] handle "another operation is in progress" helm error

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#197]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Rarely we can see the following messages in deckhouse logs:
```
helm upgrade failed: another operation (install/upgrade/rollback) is in progress
```
When it happens deckhouse queue processing is stuck.

To resolve that in place we can delete all helm Secrets of `moduleName` releases:
```bash
kubectl -n d8-system get secrets | grep moduleName | awk '{ print $1 }' | xargs kubectl -n d8-system delete secret
```

### Proposed Solution

Implement a special handler that automatically resolves such situations.

### Additional Information

The core issue is described here https://github.com/helm/helm/issues/8987.

This issue is partly related to another https://github.com/deckhouse/deckhouse/issues/187.

The problem still exists with modifications from https://github.com/flant/addon-operator/pull/234.

**Comment by konstantin-axenov** [comment]
Fixed in https://github.com/flant/addon-operator/pull/259
