### ISSUE TITLE
[vertical-pod-autoscaler] Bump CRD version to v1

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#198]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

in upstream version of vertical-pod-autoscaler exists autogenerated crd v1 - https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml. We must use this crd version in future.

### Proposed Solution

Bump vertical-pod-autoscaler crd version in deckhouse to upstream version after next release of upstream vertical-pod-autoscaler.

**Comment by EvgenySamoylov** [comment]
Realized in ca19e171d370bde8a1d197b328dbacf67345e6d4
