### ISSUE TITLE
[monitoring-kubernetes] There is no metric for OOM killed dashboard in Grafana

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#1996]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34.1

### Expected Behavior

1. oom:normalized rules are inconsistent.
2. Merge oom:normalized metrics with kube-state-metrics exported oom kill counter to always report OOM's in the Namespace/Controller/* dashboards.

### Actual Behavior

oom:normalized recording rules for the ebpf-exporter are wrong. Review them.

**Comment by EvgenySamoylov** [comment]
Closed in favor of #2723.
