### ISSUE TITLE
[cloud-provider-aws] csi-controller not reacts on AWSClusterConfiguration provider credentials change

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#200]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

21.03-hotfix-2021-06-25.1

### Expected Behavior

After credentials are updated in AWSClusterConfiguration, the csi-controller should either be restarted or somehow refresh the credentials.

### Actual Behavior

`csi-controller` fails communication to AWS:
```
I0923 10:12:07.244958      1 csi_handler.go:226] Error processing "csi-92dd52d7ff7f6aaf05a70ba9289072dcd8e9dd60ab847aa624b5b8cc2a75c385": failed to detach: rpc error: code = Internal desc = Could not de
tach volume "vol-03a47d9ca5ac84a10" from node "i-069de2d86d0aaee68": error listing AWS instances: "AuthFailure: AWS was not able to validate the provided access credentials\n\tstatus code: 401, request id: d66246ad-9bb9-4ee1-8827-3b72afe11a9b"
```

### Additional Information

Credentials are passed to the container as envs with `valueFrom.secretKeyRef` and are not updated on the fly after Secret is updated. Also, `cloud-provider-yandex` csi-controller is affected.

**Comment by nabokihms** [comment]
@EvgenySamoylov, let's add it to our roadmap. This is a rare situation yet nearly impossible to debug if you are just an ordinary user.
