### ISSUE TITLE
Make it possible to change the class priority for log-shipper-agent

### ISSUE THREAD

**Issue by NikolayGorbatov** [deckhouse/deckhouse#2016]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Log-shipper-agent starts with priority-class cluster-low by default, that is a common reason for evicting pods from production cluster and as a result, part of the logs are lost.

### Proposed Solution

Make it possible to specify priorityclass for logshipper pods in cm deckhouse

**Comment by nabokihms** [comment]
We discussed it with Nikolay and agreed that changing priority class to cluster-medium solves the issue
https://github.com/deckhouse/deckhouse/blob/7d5b22735ae0c6a3fd601237c34c847a4be309fd/modules/460-log-shipper/templates/daemonset.yaml#L65

I'm going to close this one.
