### ISSUE TITLE
[ceph-csi] update ceph-csi to v3.5.0 (or higher version)

### ISSUE THREAD

**Issue by pkonovalov** [deckhouse/deckhouse#2021]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Ability to make intree RBD migration of  https://github.com/ceph/ceph-csi/blob/devel/docs/intree-migrate.md

### Proposed Solution

Update ceph-csi image to v3.5.0 or above https://github.com/deckhouse/deckhouse/blob/main/modules/099-ceph-csi/images/cephcsi/Dockerfile

**Comment by EvgenySamoylov** [comment]
PR is here: #2973
