### ISSUE TITLE
[user-authn] ingress limit-rpm leads to unclear IngressResponses5xx alerts

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#204]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Dex-auth is [rate-limited by ingress](https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/templates/dex/ingress.yaml#L35) for 10 requests accepted from a given IP each minute. If some source IP exceeds that threshold we getting alerts about 5xx responses, but it's not clear what really happened. 

Consider that the current `503 Service Unavailable` response code might be not clear for the case of rate-limiting and we can change it. This approach will eliminate 5xx alerts.

It might be useful to allow users to tune the current default `limit-rpm` value. Even setting it to zero.

### Proposed Solution

- Change the `limit-req-status-code` ingress-nginx [parameter](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#limit-req-status-code) to `429 Too Many Requests`.

OR
- Implement limit-rpm logic with custom response code as `nginx` sidecar container to dex pod.

### Additional Information

Would be great to have the ability to know what source IPs were throttled, even just from container logs `kubectl logs -f -l app=dex -c throttler`.

**Comment by nabokihms** [comment]
Changing the rate limit response code may be a breaking change.

For this particular case, we can switch the `Ingress5xx warnings` off with the annotation and alert only on 100% errors:
```
# switch off warnings because it's impossible to get 101% of anything
threshold.extended-monitoring.flant.com/5xx-warning: "101" 
threshold.extended-monitoring.flant.com/5xx-critical: "100"
```

**Comment by konstantin-axenov** [comment]
Close in https://github.com/deckhouse/deckhouse/commit/1f430c5ce7ed497447a7342dc0a5603c34a9b355
