### ISSUE TITLE
[containerd] add ability to set containerd rootDir

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#2040]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases, especially in bare-metal installations, we want to be able to place containerd rootDir on the folder on additional disk, mounted in system. We have such ability for kubelet, via nodeGroup parameter, but do not have for containerd.

### Proposed Solution

1. Add a parameter for containerd rootDir to node group.
2. Use NodeGroupConfiguration script on node bootstrap to make symlink or bind mount from /var/lib/containerd to new location.

**Comment by az67128** [comment]
Also need this functionality

**Comment by BurykinNikolay** [comment]
same!

**Comment by hotmeatballs** [comment]
+
