### ISSUE TITLE
change cri type for single-master installations

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#205]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Today we don't have ability to change cri type for single-master installations, because bashible scripts needs to get disruption approval, but in cri change process apiserver is going down and bashible scripts fails on disruption approval.

### Proposed Solution

Add special key (it can be env variable, or special file), which enforce disruption approval in bashible scripts.
Something like this:

```
bb-deckhouse-get-disruptive-update-approval() {
    if [ "$FIRST_BASHIBLE_RUN" == "yes" ]; then
        return 0
    fi
   
    if [ -f /var/lib/bashible/disruption-approval ]; then
        return 0
    fi
```

### Additional Information
Procedure:
* scale down to 0 webhook-handler in d8-system ns.
* delete validatingwebhookconfigurations (kubectl -n d8-system delete validatingwebhookconfigurations.admissionregistration.k8s.io d8-deckhouse-validating-webhook-handler).
* change cri in ng or defaultCRI in d8-cluster-configuration.
* Wait to change cri on nodes.
* scale up webhook-handler.

**Comment by EvgenySamoylov** [comment]
Resolved in 24d188e795147041608d64b2ff8682b510e1a950
