### ISSUE TITLE
Adding portainer to deckhouse installer

### ISSUE THREAD

**Issue by balasu** [deckhouse/deckhouse#207]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26

### Expected Behavior

Portainer is a free, open source toolset for managing containerized applications. It works with Kubernetes, Docker, Docker Swarm, Azure ACI in both data centres and at the edge.

Portainer removes the complexity associated with orchestrators so developers can deploy apps quickly, easily and accurately. In addition to managing apps, it can be used to observe the behavior of containers, manage the underlying platform and provide the security and governance necessary for organization to deploy containers widely.
This add-on service will be enabled on nodeport 30777 and internally runs on 9000 port.
As part installation this add-on should be installed by default 

### Actual Behavior

Curently there is no support to add portainer as part of deckhouse installer.

### Additional Information

document about portainer https://docs.portainer.io/v/ce-2.9/

**Comment by raabdullaev** [comment]
The issue is stale. Nobody has been asking for this for 3 years.
