### ISSUE TITLE
Internal self-signed CAs are valid for a year and are not re-issued

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#2075]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34.4

### Expected Behavior

Certificates are always valid.

### Actual Behavior

Some certificates (webhook-handler, for example) become invalid after a year.

### Steps To Reproduce

1. Bootstrap a cluster
2. Wait for a year
3. webhook-handler is not serving requests anymore

### Additional Information

I believe, the root of the problem lies [here](https://github.com/deckhouse/deckhouse/blob/d80ea517799056e39261b9c219a984bfa5221016/go_lib/certificate/selfsigned.go#L96). This "Default" equals one year [here](https://github.com/cloudflare/cfssl/blob/v1.5.0/config/config.go#L690).

**Comment by nabokihms** [comment]
Should be fixed by https://github.com/deckhouse/deckhouse/pull/2146
