### ISSUE TITLE
[grafana] Kubernetes Cluster / Control Plane Status panel dont work as expected

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#210]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24

### Expected Behavior

Graphs on Kubernetes Cluster / Control Plane Status grafana panel must work

### Actual Behavior

Graphs on Kubernetes Cluster / Control Plane Status grafana panel don't work

### Steps To Reproduce

Open grafana and go to the Kubernetes Cluster / Control Plane Status

### Additional Information

Graphs don't work because prometheus metrics from kube-apiserver was renamed.
https://github.com/kubernetes/kubernetes/pull/72336

**Comment by EvgenySamoylov** [comment]
Done at 359715a862acf67c2c3784b958a45b60e5bb4dcc
