### ISSUE TITLE
[extended-monitoring] Group cron job alerts

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2106]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34

### Expected Behavior

All alerts are groupped

### Actual Behavior

Alerts don't have group annotations. For every failed CronJob a new alert is created.

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/pull/6715
