### ISSUE TITLE
Bump Grafana version to 8.1.x

### ISSUE THREAD

**Issue by 1001v** [deckhouse/deckhouse#212]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Hello. I use Grafana to display pod logs via loki/log-shipper stack, because it's a pretty simple solution and fits in Deckhouse very well. However, the current version of Grafana, used in Deckhouse, doesn't have many improvements, which were made since version 7. The most notable improvement for me is this: https://github.com/grafana/grafana/issues/25205. So, at the moment, the log viewing in Grafana is limited and not as good, as it could be. Thank you.

### Proposed Solution

Bump Grafana version to 8.1.x.

**Comment by konstantin-axenov** [comment]
Closed in f67c1895cbdfb9332234537232aea9d86ced51a3
