### ISSUE TITLE
[node-manager] monitor useless NodeGroups

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2124]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There was a case when customer ordered a NodeGroup and instances were installed in a cloud. But the NG was forgotten without useful payload. So the offencive bill was issued.

### Proposed Solution

Monitor:
* Non-special Nodes in NG have pods with non-d8 heritage.
* Special NGs don't have special pods (no ingress controllers on frontend nodes).
* Special NGs with custom labels don't have pods with similar nodeSelectors.

**Comment by EvgenySamoylov** [comment]
I suppose we need more general solution to avoid unexpected bills: #945
