### ISSUE TITLE
[node-manager][standby-holder] Holder is being deployed if minPerZone == maxPerZone

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#214]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.17

### Expected Behavior

We don't need standby-holder if minPerZone and maxPerZone are equal.

### Actual Behavior

standby-holder is always being deployed.

**Comment by 31337Ghost** [comment]
It would be enough to add a condition similar to [that one](https://github.com/deckhouse/deckhouse/blob/main/modules/040-node-manager/hooks/discover_standby_ng.go#L196). Continuing the for-loop if `minPerZone == maxPerZone`.
