### ISSUE TITLE
[site][getting-started] Existing cluster

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#216]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It would be useful to install Deckhouse on existing cluster.

### Proposed Solution

Add installation instructions to Getting Started guide

**Comment by EvgenySamoylov** [comment]
Close as a duplicated issue.
