### ISSUE TITLE
[ci] Get `summary` and `section` field for changelog from pull request title

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#2168]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We always write title for pull request in the next format:

```
[module-1][module-2]...[module-n] Summary
```

I always set pull request title and copy-paste this title to `summary` section in all changelog sections and after it set `section` from modules in the braces `[]`. 

We can parse pull-request title and create sections for changelog automatically, when pull-request was created or title was changed.

And, maybe, we can set `type=(bug | chore)` if pull request have `type/(bug | chore)` label. 

`impact` commented by default. 

For 90% cases we will automate filling changelog section.

We can add `impact/high` and `impact/low` labels and i think you know why :-)   

### Proposed Solution

When pull-request created or changed:
- get pull request title (https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request pull request object contains `title` field)
- split string on two sub-strings by ` ` space (module name can not contains spaces and we we will agree that module will wrap by braces `[]` and modules will not separate by any one symbol) 
- parse modules with [this](https://regex101.com/r/Edo4c4/1) regexp and trim modules name from symbols `[` and `]`
- create or change changelog sections with modules list and new summary

**Comment by shvgn** [comment]
It is not that simple. 

Some changes are not directly deducible from where the changes were made. E.g. changes in helm_lib or go_lib actually change things in many other modules. But users care about the behavior more that implementation. So we have to add multiple similar changes for many section.
Look at changes block in this PR and imagine its title https://github.com/deckhouse/deckhouse/pull/2056

**Comment by shvgn** [comment]
Moreover, if you will to add changes by hand, the 'changes action' should somehow distinguish automatic changes from yours one, not to overwrite handwritten input. That will make us introduce more complication than we'll gain from it, IMO.

**Comment by shvgn** [comment]
And one more thing. In changelog we read "what have been done", in the past form. In PRs we write what to do, in imperative form. Imperative changelog is not read well. 

Do you know any good imperative changelog? Compare:

```
Changelog v1.2.3

- Add new feature
- Fix annoying bug
```

vs 

```
Changelog v1.2.3

- Added new feature
- Fixed annoying bug
```

**Comment by shvgn** [comment]
I would do the opposite: remove all [square brackets] in favor of labels.
