### ISSUE TITLE
[bashible] ntp sync in all nodes

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#217]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.20

### Expected Behavior

automatic time synchronization

### Actual Behavior

No automatic time sync
Not installed any time sync daemons

**Comment by alexey-gavrilov-flant** [comment]
maybe it is worth adding to the servers  pool.ntp.org
or giving the ability to specify custom server at the cluster level

**Comment by konstantin-axenov** [comment]
We want to try chrony as the solution for fast and accurate time synchronization.

**Comment by EvgenySamoylov** [comment]
Done at 0b2d4fda9985106c541d1a6d9c26c698f75d0c2b
