### ISSUE TITLE
Mistake in chaos module documentation

### ISSUE THREAD

**Issue by trublast** [deckhouse/deckhouse#2180]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34

### Expected Behavior

Chaos mode in example corresponds allowed mode values

### Actual Behavior

Allowed values for chaos.mode: Disabled, DrainAndDelete
Example chaos.mode: DrainAndReboot

### Additional Information

1. It is not specified how many nodes in node group will be drained after the specified period. I guess one
2. DrainAndDelete and DrainAndReboot seems different for static and cloud clusters. Please clarify in docs. Will DrainAndDelete remove node from static NG?

**Comment by z9r5** [comment]
@trublast Thank you!
