### ISSUE TITLE
[Upmeter] Fix smoke-mini image on failing pods

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#219]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24

### Expected Behavior

When smoke-mini image is not available, it is usually outdated. At the same time, deckhouse values contain correct image repo. Hence deckhouse is able to force-change the image for failing pods. It just does not do that. Failing pods require manual interruption: restarting deckhouse and deleting failing StatefulSets to avoid copying bad images to values again.

The `resheduler` hook can detect that the image is not desired, clean the StatefulSet values instead of trusting them, and delete failing pods. Thus it will effectively reshedule missing smoke-mini pods as at first run. 

Deckhouse can possibly detect other problems related to image.

### Actual Behavior

Smoke mini image is taken from its current StatefulSet object as granted regardless of pod status. Thus failing pods remain failing, and PDB in this case stops the resheduling

### Steps To Reproduce

1. Scale deckhouse to 0.
2. Change images in smoke-mini statefulsets to inexising or failing.
3. Scale deckhouse back to 1.
4. Deckhouse does not cure statefulsets with correct images.

**Comment by konstantin-axenov** [comment]
@shvgn Is this issue still valid?

**Comment by shvgn** [comment]
@konstantin-axenov  I think no
