### ISSUE TITLE
[user-authn] Do not use colons in DexClient ids

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#220]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.24.20

### Expected Behavior

The problem is that there are two main ways to send credentials to the IdP:
* Basic auth header - `client_secret_basic`
* HTTP POST parameters - `client_secret_post`

For the `client_secret_basic` we cannot have colons in client ids, because the combined string of id `na:me` and `password` for the header on the side of a server will be decoded as id `na` and password `me:password`.

### Actual Behavior

1. We do not need colons in client ids. It is possible to use `@` or anything else.
2. To migrate smoothly, we need to deploy two oauth2 client crs for the single dex client cr. The one with colons in id and the one without it. The password should be the same.

**Comment by konstantin-axenov** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/4dd9775facd8bb3eb67197ef0c4ca8276a91c328
