### ISSUE TITLE
[candi] Install the latest kernel in the CentOS distribution

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#2209]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

More and more software (mainly cilium) relies on the latest kernel features. CentOS kernels are WOEFULLY outdated.

### Proposed Solution

candi subsystem installs the latest kernel

**Comment by EvgenySamoylov** [comment]
We have dropped the kernel management in #3076.
