### ISSUE TITLE
[node-manager] [standby-holder] implement calculation of the number of resources that standby-holder shouldn't hold

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#222]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The current NodeGroup parameter `standbyHolder.notHeldResources` is not usable if there are DaemonSet with VPA exists. Resource requests of DaemonSet Pods will be provided automatically by VPA and the administrator won't be able to configure `notHeldResources` correctly.

### Proposed Solution

Discover the number of resources that standby-holder shouldn't hold from cluster resources. 

### Additional Information

Consider resolving https://github.com/deckhouse/deckhouse/issues/214 and the current issue together.

**Comment by EvgenySamoylov** [comment]
Looks like we need to fix the StandBy feature instead.

**Comment by konstantin-axenov** [comment]
Discussed that it seems proper to make patch for autoscaler:
- Autoscaler should be aware of standby nodes amount
- Autoscaler taints standby node
- If it is calculated that pending pods can be scheduled on tainted standby node, autoscaler removes taint and starts to create new standby node

**Comment by EvgenySamoylov** [comment]
Will be realized in #2959.
