### ISSUE TITLE
[control-plane-manager] Backup etcd to local disk

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#2230]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We discussed inside our command and we piked out next cases for backup etcd db:
- `kubectl delete ns --all` or another removing resources from cluster 'accidentally'. Good point for fast recovery.
- Full lost control-plane node in single control-plane configuration. When user choice single control-plane configuration user understand all risks. For critical services user should choice multiple control-plane nodes configuration.
- Lost cluster from hackers. We are confident in our product. Deckhouse is secure platform.

Thus, we should protect us from first case. We can  doing backup and store backup on control-plane node.

### Proposed Solution

- Create daemonset with backup script [here](https://deckhouse.io/en/documentation/v1/modules/040-control-plane-manager/faq.html#how-do-make-etcd-backup). Script should run in infinite loop.
- Mount `/var/lib/etcd` dir to daemonset 
- decide, save backup to same disk with etcd data or on the root disk (in this case we should mount second directory for backup)
See #2226 .
- change script. Not use Kuse-API for copy backup, use tmp file for backup.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/pull/9637
