### ISSUE TITLE
[openapi] Incorrect regex for resources

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2233]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34

### Expected Behavior

This is valid config
```
  prometheus: |
    vpa:
      maxCPU: 1.5
      maxMemory: 5.0Gi
```

### Actual Behavior

This regex
```
^[0-9]+(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
```
Leads to error
```
"ConvergeModules failed in phase 'StandBy', requeue task to retry after delay. Failed count is 162. Error: config not valid: 3 errors occurred:\n\t* 'prometheus' module section in ConfigMap/deckhouse is not valid\n\t* \"prometheus.vpa.maxMemory\" must validate one and only one schema (oneOf). Found none valid\n\t* prometheus.vpa.maxMemory should match '^[0-9]+(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'\n\n"
```

**Comment by z9r5** [comment]
Fixed in #2940
