### ISSUE TITLE
[prometheus] HTTPS and FQDN support for additional alertmanager

### ISSUE THREAD

**Issue by alexeybobylev** [deckhouse/deckhouse#227]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

HTTPS is needed to encrypt traffic. FQDN is required to maintain one DNS record instead of updating multiple resources in different clusters.

### Proposed Solution

ExternalName can help with FQDN. I'm not sure about how to add HTTPS support.

**Comment by konstantin-axenov** [comment]
Closed in 39b8bfb66ee899c04601df941ace781ea292c10c
