### ISSUE TITLE
Add ability to specify certManager credentials as Secrets

### ISSUE THREAD

**Issue by o-morhunenko** [deckhouse/deckhouse#228]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sensitive data is stored in the deckhouse config as a plain text.

### Proposed Solution

Add ability to specify certManager credentials as Secrets

**Comment by nabokihms** [comment]
If you do not want to use Deckhouse configmap for storing credentials, it is always possible to create your Issuer or ClusterIssuer and use it. There is an excellent example in the doc on how to add your issuer and save its credentials to the secret (you can create not only an issuer for the vault yet any issuer you want).
https://deckhouse.io/en/documentation/v1/modules/101-cert-manager/faq.html#vault-integration
