### ISSUE TITLE
[deckhouse] consistent updates through versions

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#230]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes migrations are implemented with consideration to be applied sequentially. But if the deckhouse was pinned to the old version for too much time some migrations will be skipped during the update to the latest version.

### Proposed Solution

Basing on new update mechanics https://github.com/deckhouse/deckhouse/issues/185 it should be quite possible to implement consistent updates.

**Comment by yalosev** [comment]
Yup. We have all releases created into a cluster and they are applied one by one, so we can't skip any release
