### ISSUE TITLE
Linux kernel 5.x support for CentOS 7

### ISSUE THREAD

**Issue by mobilesfinks** [deckhouse/deckhouse#232]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We use the Centos 7 Linux distribution with the kernel-ml from the elrepo repository because it is more stable when used with the newest Docker versions. When bootstrapping, ```dhctl bootstrap``` attempts to install kernel-3.10.0-1127.el7 while the more recent 5.14.12-1.el7.elrepo.x86_64 version is already in use in our system. In addition, there is a 3.10.0-1160.el7 kernel on the host, but the bootstrapper doesn't see it.

### Proposed Solution

Add support for 5.x kernels in Deckhouse.

**Comment by EvgenySamoylov** [comment]
Fixed by #1173
