### ISSUE TITLE
[modules] add an annotation to component's controllers containing used software version

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#236]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

As far as our images tags contain only content-hash without a human-readable version it would be nice to provide an easy way of determining which software version is currently used in a particular component's image.

### Proposed Solution

Add an annotation to component's controllers containing used software version, which is defined in [candi/version_map.yml](https://github.com/deckhouse/deckhouse/blob/main/candi/version_map.yml).

**Comment by EvgenySamoylov** [comment]
@31337Ghost Which controllers are implied here?

**Comment by 31337Ghost** [comment]
@EvgenySamoylov I'm feeling unclear about understanding your question.
