### ISSUE TITLE
CPU panel in Node Dashboard display incorrect information

### ISSUE THREAD

**Issue by Ivelok** [deckhouse/deckhouse#2368]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.34.14

### Expected Behavior

Expected panel view:
![Screenshot from 2022-08-31 09-38-00](https://user-images.githubusercontent.com/40290212/187616594-2c23067e-4d4a-4753-a1b3-77f923e1ebae.png)

### Actual Behavior

Actual panel view: 
![Screenshot from 2022-08-31 09-26-10](https://user-images.githubusercontent.com/40290212/187616757-ccee4b21-598c-48b1-b74e-4010138af92b.png)

### Steps To Reproduce

Open "Node" dashboard in Deckhouse Grafana

**Comment by EvgenySamoylov** [comment]
@Ivelok Is it fixed in #2371?
