### ISSUE TITLE
[monitoring][grafana-dashboards] New dashboard definition format — CR rendering

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#240]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Okmeter team [is working](https://flant.slack.com/archives/C020AUATXPF/p1634294281025800) on a new dashboard definition format. It will be more human-friendly than the original grafana JSON. So, we need to prepare for migration.

### Proposed Solution

* Modify CRD grafanadashboarddefinitions.deckhouse.io — add enum-field `format`. Values — "Grafana" (default) and "Okmeter".
* Modify helm_lib _monitoring_grafana_dashboards.tpl:
  * If dashboard file extension is json — render `format` = "Grafana",  If dashboard file extension is yaml — render `format` = "Okmeter".
  * There could be other options for file naming. Maybe we should name files as <dashname>.grafana.json and <dashname>.okmeter.yaml but it is too much for now. Or we could place the files in different folders (grafana-dashboards/grafana/ and grafana-dashboards/okmeter/), If this is caused by helm limitations.

**Comment by nabokihms** [comment]
The feature is not ready yet. ETA ~2 month.
