### ISSUE TITLE
[monitoring][grafana-dashboards] New dashboard definition format — CR implementing

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#241]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Okmeter team [is working](https://flant.slack.com/archives/C020AUATXPF/p1634294281025800) on a new dashboard definition format. It will be more human-friendly than the original grafana JSON. Also, they are working on a conversion tool from the new format to the grafana format. After they finish, we must apply their tool to grafana-dashboard-provisioner and implement a new `format` field in CRD grafanadashboarddefinitions.deckhouse.io (#240).

### Proposed Solution

Add the new tool to the grafana-dashboard-provisioner image and modify the hook to handle the `format` field.

_No response_

**Comment by EvgenySamoylov** [comment]
The feature is not ready yet. ETA ~2 month.

**Comment by nabokihms** [comment]
Okmeter team abandoned it. Closing.
