### ISSUE TITLE
[linstor] Document typical deployment schemes

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#2436]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The most use case of LINSTOR is bare metal. But it's not clear how to deploy LINSTOR in case with virtual machines

### Proposed Solution

Describe typical deployment schemes for using LINSTOR

### Additional Information

Probable problem can be solved by implementing KubeVirt to have an opportunity to spawn virtual machines on bare metal servers
https://github.com/deckhouse/deckhouse/pull/1357

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by apolovov** [comment]
I don't see any prospects.
