### ISSUE TITLE
[node-manager] approvalMode Automatic is broken

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#244]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26

### Expected Behavior

Node groups with `approvalMode: Automatic` do not required annotation `update.node.deckhouse.io/disruption-approved=` on disruptive updates.

### Actual Behavior

Bashible waits for approve
```
Oct 20 16:41:51 static-node-0 bashible.sh[52047]: bb-deckhouse [INFO] Step needs to make some disruptive action. It will continue upon approval:
Oct 20 16:41:51 static-node-0 bashible.sh[52047]: bb-deckhouse [INFO] kubectl annotate node static-node-0 update.node.deckhouse.io/disruption-approved=
Oct 20 16:41:51 static-node-0 bashible.sh[52047]: bb-deckhouse [INFO] Retry in 10sec...
```

**Comment by nabokihms** [comment]
@konstantin-axenov is this still a valid issue?

**Comment by konstantin-axenov** [comment]
> @konstantin-axenov is this still a valid issue?
Needs investigation)

**Comment by konstantin-axenov** [comment]
I think we can close this issue. There were a lot of disruptive node updates during 1.34 release, and `automatic` mode worked as expected.
