### ISSUE TITLE
[extended-monitoring] Fix alerting on certificates

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#2478]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.36

### Expected Behavior

Alerts should clearly denote what happens 

### Actual Behavior

While a certificate secret might have a problem with only it's structure (e.g. missing ca.crt), the alert should not say that the certificate exporter is malfunctioning (`D8CertExporterMalfunctioning`)

**Comment by nabokihms** [comment]
1. ca.crt was not the cause of the error
2. Alert was deleted so it should be fine for now
