### ISSUE TITLE
EKS does not allow issuing client certificates for Kubernetes API access

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2482]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, it is not possible to install Deckhouse on top of EKS. 

The main reason is that EKS does not support issuing certificates signed by Kubernetes CA with the `client auth` capabilities. See https://github.com/aws/containers-roadmap/issues/1604 for more details.

These certificates are utilized in two places:

- [x] 1. `prometheus` - orders a prometheus-api access certificate. This is used for the trickster -> prometheus connection (this will fix #2951). https://github.com/deckhouse/deckhouse/pull/3217
- [x] 2. `prometheus` - orders a scraper certificate. Previously it was used to collect metrics from kube-rbac-proxy protected targets. As of today, the client certificate is only required for the `monitroing-kubernetes-control-plane` module, which will be refactored in the future.
- [x] 3. `user-authn` - orders a certificate for Dex to listen (`server auth` capability instead of `client auth`). According to [EKS docs](https://docs.aws.amazon.com/eks/latest/userguide/cert-signing.html), a particular signer name must be set - `beta.eks.amazonaws.com/app-serving`. https://github.com/deckhouse/deckhouse/pull/3218
- [x] 4. `ingress-nginx` - client certificate authentication is used in configuration snippets to provide access to protected interfaces, e..g, grafana, prometheus, upmeter, etc. Without certificates, the controller pod will remain in the crashloopbackoff state.
- [x] 5. `flant-integration` - with the client certificate, this module collects metrics from prometheus. https://github.com/deckhouse/deckhouse/pull/3216

### Proposed Solution

Go through the list and reduce the number of issued client certificates. For example, for trickster and flant-integration it is possible to migrate to token authentication, which may be a problem for ingress-nginx.

**Comment by gecube** [comment]
Another option - is to use cert-manager for issuing the certificates necessary in deckhouse components inter-communication. It is relatively easy. Also it will be easy to manage these certs. And the certs are much more secure than tokens.

**Comment by EvgenySamoylov** [comment]
Let's remove it from the doc until we will fix that: #2494

**Comment by nabokihms** [comment]
Resolved
