### ISSUE TITLE
[terraform-manager] D8TerraformStateExporterHasErrors never alerts

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#251]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25

### Expected Behavior

If there is a continuous layout error, there must be D8TerraformStateExporterHasErrors alert.

### Actual Behavior

The candi_converge_exporter_errors metric is growing but too slow to trigger the alert.

### Steps To Reproduce

Configure any non-existent peeredVPCs in the AWS layer.

**Comment by name212** [comment]
@nabokihms Perhaps, have you fixed it [here](https://github.com/deckhouse/deckhouse/commit/236e79c41d13597269b32ff127aca55d6757b1ef) yet?

**Comment by nabokihms** [comment]
Yeah, you are right. Should be fixed now.
