### ISSUE TITLE
[monitoring-kubernetes-control-plane] provide a useful dashboard to investigate apiserver abnormal load

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#252]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes we are facing abnormal CPU or Memory usage of Kubernetes api-server and for now, we have no easy way to understand:
- what cluster component generates that load;
- what type of requests are most frequent;
- which resources were requested.

### Proposed Solution

Implement a dashboard. At least request rate and latency implemented in [community apiserver dashboard](https://grafana.com/grafana/dashboards/12006).

**Comment by EvgenySamoylov** [comment]
Fixed in 359715a862acf67c2c3784b958a45b60e5bb4dcc
