### ISSUE TITLE
[global-hooks][deckhouse_registry] confusing values path

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#256]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26

### Expected Behavior

DIscovery global hooks should save their discovered data to global.discovery.

### Actual Behavior

The hook is saving discovered data to `global.modulesImages`, which causes a wrong expectation that I can override it with deckhouse CM.

**Comment by EvgenySamoylov** [comment]
@name212 looks like linked with #330. Could you please look into this?

**Comment by apolovov** [comment]
The issue wasn't about my ability to override values via cm. The issue was about values scheme clarity and transparency to understand. The scheme gives false hope that I can override the value via CM.

**Comment by apolovov** [comment]
The decision:
* move to `discovery`:
```
clusterConfiguration
clusterIsBootstrapped:
deckhouseEdition:
deckhouseVersion:
modulesImages:
```
* move to `modules`:
```
storageClass
```

**Comment by nabokihms** [comment]
This is a technical debt. @EvgenySamoylov let's add this to our future plans.
