### ISSUE TITLE
 Bad sudo password, exiting. TODO handle this correctly.

### ISSUE THREAD

**Issue by mortician2010** [deckhouse/deckhouse#26]
During the bootstrap getting the following error.
 ⛵ ~ Bootstrap: Initial bootstrap
│ ┌ Render bootstrap templates
│ │ From "/deckhouse/candi/bashible/bundles/ubuntu-lts" to "/bootstrap"
│ │ From "/deckhouse/candi/cloud-providers/bashible/bundles/ubuntu-lts" to "/bootstrap"
│ │ Templates directory "/deckhouse/candi/cloud-providers/bashible/bundles/ubuntu-lts" does not exist. Skipping...
│ │ From "/deckhouse/candi/cloud-providers/bashible/common-steps" to "/bootstrap"
│ │ Templates directory "/deckhouse/candi/cloud-providers/bashible/common-steps" does not exist. Skipping...
│ └ Render bootstrap templates (0.00 seconds)
│
│ ┌ bootstrap.sh
│ │ Bad sudo password, exiting. TODO handle this correctly.

Please advise, 
Thank you!

**Comment by nabokihms** [comment]
Hello! This error occurs if the provided sudo password is incorrect. You need to add the flag `-K` to the dhctl bootstrap command to be asked for typing the password.

**Comment by mortician2010** [comment]
Thanks a lot! It works like a charm!
