### ISSUE TITLE
[benchmark-reports] implement a way to run benchmarks in the cluster

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#261]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes we are facing problems related to network and storage cluster subsystems but it is hard to investigate them.

### Proposed Solution

Implement a module and related CRD `benchmark.deckhouse.io` having boolean parameters of particular tests to run, e.g.:
- network throughput;
  > Runs `iperf` servers and clients on particular or new NodeGroup Nodes checking throughput between all of them.
- network latency between control-plane Nodes;
   > To fulfill etcd requirements.
- network latency overall cluster;
- `kubernetes-data` volume i/o capacity;
   > To fulfill etcd requirements.
- ...

All benchmark results can be fitted into the same CRD inside `/status` subresource.

### Additional Information

Except of running that benchmark for problems investigation, it also might be useful to run a benchmark right after cluster installation to be sure that the cluster is fully ready for the production loads and meets general requirements.

**Comment by raabdullaev** [comment]
Implemented in operator-trivy.
