### ISSUE TITLE
[linstor] Only one of controllers serves metrics in HA mode

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2614]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.36

### Expected Behavior

No alerts, no unhealthy targets in prometheus.

### Actual Behavior

Alert D8LinstorControllerHealth fires and errors in kube-rbac-proxy
```
2022/09/29 17:00:09 http: proxy error: dial tcp 127.0.0.1:3370: connect: connection refused
2022/09/29 17:00:21 http: proxy error: dial tcp 127.0.0.1:3370: connect: connection refused
```

### Steps To Reproduce

Just run linstor in ha mode

### Additional Information

![image](https://user-images.githubusercontent.com/14013249/193093786-c067a595-be95-4b64-ba85-04fa7e79381d.png)

**Comment by kvaps** [comment]
Let's teach [k8s-await-election](https://github.com/LINBIT/k8s-await-election) add labels to running pod and use headless service to collect metrics

**Comment by konstantin-axenov** [comment]
D8LinstorControllerTargetDown was removed. But we still have alert TargetDown
![image](https://user-images.githubusercontent.com/14013249/219638853-f2ac7ec6-78f6-440f-bcd6-7962d0cfa013.png)
![image](https://user-images.githubusercontent.com/14013249/219638924-439f3d80-1569-4a1f-a0cc-455365290f4c.png)
