### ISSUE TITLE
Support custom CAs in the image-availability-exporter

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#262]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some custom registries' certificates may be signed by a custom CA.

### Proposed Solution

Consider providing a custom CA to image-availiabity-exporter.

1. We've got a custom `ca` field in the `registry-secret`.
2. We've got to enhance `image-availability-exporter` so that it supports custom CAs

**Comment by nabokihms** [comment]
Connected https://github.com/deckhouse/k8s-image-availability-exporter/issues/45

**Comment by Beastlex** [comment]
There is another feature request to CA in image-availability-exporter from client
