### ISSUE TITLE
Bootstrap does not disable swap on static cluster

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#263]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.26.0

### Expected Behavior

Swap need to disabled.

### Actual Behavior

Swap is not disabled and kublet not stated

**Comment by EvgenySamoylov** [comment]
swap will be returned in k8s 1.23: https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/

**Comment by nabokihms** [comment]
@RomanenkoDenys is this issue still valid? Could you check this?
