### ISSUE TITLE
[bashible] Some system does not include lsb_release binary

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#266]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25.4

### Expected Behavior

Installation without errors on VMs. 

### Actual Behavior

Bashible need binary lsb_release, but some installations can run without it. We have to add lsb_release installation or use other method during distro detection.

### Logs

```shell
Run step 031_install_containerd.sh
│ │ /var/lib/bashible/bundle_steps/031_install_containerd.sh: line 83: lsb_release: command not found
│ │ Failed to execute step /var/lib/bashible/bundle_steps/031_install_containerd.sh ... retry in 10 seconds.
│ └ Run step 031_install_containerd.sh (10.10 seconds) FAILED
```

**Comment by nabokihms** [comment]
Maybe we do not need to use the lsb_release and follow the logic from the bootstrap bundle script.

**Comment by EvgenySamoylov** [comment]
Done at 48d957720154093c219151ad096d0c0abc4f04f8
