### ISSUE TITLE
Update CSI components to the latest version, consider implementing dependency update tracking

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#267]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We are trailing behind CSI releases for at least a year. There were some important bug fixes in all of them.

### Proposed Solution

Consider implementing update tracking for all external components.

**Comment by EvgenySamoylov** [comment]
It has been updated already.
