### ISSUE TITLE
[istio] let users configure sidecar resources

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2674]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some dev clusters users don't need CPU resource management. So, they don't need requests.

### Proposed Solution

Add  a`sidecar.resourcesManagement` parameter.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by EvgenySamoylov** [comment]
@apolovov Are there any applications that don't use CPU at all? I mean, it consumes resources, doesn't it? Could you please explain it more and maybe propose some additional solutions.

**Comment by apolovov** [comment]
It is not widely required, there was a single request during conversation with a collegue.
