### ISSUE TITLE
Need to update cluster in the exact day of the month

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#2693]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some clients ask us if they are able to update clusters say on the last Friday of the month.

### Proposed Solution

Probably we need to consider giving more options in the update windows configuring.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by EvgenySamoylov** [comment]
Current workaround is to change updating mode from Auto to Manual (updating windows are turned off in that case) and then back to Auto (updating windows are turned back on).
