### ISSUE TITLE
Failed to stop kubelet.service: Unit kubelet.service not loaded.

### ISSUE THREAD

**Issue by mortician2010** [deckhouse/deckhouse#27]
Yet another issue found during the bootstrap:
 Run step 031_install_containerd.sh, retry attempt #1 of 10
│ │ Failed to stop kubelet.service: Unit kubelet.service not loaded.
│ │ Failed to execute step /var/lib/bashible/bundle_steps/031_install_containerd.sh ... retry in 10 seconds.

**Comment by nabokihms** [comment]
It looks like there is a kubelet installed on a node, but dhctl only installs it on the 34th step. Could you ensure that you are installing Deckhouse on a clean node?

**Comment by mortician2010** [comment]
I am just referring to this resource:
https://deckhouse.io/ru/gs/
thus I've tried several times doing a clean installation.

**Comment by nabokihms** [comment]
Ok, we need to investigate it then. Could you show the config you used to run the cluster bootstrap (without sensitive data)? We will try to reproduce the problem.

**Comment by mortician2010** [comment]
yes, sure.

apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "1.19"
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  releaseChannel: Stable
  configOverrides:
    global:
      modules:
        publicDomainTemplate: "%s.test.local"
    cniFlannelEnabled: true
    cniFlannel:
      podNetworkMode: VXLAN
---
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- 192.168.60.0/24

**Comment by mortician2010** [comment]
yes, sure. 
config.yml:

apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Static
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: "1.19"
clusterDomain: "cluster.local"
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  releaseChannel: Stable
  configOverrides:
    global:
      modules:
        publicDomainTemplate: "%s.test.local"
    cniFlannelEnabled: true
    cniFlannel:
      podNetworkMode: VXLAN
apiVersion: deckhouse.io/v1
kind: StaticClusterConfiguration
internalNetworkCIDRs:
- 10.0.4.0/24

**Comment by Nariman747** [comment]
@mortician2010 
You are need delete **containerd** on your system.
If your OS is Centos 7 enter this command:
yum remove containerd.io -y

**Comment by yalosev** [comment]
@mortician2010 what OS do you use?

**Comment by mortician2010** [comment]
I'll try and let you know, thanks!
@yalosev Host OS is Debian

**Comment by yalosev** [comment]
Debian OS is not supported yet. (You can vote for [this](https://github.com/deckhouse/deckhouse/issues/17) issue). Maybe it could work but not guaranteed

Try to use Ubuntu 16.04/18.04/20.04 or CentOS 7

**Comment by konstantin-axenov** [comment]
Debian support feature will be implemented in https://github.com/deckhouse/deckhouse/pull/546
