### ISSUE TITLE
OpenVPN module not have option for "redirect-gateway"

### ISSUE THREAD

**Issue by ABess-Flant** [deckhouse/deckhouse#2700]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.36.9

### Expected Behavior

Can handle option "redirect-gateway" through deckhouse configmap

### Actual Behavior

redirect-gateway option cant be included in configmap

**Comment by EvgenySamoylov** [comment]
Was realized in #3178
