### ISSUE TITLE
Remove the old nginx-ingress module from the codebase

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#274]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The [nginx-ingress](https://github.com/deckhouse/deckhouse/tree/main/ee/fe/modules/400-nginx-ingress) module is deprecated and was replaced by the new [ingress-nginx](https://github.com/deckhouse/deckhouse/tree/main/modules/402-ingress-nginx).

### Proposed Solution

Remove the [nginx-ingress](https://github.com/deckhouse/deckhouse/tree/main/ee/fe/modules/400-nginx-ingress) module and all its mentions from the code.

**Comment by nabokihms** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/96e2161db4b742d8d90144db1d1997d2bc0cae27
