### ISSUE TITLE
[ingress-nginx] Increase validation timeout up to 30s

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2754]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Multiple reports of failing releases were received after 1.36 release.
```
Error: helm upgrade have failed: UPGRADE FAILED: error processing rollout phase stage: error applying resources: Internal error occurred: failed calling webhook "public.validate.d8-ingress-nginx": Post "[https://public-admission.d8-ingress-nginx.svc:443/networking/v1/ingresses?timeout=15s](https://public-admission.d8-ingress-nginx.svc/networking/v1/ingresses?timeout=15s)": context deadline exceeded
```
It happens because previous default ingress controller in Deckhouse had validation disabled. But now ingress controller 1.1 is default and validation is enabled.

### Proposed Solution

Increase timeout.

**Comment by EvgenySamoylov** [comment]
Lets set timeout to 30s.

**Comment by nabokihms** [comment]
Closed by https://github.com/deckhouse/deckhouse/pull/2812
