### ISSUE TITLE
[node-manager] Require cloudInstances section for CloudEphemeral nodes in NodeGroup

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#276]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.25.5

### Expected Behavior

Inability to deploy NodeGroup without the cloudInstances section

### Actual Behavior

It is allowed to deploy a NodeGroup without the cloudInstances section, as a result of which all nodes of this NodeGroup are deleted.

**Comment by EvgenySamoylov** [comment]
Resolved in f8b52d2b58193991ad4669c009450c222deb10fb
