### ISSUE TITLE
[ingress-nginx] backport redirectScheme fix to 1.1

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2760]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a bug when using `behindL7Proxy` controller and a load balancer without X-Forwarded-Proto header, redirects don't work. They redirect to `nil://example.com/abc`.
The [fix](https://github.com/kubernetes/ingress-nginx/pull/8468) is in ingress-nginx >= 1.2.

### Proposed Solution

Update the controller.

### Additional Information

How to reproduce:

curl -H 'X-Forwarded-Proto: https' -H 'Host: example.com' https://1.2.3.4 -k
nice redirect to https://www.example.com

curl -H 'Host: example.com' https://1.2.3.4 -k
bad redirect to nil://www.example.com

**Comment by EvgenySamoylov** [comment]
Let's patch our 1.1 ingress-nginx with this tweak instead of updating it to 1.2+
