### ISSUE TITLE
[istio] Multitenancy in kiali dashboard

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2765]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Current strategy is anonymous. This is not what users expect.

### Proposed Solution

Kiali supports multitenancy for openshift probably it's possible to use the same logic.

**Comment by apolovov** [comment]
Solved in https://github.com/deckhouse/deckhouse/pull/8830.
