### ISSUE TITLE
[linstor] drbd kernel-module-injector not working with SELinux

### ISSUE THREAD

**Issue by kvaps** [deckhouse/deckhouse#2775]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.36

### Expected Behavior

drbd kernel-module-injector can't able to build and inject DRBD module into kernel

### Actual Behavior

- drbd kernel-module-injector can't inject module with SELinux enabled

### Steps To Reproduce

Enable linstor module, check linstor-node logs

### Additional Information

OS: RedOS

### Logs

```
        Module build was successful.
=======================================================================
  With DRBD module version 8.4.5, we split out the management tools
  into their own repository at https://github.com/LINBIT/drbd-utils
  (tarball at http://links.linbit.com/drbd-download)

  That started out as "drbd-utils version 8.9.0",
  has a different release cycle,
  and provides compatible drbdadm, drbdsetup and drbdmeta tools
  for DRBD module versions 8.3, 8.4 and 9.

  Again: to manage DRBD 9 kernel modules and above,
  you want drbd-utils >= 9.3 from above url.
=======================================================================
insmod: ERROR: could not insert module ./drbd.ko: Permission denied
insmod: ERROR: could not insert module ./drbd_transport_tcp.ko: Permission denied

Could not load DRBD kernel modules
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
