### ISSUE TITLE
Add script to automate `git bisect run` to track down commit that intcreased arbitrary command execution time

### ISSUE THREAD

**Issue by gmaiorov** [deckhouse/deckhouse#2791]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

While working on #2787 I've used `git bisect run` to track down a commit that lead to increase of matrix test duration.
It seems to be useful to automate such task for generic use.

### Proposed Solution

Create script that automates `git bisect run` and add it to `deckhouse-internal`.
Syntax could  be like:
```
bisect-time.sh \
    --good <ref> \
    --bad <ref> \
   (--limit-seconds <seconds> | --limit-minutes <minutes> | --limit-hours <hours>) \
   [--silent \]
    <cmd> <cmd_args>
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment]
It should be implemented when needed. Closing for now.
