### ISSUE TITLE
Distroless container  images

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#2797]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If we don't need the debugging tools in the binary go container, consider using a basic scratch image.
The scratch-based container image is simpler, lighter, and contains no potential security holes.

### Proposed Solution

Change the base image of the container from alpine to scratch if the container contains only one binary go.

**Comment by nabokihms** [comment]
NIT: other dependencies, like ca-certificates, may be required for a binary to work. That is why it may be better to base builds on something like https://github.com/GoogleContainerTools/distroless

**Comment by EvgenySamoylov** [comment]
PR is #3963

**Comment by konstantin-axenov** [comment]
https://github.com/deckhouse/deckhouse/issues/4663
https://github.com/deckhouse/deckhouse/issues/4628
