### ISSUE TITLE
[prometheus] --query.max-samples customization

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2846]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For lots of metrics, aggregated dashboards like the `Namespaces` dashboard stop showing data.

### Proposed Solution

There should be an ability to customize --query.max-samples arg.
Or we should hardcode some large values:
```
  query:
    maxSamples: 100000000
```

(default is 50000000).

### Additional Information

Original author - @apolovov

**Comment by EvgenySamoylov** [comment]
It was realized in #3124
