### ISSUE TITLE
vSphere e2e tests fail on k8s 1.21 and containerd

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#2880]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.38

### Expected Behavior

The tests should pass on daily basis

### Actual Behavior

The tests fail while bootstrapping system node from resources.yaml

- https://github.com/deckhouse/deckhouse/actions/runs/3320859780/jobs/5506053678
- https://github.com/deckhouse/deckhouse/actions/runs/3310124264/jobs/5463992138
- https://github.com/deckhouse/deckhouse/actions/runs/3318254781/jobs/5485232432
- https://github.com/deckhouse/deckhouse/actions/runs/3326114715/jobs/5499517826

**Comment by nabokihms** [comment]
Fixed by @konstantin-axenov. There was a problem with our vSphere setup.
