### ISSUE TITLE
[cloud-provider-yandex] Perform fsck before mount

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#2887]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.38.4

### Expected Behavior

Disk is always mounted without issues.

### Actual Behavior

If there is a filesystem corruption, it won't mount. It'll require manual action.

### Additional Information

Almost all other CSI providers already do this.

**Comment by duckhawk** [comment]
https://github.com/deckhouse/yandex-csi-driver/pull/12
