### ISSUE TITLE
Consider running kubernetes-api-proxy as a static pod

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#29]
We deploy the proxy on each node. This proxy is an instance of nginx directed to the masters internal addresses. It allows to balance requests between all master nodes.

We should consider delivering it as a static pod instead of creating a systemd unit. It looks like a more simple and transparent way.

**Comment by 31337Ghost** [comment]
We might want to implement this together with the issue https://github.com/deckhouse/deckhouse/issues/144.

**Comment by nabokihms** [comment]
We decided to stay with a systemd-unit implementation.
