### ISSUE TITLE
[cni-cilium] Disable rp_filter in cilium agent pods

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#2900]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Bashible disables `rp_filter` on all nodes to be able to run cilium.
https://github.com/deckhouse/deckhouse/blob/b250b7e6a27d7e630986b403808e06b14f2b2729/candi/bashible/common-steps/node-group/041_configure_sysctl_tuner.sh.tpl#L81

### Proposed Solution

Cilium cannot run on nodes without bashible. If bashible stops working or cannot adjust rp_filter, a network on a node will not work. This is a dependency, and we can avoid it by moving tunning rp_filter to the daemonset init container.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment]
This is a nice-to-have issue, but the team has no capacity to do it at the current time.
