### ISSUE TITLE
[node-manager] sync the Node time during bootstrap

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#2949]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is possible to join a Node with unsynchronized time, which leads to weird errors in the cluster. i.e. OIDC-tokens suddenly stop working.

### Proposed Solution

To run ntp-date from bootstrap.sh

**Comment by konstantin-axenov** [comment]
Seems that we encountered problem of `makesptep` for the first time. We need to tune this parameter.
https://github.com/deckhouse/deckhouse/blob/main/modules/470-chrony/images/chrony/start.sh#L37
```
makestep 1.0 3
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by RomanenkoDenys** [comment]
We need to have own ntp server in cluster. To do it we need to add allow directive to the chrony config to allow nodeNetworkCIDR hosts connect to chrony and add master node ip addresses as ntp servers. Also chrony pod should work on any uninitialized node.
