### ISSUE TITLE
[ingress-nginx] Deckhouse get stuck if ingress controller exists without available replicas

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#2950]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.39

### Expected Behavior

We discussed that this is misconfiguration of Deckhouse. But maybe we can do something to prevent such problem.

### Actual Behavior

Deckhouse get stuck on release update

### Steps To Reproduce

1. Create ingress controller with bad node-selector and enabled validation.
2. Wait while validation webhook is updated
3. Ingress resources can't be upgraded

**Comment by EvgenySamoylov** [comment]
Lets use `failurePolicy: Ignore`

**Comment by apolovov** [comment]
My proposal:
* failurePolicy: Ignore if there is label `heritage: deckhouse`
* failurePolicy: Fail for others
