### ISSUE TITLE
[log-shipper] connective graylog + log-shipper through logstash

### ISSUE THREAD

**Issue by ruslangizatulin-flant** [deckhouse/deckhouse#297]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to use graylog in conjunction with log-shipper

### Proposed Solution

There is an issue in vector community  https://github.com/vectordotdev/vector/issues/4868

**Comment by gyrter** [comment]
I think we should add 2 new sinks to log-shipper - graylog and vector.
