### ISSUE TITLE
[getting started] Add config validation

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#298]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have a lot of questions about publicDomainTemplate. Users missing *%s* in this setting.

### Proposed Solution

Add validation to config generator. Or remove *%s* from this setting and rename it to  publicDomainSuffix

**Comment by z9r5** [comment]
[Done](https://github.com/deckhouse/deckhouse/commit/8af4fa2512e77ad581770217a3e4533336766180)
