### ISSUE TITLE
Alert about services of loadbalancer type in pending state

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#2981]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Now we have no alerts about services of loadbalancer type stucked in a pending state. This can become a problem, for example, in case when no addresses left in metallb pool.

### Proposed Solution

Add metrics about services state in one of existing exporters (there is no suitable metrics now), and create CustomPrometheusRule for this case.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment]
We still, need this, and it seems like a good first issue.
