### ISSUE TITLE
[grafana][dashboard-provisioner] Check that all dashbords have unique UID.

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#2994]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If two dashbords have one UID we have an error "Dashboard not found" and dashbord does not show in the list.

### Proposed Solution

In dashboard provisioner for each dashboard check UID and if it be in the list will show an error.

**Comment by yalosev** [comment]
https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/images/grafana-dashboard-provisioner/hooks/dashboard_provisioner.sh

**Comment by yalosev** [comment]
Set `.metadata.name` to `.uid` field with jq
