### ISSUE TITLE
Cluster operators (prometheus-operator) should not conflict with user-deployed operators

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#30]
For example, it is not possible to deploy the second prometheus-operator in addition to the one managed by the deckhouse.

Each deployed operator should either be:

1. Fully configurable
2. Scoped to deckhouse-managed resources

**Comment by konstantin-axenov** [comment]
It is resolved by [commit](https://github.com/deckhouse/deckhouse/commit/539d3400156b5318ee4dc1f1765ba888e989b28e). Released in [v1.24.14](https://github.com/deckhouse/deckhouse/releases/tag/v1.24.14).
