### ISSUE TITLE
[node-manager] Configure node resource eviction policy

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3034]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is a possibility to configure pods eviction based on resources. It seems that [defaults](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#hard-eviction-thresholds) are not sufficient for all workloads and can be adjusted. In addition, consider changing the status update frequency.

(Maybe it can also be good to figure out how kubelet tracks node resources).

### Proposed Solution

It can works well with the early-oom kill or even substitute it at some point.

**Comment by EvgenySamoylov** [comment]
Closed in favor of #2874.
