### ISSUE TITLE
[cni-cilium] hostPort works unpredictably

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#3035]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.39.2

### Expected Behavior

Pod's `hostPort` IP is not used by Cilium. Instead, it uses local internal host IP, which it deduces manually. This differs from CNI project's portmap implementation, and leads to issues with hostPort on non-standard networking stacks. Those that include multiple IPs or have an ephemeral IP (such as OpenStack's Floating IP).

### Actual Behavior

We hit the issues described here: https://github.com/cilium/cilium/issues/12116

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
