### ISSUE TITLE
[chrony] Filter out of cluster nodes in NTPDaemonOnNodeDoesNotSynchronizeTime alert

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#3041]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some client have exporter that export metrics from external nodes which do not have in the cluster.
We cannot manage this nodes but we have alert NTPDaemonOnNodeDoesNotSynchronizeTime.

### Proposed Solution

`(min by(node) (node_timex_sync_status{job="node-exporter"})) == 0`

**Comment by alexey-gavrilov-flant** [comment]
`(min by(node) (node_timex_sync_status{job="node-exporter"})) == 0`
