### ISSUE TITLE
[cloud-provider-aws] Destroy cluster was failed with error

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#3048]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.40

### Expected Behavior

Cluster should destroy without error.

### Actual Behavior

Some times destroy was failed with error:
```
destroing of node 3467244482-1-con-1-21-aw-master-0 failed: 1 error occurred:
	* 
Error: deleting EBS Volume (vol-0ef82bf89f8c51376): VolumeInUse: Volume vol-0ef82bf89f8c51376 is currently attached to i-0713f87e81617cce7
	status code: 400, request id: 5350c2bd-6f69-400f-b5c0-7866f71ce57e
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
