### ISSUE TITLE
[control-plane-manager] Add authentication webhook support

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#305]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is reasonable to abstain from using OIDC provider and allow straight token projection, especially if the users already use this solution in their non-deckhouse installations.

### Proposed Solution

We can set an authorization webhook for the kube-apiserver. Consider adding options to enable the authentication webhook.

**Comment by EvgenySamoylov** [comment]
Fixed by da57fef8e36adbeb726991c9b201f69d132fe5a6
