### ISSUE TITLE
[secrets-store] New module

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3053]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Kubernetes secrets aren't safe enough. It is easy to leak secrets by mistake, especially in large enterprise systems where all secrets should be delivered through one hole to many Kubernetes clusters.

Additional issues:
* Secret data is stored in etcd. By default, etcd data is not encrypted, and neither are your secrets. You should enable encryption at rest, limit access to etcd to admin users only, and safely dispose of disks where etcd data was formerly stored.
* Anyone with root access on any node can read any secret, because they can impersonate the kubelet. Kubernetes does not send secrets on a “need to know” basis; it exposes secrets to anyone on any node with root access.
* Any user who creates a pod that uses a secret has access to that secret, even if the API Server policy does not allow the user to view the secret.

There are external secret management solutions that fall into two broad categories:

* Cloud provider tools - including [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/), [Google Cloud Platform KMS](https://cloud.google.com/kms/), and [Azure Key Vault](https://azure.microsoft.com/en-in/services/key-vault/) - help encrypt secrets within each cloud environment, automatically rotate secret values, manage access to secrets with policies, and perform central auditing of secrets.
* Open source tools - [Hashicorp Vault](https://www.vaultproject.io/) provides secrets management and data protection, with advanced features like dynamic secrets, namespaces, leases, and revocation for secrets data.

### Proposed Solution

Develop a new module to be able to substitute standard secrets mechanics with something more suitable:

- Hashicorp Vault - as was mentioned above, the most popular and robust open-source solution to store secrets. We need to think about how to deploy it properly with Deckhouse.
- Secrets Store CSI driver that can mount secrets into pods and use Hashicorp vault as the backend. See the following link for more details - https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html It will help users to get a much better experience with vault and Kubernetes out of the box.

### Additional Information

https://blog.aquasec.com/managing-kubernetes-secrets

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment]
Another great option is to use the [external secrets operator](https://external-secrets.io/) to sync secrets to cluster secrets and rotate them. It stores data in Kubernetes secrets, which can be not as secure as desired but easier to operate than with the secret-storage-csi
