### ISSUE TITLE
[cloud-provider-openstack] Add ConfigDrive support to instance class

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3060]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some providers might not have metadata server enabled.

### Proposed Solution

Add ConfigDrive to OpenstackInstanceClass. It's supported in [mcm](https://github.com/deckhouse/mcm/blob/master/pkg/driver/driver_openstack.go#L126).

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
