### ISSUE TITLE
[flant-integration] export metrics about Istio module

### ISSUE THREAD

**Issue by 31337Ghost** [deckhouse/deckhouse#307]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We'd like to get a statistic of Istio usage in clusters.

### Proposed Solution

Export metrics representing:
- module enablement
- namespaces count, where Istio is enabled
- RPS of the traffic:
   - ingress/egress (external to cluster)
   - internal (in-cluster between services)
   - federation (between Kubernetes clusters)
   - alliance

**Comment by nabokihms** [comment]
Done
