### ISSUE TITLE
[dhctl] Error on step 31 while install on CentOS Stream 9

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3087]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.39.2

### Expected Behavior

No problems during installation

### Actual Behavior

While installing version:
[CentOS-Stream-9-20221118.0-x86_64-dvd1.iso](http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-20221118.0-x86_64-dvd1.iso)

There is permanent error on step 31:
```
│ ┌ Run step 031_install_containerd.sh, retry attempt #1 of 10
│ │ bb-rp [INFO] Installing package 'containerd-io'
│ │ warning: containerd.io.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
│ │ 	package container-selinux-3:2.191.0-1.el9.noarch (which is newer than container-selinux-3:2.189.0-1.el9.noarch) is already installed
│ │ Failed to execute step /var/lib/bashible/bundle_steps/031_install_containerd.sh ... retry in 10 seconds.
│ └ Run step 031_install_containerd.sh, retry attempt #1 of 10 (51.25 seconds) FAILED
```
Packet downgrade resolves problem

**Comment by EvgenySamoylov** [comment]
Fixed in #3863
