### ISSUE TITLE
Add proxy support for cloud providers

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3090]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have proxy support in cloud provider for Yandex, but not for others.

### Proposed Solution

Add proxy support for cloud providers:
- AWS
- Azure
- GCP
- OpenStack
- Vsphere

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/pull/10676
