### ISSUE TITLE
[pod-reloader] Add ability to react on the creation of a configmap

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#3091]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Module pod-reloader provides the ability to reload pods when related ConfigMaps or Secrets change. 

In some cases the configuration changes with resource re-creation, i.e. Delete/Add in Kubernetes API event instead of Modify. These cases can be caused by Helm hooks used by third-party Helm charts.

Under the hood, pod-reloader uses stakater/Reloader v0.0.11 which does not support Add events.

### Proposed Solution

- Upgrade the dependency of [stakater/Reloader](https://github.com/stakater/Reloader) to the latest version
- Use flag [`--reload-on-create`](https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/templates/deployment.yaml#L186)

### Additional Information

To reproduce the issue and to verify it has been fixed, one can use Helm Chart with configmap generated by `pre-upgrade` Helm hook, and annotated with `pod-reloader.deckhouse.io/match: "true"`

**Comment by EvgenySamoylov** [comment]
PR is #3096
