### ISSUE TITLE
[cni-cilium] Getting started for BareMetal installations

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3145]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The BareMetal installation section of the Getting Started guide contains an example of InitialClusterConfiguration with the cni-flannel module enabled.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/32434187/204379154-4c70ffda-c158-40d1-99dc-bc402f6c5e9e.png">

### Proposed Solution

Since cilium is going to be the primary cni for Deckhouse, consider changing getting started instructions accordingly.

**Comment by z9r5** [comment]
Done in #5093
