### ISSUE TITLE
[Upmeter] Fix agent memory leak

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#315]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26

### Expected Behavior

Agent should have constant memory consumption level

### Actual Behavior

Agent has a leak. The leak can be easily seen the in grafana dashboard.

**Comment by EvgenySamoylov** [comment]
Resolved in 31f28bb4d30f5d0e01f281dfdd2770cceed60040
