### ISSUE TITLE
[descheduler] Flexible tuning of pods filters

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#316]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes a node in the cluster is dedicated for one pod, and it almost totally requires all memory and CPU capacity. And this pod can be evicted by LowNodeUtilization policy. We need to give ability for smart filtering of such pods.

### Proposed Solution

Implement one of the [pod filters](https://github.com/kubernetes-sigs/descheduler#filter-pods) that are available in descheduler.

**Comment by EvgenySamoylov** [comment]
It was discussed with the DevOps teams internally. It's considered a quite important issue because of the high descheduler's money-saving potential in the clouds.

**Comment by EvgenySamoylov** [comment]
Closed in favor of: #1382
