### ISSUE TITLE
[monitoring] Remove obsolete grafana storage

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3177]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.40

### Expected Behavior

Pvc for grafana storage exists in old clusters. It's left after migration to stateless grafana.

### Actual Behavior

Pvc exists
```
kubectl -n d8-monitoring get pvc grafana-storage-grafana-0
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
grafana-storage-grafana-0   Bound    pvc-0687dafe-afcf-48e7-b1ac-27e782fe44c0   2Gi        RWO            network-hdd    2y270d
```

**Comment by z9r5** [comment]
Done
