### ISSUE TITLE
[vertical-pod-autoscaler] request to update version

### ISSUE THREAD

**Issue by devbrom** [deckhouse/deckhouse#3214]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

I have situation when some operator creates several deployments with 1 replicas (by each deployment) and one common PDB. In this case VPA can't update pods because we have only one replica by each controller.

I have made small research and discovered that in the next VPA version 0.10.0 (currently in deckhouse we have 0.9.2) that case has been covered. In the next version we can overwrite minimal replicas (which is set as argument in VPA updater launch command) by the value in each VPA resources.

### Proposed Solution

update VPA version

### Additional Information

https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler/enhancements/4566-min-replicas
https://github.com/kubernetes/autoscaler/releases/tag/vertical-pod-autoscaler-0.10.0

If you have piece of advice how can I update VPA version in my cluster, before that will be released it would be useful for me. Thanks.

**Comment by EvgenySamoylov** [comment]
It's already in progress here: #3224

Thanks for that!
