### ISSUE TITLE
[ingress-nginx] Allow changing "log_format"

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#322]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

A user might wish to export some variables that are not currently present in built-in log_format.the 

### Proposed Solution

Allow configuring log format via `IngressNginxController` CR.

**Comment by nabokihms** [comment]
As I see it, we do not need to allow changing the format completely, but only allow adding more fields to existing JSON e.g., by providing a map of keys and values including Nginx variables.

**Comment by nabokihms** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/72cd9034390d8c60898787bb57edb22a40bf0d57
