### ISSUE TITLE
[prometheus] Does not use new certificates from prometheus-scraper-tls without restarting the pod

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#324]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.26

### Expected Behavior

After renewing the certificates (prometheus-scraper-tls), the new ones should be used

### Actual Behavior

Prometheus does not load updated certificates and continues to use old ones

### Logs

```shell
W1125 05:36:55.854985       1 x509.go:133] GET /metrics: [Prometheus/2.28.0 10.3.0.24:51498]: certificate expires in one week. Issuer: CN=kubernetes, Subject: CN=d8-monitoring:scraper, NotBefore: 2020-12-01 00:59:00 +0000 UTC, NotAfter: 2021-12-01 00:59:00 +0000 UTC
```

**Comment by EvgenySamoylov** [comment]
Fixed at 6bf656d9dc84bb01e188268e3c6210d98a217523
