### ISSUE TITLE
[docs] Advanced monitoring mode note has no links

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#3242]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main

### Expected Behavior

This note should have link to extended-monitoring module page.

### Actual Behavior

https://deckhouse.io/documentation/v1/modules/300-prometheus/#advanced-monitoring-mode

It says "Deckhouse also provides the advanced monitoring mode" without links to further reading.

### Additional Information

I think it should contain link to https://deckhouse.io/documentation/v1/modules/340-extended-monitoring/

**Comment by z9r5** [comment]
Ref: #3242
