### ISSUE TITLE
Namespace deletion stuck, bashible.deckhouse.io/v1alpha1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by andlf** [deckhouse/deckhouse#3246]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.40.3

### Expected Behavior

Namespace deleted.

### Actual Behavior

Namespace deletion stuck. Clearing finalizers does not help. 
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Tue, 06 Dec 2022 10:23:44 +0300  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: bashible.deckhouse.io/v1alpha1: the server is currently unable to handle the request

### Steps To Reproduce

Delete namespace.

### Additional Information

Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Tue, 06 Dec 2022 10:23:44 +0300  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: bashible.deckhouse.io/v1alpha1: the server is currently unable to handle the request

**Comment by EvgenySamoylov** [comment]
Probably there was some issue with bashible API server. Need to check logs in the d8-cloud-instance-manager namespace.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
