### ISSUE TITLE
[dhctl] image updated to v* tag after bootstrap ends

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#3251]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main

### Expected Behavior

I assume that deckhouse is ready after issueing this command:

```
dhctl bootstrap-phase install-deckhouse --kubeconfig=/kubeconfig --config=/config.yml
```
(It is from the [Getting started for kind](https://deckhouse.io/gs/kind/step4.html))

### Actual Behavior

`dhctl` says deckhouse is ready:

```
...

│ │ │ Deckhouse pod found: deckhouse-fb74f4595-lvsf8 (Running)
│ │ │ Running pod found! Checking logs...
│ │ │ 	Module "operator-prometheus-crd" run successfully
│ │ │ 	Module "prometheus" run successfully
│ │ │ 	Module "ingress-nginx" run successfully
│ │ │ No more converge tasks found in Deckhouse queue.
│ │ │ Deckhouse pod is Ready!
│ │ └ Waiting for Deckhouse to become Ready (108.88 seconds)
│ └ ⛵ ~ Bootstrap: Install Deckhouse (109.08 seconds)
└ ⛵ ~ Bootstrap: Install Deckhouse (109.18 seconds)
```

But it is not ready:

```
kubectl -n d8-system get po
NAME                                        READY   STATUS    RESTARTS       AGE
deckhouse-5b997f9d64-qkfnx                  0/1     Running   0              70s
```

It updates image from `ce:stable` to `ce:v1.40.3` (`ce:alpha -> ce:v1.41.1`) and starts pulling:

  Normal   Pulling    3m12s             kubelet            Pulling image "registry.deckhouse.io/deckhouse/ce:v1.40.3"
  Normal   Pulled     20s               kubelet            Successfully pulled image "registry.deckhouse.io/deckhouse/ce:v1.40.3" in 2m51.6355445s

### Steps To Reproduce

1. Install deckhouse in kind: https://deckhouse.io/gs/kind/step4.html
2. Run dhctl bootstrap-phase install-deckhouse
3. See message "Deckhouse pod is Ready!"
4. Create ingress controller `kubectl create -f ingress-nginx-controller.yml`
5. Be confused by the error:
```
error: unable to recognize "ingress-controller.yml": no matches for kind "IngressNginxController" in version "deckhouse.io/v1"
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by nabokihms** [comment]
We discussed it earlier with @RomanenkoDenys and @name212. 
The current plant is that dhctl can only bootstrap a specific version of the Deckhouse. As of today, dhctl deploys and image with release channel tag, e.g., alpha, beta, early-access.

**Comment by yuriygoryaev** [comment]
relates to #[5073](https://github.com/deckhouse/deckhouse/issues/5073)
