### ISSUE TITLE
[deckhouse] Always set working directory for hooks to the module directory

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3262]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Always use a relative path to access module files. 

### Proposed Solution

Consider the most strict variant - chroot. It is the safest option to prevent hooks from working with the filesystem, yet it affects symlinks and cannot be used blindly for all modules from our current setup.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/issues/10306
