### ISSUE TITLE
[cni-cilium] Deckhouse host-network ciliumClusterWideNetworkPolicies.

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#3286]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Cilium have 3 types of policies:
1. CiliumNetworkPolicy (Namespaced).
2. CiliumClusterWideNetworkPolicy (cluster wide).
3. CiliumClusterWideNetworkPolicy in HostNetwork mode.

Policies 1 and 2 for users use.

CiliumClusterWideNetworkPolicy in HostNetwork mode makes it possible to implement host firewall, which is usable in the case of baremetal install, or installation in the clouds without support of security groups.
But if the applied policy contains errors, we can lose access to the cluster.

To prevent possible errors, we should add the ability to easily configure a limited set of predefined security policies. 

### Proposed Solution

First vision of design.
We need 3 predefined host security policies:
1. No policy.
2. Policy with acceess to limited set ports on nodes (ssh, nodeport range, kubernetes api, ingress ports).
3. Same as the 2, but with whitelists.

**Comment by konstantin-axenov** [comment]
Still valid issue.

**Comment by apolovov** [comment]
There is newer issue https://github.com/deckhouse/deckhouse/issues/4591.
