### ISSUE TITLE
[prometheus] Customize interfaces on Grafana home page

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3289]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Users want to use Grafana as a developer/administrator portal and provide all necessary links.

### Proposed Solution

There is a hook in charge of collecting annotations from ingresses. Consider giving users the ability to set annotations on their own ingress resources.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Grafana seems to be not the best solution for this case. We have Deckhouse UI, and it should have such option for customization.
