### ISSUE TITLE
Disable GetCapacity in OpenStack CSI

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3295]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.40.3

### Expected Behavior

No error in CSI controller logs.

### Actual Behavior

```
root@dev-master-0:~# kubectl -n d8-cloud-provider-openstack logs csi-controller-7dfc5d856f-fwtbn controller
E1209 16:52:20.231399       1 utils.go:85] GRPC error: rpc error: code = Unimplemented desc = GetCapacity is not yet implemented
E1209 16:52:20.235031       1 utils.go:85] GRPC error: rpc error: code = Unimplemented desc = GetCapacity is not yet implemented
```

### Steps To Reproduce

It is usual behavior cluster in OpenStack with identity 3.14.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
It's not implemented in CSI Driver.
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L560
