### ISSUE TITLE
[prometheus] VPA min can be greater max

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3308]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.41.0

### Expected Behavior

Min allowed values for VPA are hardcoded in the helm templates. Max allowed values are calculated according to the number of pods in the cluster. 

If max allowed values are lower than min allowed, consider making them even.

### Actual Behavior

```
minAllowed:
  cpu: 50m
  memory: 500Mi
maxAllowed:
  cpu: "386m"
  memory: "290Mi"
  ```

```
ModuleRun failed in phase 'CanRunHelm'. Requeue task to retry after delay. Failed count is 26. Error: helm upgrade failed: cannot patch "prometheus-longterm" with kind VerticalPodAutoscaler: admission webhook "vpa.k8s.io" denied the request: max resource for memory is lower than min && cannot patch "prometheus-main" with kind VerticalPodAutoscaler: admission webhook "vpa.k8s.io" denied the request: max resource for memory is lower than min
```

### Steps To Reproduce

1. Deploy cluster (probably deploy deckhouse to the cluster with few pods).
2. Enable prometheus module.

**Comment by yalosev** [comment]
```
{{- define "prometheus_resources" }}
cpu: 200m
memory: 1000Mi
{{- end }}
```
hardcode this values into detect_vpa_max

like this:
```go
var (
	minMem = resource.NewQuantity(1000, resource.BinarySI)
)

	if maxMem < minMem {
		maxMem = minMem
	}
```
