### ISSUE TITLE
[deckhouse] Restore information about skipped releases

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3313]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If Deckhouse was disabled or didn't have internet access to registry for some time, there is information about latest Deckhouse releases. And user have to create DeckhouseRelease objects manually for skipped releases. It increases the possibility of error.

### Proposed Solution

We have to keep information about release in registry. The easiest way is to tag channel meta image with minor release version and always store it in registry. When Deckhouse finally has access to the registry, it downloads the latest release and can restore information about previously skipped releases.

It's also important to modify [pull and push](https://github.com/deckhouse/deckhouse/tree/main/tools/release) scripts for delivery using usb stick.

**Comment by nabokihms** [comment]
Think about how it will work in air-gapped environment and in cases when Deckhouse was manually updated by changing the image (provide some kind of protection).

**Comment by yalosev** [comment]
```
skopeo list-tags docker://registry.deckhouse.io/deckhouse/ce/release-channel
```
reminder

**Comment by konstantin-axenov** [comment]
Related https://github.com/deckhouse/deckhouse/issues/5098
