### ISSUE TITLE
Enrich master nodegroup scaling docs

### ISSUE THREAD

**Issue by evstratbg** [deckhouse/deckhouse#333]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is no information how to scale master node in a cluster

### Proposed Solution

Enrich docs with info about scaling of a master nodes

### Additional Information

Telegram message link: https://t.me/deckhouse_ru/3133

**Comment by EvgenySamoylov** [comment]
This might be a good start for "dhctl usage FAQ" docs section.
