### ISSUE TITLE
Creating two CustomAlertmanager failed

### ISSUE THREAD

**Issue by lysyy** [deckhouse/deckhouse#3369]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1-41-2   Deployed

### Expected Behavior

When created two CustomAlertmanager, created two alertmanager sts and two configs.

### Actual Behavior

When created two CustomAlertmanager, something deletes one of Alertmanagerconfig, and prometheus operator fails: msg="Sync \"d8-monitoring/alerts-to-alerta\" failed: provision alertmanager configuration: failed to get global AlertmanagerConfig: alertmanagerconfigs.monitoring.coreos.com \"alerts-to-alerta\" not found"
kubectl get CustomAlertmanager
NAME               TYPE
alerts-to-alerta   External
alerts-to-telega   Internal
$kubectl get Alertmanagerconfig -A
NAMESPACE       NAME               AGE
d8-monitoring   alerts-to-telega   17m

### Steps To Reproduce

Create this objects:
1.
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: alerts-to-alerta
spec:
  internal:
    receivers:
    - name: alerta-webhook-reciever
      webhookConfigs:
      - sendResolved: true
        url: http://alerta.d8-monitoring.svc:8080/webhooks/prometheus
    route:
      groupBy:
      - job
      groupInterval: 1m
      groupWait: 30s
      receiver: alerta-webhook-reciever
      repeatInterval: 1m
  type: External
2. 
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: alerts-to-telega
spec:
  internal:
    receivers:
    - name: webhook-telega-reciever
      webhookConfigs:
      - sendResolved: true
        url: http://telegram-alertmanager.d8-monitoring.svc:8080/alerts
    route:
      groupBy:
      - job
      groupInterval: 5m
      groupWait: 30s
      receiver: webhook-telega-reciever
      repeatInterval: 3h
  type: Internal

**Comment by EvgenySamoylov** [comment]
It looks like both types should be "internal" as it refers to the type of alertmanager: https://deckhouse.io/documentation/v1/modules/300-prometheus/cr.html#customalertmanager-v1alpha1-spec-type

**Comment by lysyy** [comment]
I try set both Internal, result is the same

**Comment by RomanenkoDenys** [comment]
Have one more case - https://flant.slack.com/archives/C78AQG5EY/p1679901561755499
