### ISSUE TITLE
Links in the "Enabled modules" section of the grafana home page should go to the inner cluster docs

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#3404]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have a lot of installations in the air-gapped infrastructure, with no internet access from the cluster. So having links to the deckhouse.io docs on the grafana home page is meaningless in such clusters.
<img width="1383" alt="Screenshot 2022-12-21 at 22 03 35" src="https://user-images.githubusercontent.com/9217407/209204625-318320e2-a2ac-4c89-8592-3733f57e6e19.png">

### Proposed Solution

Yet it's a bigger challenge to change these links to the inner doc than it might seem to be. We need to have the global hook to render these metrics based on the status of the deckhouse-web module:
1. If the deckhouse-web module is enabled, we need to render the publicDomainTemplate and make the appropriate links.
2. If it's disabled - render the public docs instead.

**Comment by nabokihms** [comment]
1. Add a hook that will expose metrics with proper URLs with a public domain template.
2. Use these metrics for the Enabled modules panel (somehow).
