### ISSUE TITLE
[istio] kiali impersonalisation and RBAC

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#3421]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Kiali by default uses the kiali SA to work with k8s API. So, it has the maximum access level for any user logged in.

### Proposed Solution

To use the [token](https://kiali.io/docs/configuration/authentication/token/) or [header](https://kiali.io/docs/configuration/authentication/header/) authentication strategy.
It seems we can use the header srategy out-of-the-box. But we can use it only if there the user-authn module is in use.

**Comment by EvgenySamoylov** [comment]
Refers to #2765

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by apolovov** [comment]
Solved in https://github.com/deckhouse/deckhouse/pull/8830.
