### ISSUE TITLE
Release v1.29.0

### ISSUE THREAD

**Issue by diafour** [deckhouse/deckhouse#344]
:point_right: Use this issue to test milestone [v1.29.0](https://github.com/deckhouse/deckhouse/milestone/5) and deploy released tag.
            :point_right: Use 'e2e/run/' labels to run default e2e test.
            :point_right: Use 'e2e/use/' labels to run specific e2e test.
            :point_right: Use 'deploy/' labels to deploy site and documentation.
            :point_right: Use 'deploy/deckhouse/' labels to deploy to channels after creating tag.

**Comment by deckhouse-BOaTswain** [comment]
New commit [b83449](https://github.com/deckhouse/deckhouse/commit/b834498167512dd9683b1104f7fdeab53bc55e8e) in branch 'main':
```
Merge branch 'ci_github_werf_run_rebuild' into 'main'

[github-actions] fix(ci): prevent rebuild during werf run

See merge request sys/deckhouse-oss!790
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [e96177](https://github.com/deckhouse/deckhouse/commit/e9617732e37f472804a01343356aa9bd15a79538) in branch 'main':
```
Merge branch 'ci_github_e2e_vsphere_runner' into 'main'

[github-actions] fix(ci): add labels to runs-on for e2e tests

See merge request sys/deckhouse-oss!791
```

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/vsphere"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/yandex-cloud"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/vsphere"...

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/vsphere"...

**Comment by deckhouse-BOaTswain** [comment]
New commit [f450ae](https://github.com/deckhouse/deckhouse/commit/f450aeda0f911f94b83a28ccb7d6e5f2a911692e) in branch 'main':
```
Merge branch 'ci_github_e2e_vsphere_layout' into 'main'

[github-actions] fix(ci): set Standard layout for vSphere e2e test

See merge request sys/deckhouse-oss!792
```

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/vsphere"...

**Comment by deckhouse-BOaTswain** [comment]
New commit [20db32](https://github.com/deckhouse/deckhouse/commit/20db325e2d5fdb9ca494f24d9f95beb8324276c9) in branch 'main':
```
Merge branch 'doc-fix-details' into 'main'

[docs][prometheus] Update FAQ

See merge request sys/deckhouse-oss!795
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [d99a16](https://github.com/deckhouse/deckhouse/commit/d99a16191ad3801399f8ae243ff0ba5614a21d74) in branch 'main':
```
[user-authn] Dex rate limit doc (#352)

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [e1ac76](https://github.com/deckhouse/deckhouse/commit/e1ac76a9d9624708baf6e5af62084f444a410344) in branch 'main':
```
Merge pull request #354 from deckhouse/nm-fix-copyright-validator

[ci][validators] Golang copyright one line comments without previous new line
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [befa48](https://github.com/deckhouse/deckhouse/commit/befa48c3cf4974fca3e3d9eb72c593c089b11d4b) in branch 'main':
```
Merge pull request #356 from deckhouse/nm-fix-cyrilic-validator-formatting

[ci][validators] Fix "No Cyrillic" validator formatting
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [bba226](https://github.com/deckhouse/deckhouse/commit/bba226082991d6153bda0e84a84a367fcec31c5b) in branch 'main':
```
Merge pull request #351 from deckhouse/upmeter-scheduling-config

[upmeter] Node selector and toleration settings for server
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [9ff9fa](https://github.com/deckhouse/deckhouse/commit/9ff9fa69817b74bb6a53f4ce04d6fc33c3566d47) in branch 'main':
```
Merge pull request #358 from deckhouse/update-readme-logo

[docs] Updating README
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [4617fa](https://github.com/deckhouse/deckhouse/commit/4617faa68fd9374b577b1a1867f28a81e92520d5) in branch 'main':
```
[istio] Refactoring (#357)

* Refactoring
* Internal libraries build fix
* Refactoring generate_ca.go fix
* Add mount to golang ci linter docker options
* Add copyrights
* Render CI templates

Co-authored-by: m.nabokikh <maksim.nabokikh@flant.com>
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [b12800](https://github.com/deckhouse/deckhouse/commit/b128009533bc0008ae7ad6e8aa160d7a9afb3b10) in branch 'main':
```
[deckhouse] fix update hook Manual mode (#362)
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [9c7075](https://github.com/deckhouse/deckhouse/commit/9c70754d9110a825a45bab842a6d3279d79870b3) in branch 'main':
```
http checker: fail when cannot dial (#349)
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [b2c6b4](https://github.com/deckhouse/deckhouse/commit/b2c6b473778a7343447b8129556d5dd1deef718d) in branch 'main':
```
Merge pull request #389 from deckhouse/nm-fix-dashboard

[ingress-nginx][monitoring-k8s] Fix. Revert refresh on grafana dashboard
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [311cd3](https://github.com/deckhouse/deckhouse/commit/311cd3671b1efadc46b40c13f1a608dd56cec4e1) in branch 'main':
```
Merge pull request #391 from deckhouse/fix-update-deckhouse

[deckhouse] fix update deckhouse hook
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [27589a](https://github.com/deckhouse/deckhouse/commit/27589a09557d65c6965298d9becfe1f7c35b7b4f) in branch 'main':
```
Merge pull request #342 from deckhouse/user-authz-rules-combinations

[user-authz] How rules are combined
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [96a03d](https://github.com/deckhouse/deckhouse/commit/96a03d8277138527a5938a75dbba459f8ead1b88) in branch 'main':
```
Merge pull request #370 from deckhouse/metallb-doc

[metallb] added source-address parameter to doc.
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [65de93](https://github.com/deckhouse/deckhouse/commit/65de93aa667282a2a6b71a650b181133da7f321c) in branch 'main':
```
Merge pull request #361 from deckhouse/nm-fix-yandex

[yandex-cloud-provider] Fix. Add additionalExternalNetworkIDs config in openapi spec
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [817e8f](https://github.com/deckhouse/deckhouse/commit/817e8f970f51f1893f1e1c6ad3bf88fbc83a1833) in branch 'main':
```
Merge pull request #364 from deckhouse/chrony-fix2

[chrony] fix rollout restart time
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [39df89](https://github.com/deckhouse/deckhouse/commit/39df8941bc646f11bd60057f486df3fff360f6c6) in branch 'main':
```
Merge pull request #404 from deckhouse/etcd-faq-clarify

[control-plane-manager] Clarify `--force-new-cluster` usage
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [3c5f10](https://github.com/deckhouse/deckhouse/commit/3c5f10d930e12216b99a02bdd86ffe76e0d74432) in branch 'main':
```
Merge pull request #367 from deckhouse/force-disruption-drain

[node-manager] Force disruption drain
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [0595f7](https://github.com/deckhouse/deckhouse/commit/0595f79eb14f35f0daa67171eb03fa94497793c9) in branch 'main':
```
Merge pull request #393 from deckhouse/ingress-default-certificate

[ingress-nginx] add the ability to set a default certificate
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [ebfad5](https://github.com/deckhouse/deckhouse/commit/ebfad5bb3b30e6fdef2a3ae7dd515771ecd5b7f5) in branch 'main':
```
Merge pull request #374 from deckhouse/cert-manager-vault

[cert-manager] vault integration docs
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [087a6e](https://github.com/deckhouse/deckhouse/commit/087a6e9c192295ca035b4e064811348b5ec9148a) in branch 'main':
```
Merge pull request #400 from deckhouse/ci_github_runs_on_labels_for_non_e2e_jobs

[ci] feat(ci): use 'regular' label to schedule non e2e jobs
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [41a6fd](https://github.com/deckhouse/deckhouse/commit/41a6fd88f5877f1c66abf8c250bb40b6ff6d541a) in branch 'main':
```
Merge pull request #409 from deckhouse/ci_github_actionlint

[github] use actionlint if available
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [36d522](https://github.com/deckhouse/deckhouse/commit/36d522fa2a7da5e31461aec45fe8afdae6b4b659) in branch 'main':
```
Merge pull request #350 from deckhouse/upm-resched-pvc-zone-change

[upmeter] rescheduler hook: more reliable Pod re-creating, deleting PVC on zone change
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [21f8de](https://github.com/deckhouse/deckhouse/commit/21f8de671f92738c15c0aee74f6fa04150a059bd) in branch 'main':
```
Merge pull request #398 from deckhouse/upgrade-cert-manager

[cert-manager] Upgrade to v1.6.1
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [ff19c1](https://github.com/deckhouse/deckhouse/commit/ff19c1123f594470f0f3e952300c648e9f532b45) in branch 'main':
```
Merge pull request #375 from deckhouse/bashible-context

[deckhouse] generate bashible context inside bashible-apiserver
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [7c6d7a](https://github.com/deckhouse/deckhouse/commit/7c6d7af8c2bf554b59d216f7594ea5e4c8d1004e) in branch 'main':
```
Merge pull request #372 from deckhouse/log-shipper_elasticsearch-datastream

[log-shipper] Elasticsearch datastream support
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [fd6fe8](https://github.com/deckhouse/deckhouse/commit/fd6fe853662920c13d44c6a757f543a880467bb6) in branch 'main':
```
Merge pull request #399 from kvaps/upd-openstack-config

[getting-started] Update config.yml for OpenStack
```

**Comment by deckhouse-BOaTswain** [comment]
New commit [324e7f](https://github.com/deckhouse/deckhouse/commit/324e7f4b18629aa31b8562da5d9fad865f05ae3c) in branch 'main':
```
Merge pull request #421 from deckhouse/grafana-bump-8-2-7

[prometheus] Bump Grafana to 8.2.7
```

**Comment by deckhouse-BOaTswain** [comment]
Run workflow "e2e/run/aws"...

**Comment by deckhouse-BOaTswain** [comment]
New tag 'v1.29.0' is created.
