### ISSUE TITLE
[cloud-provider-azure] Add firewall rule to allow UDP 123 port for NTP to work

### ISSUE THREAD

**Issue by gmaiorov** [deckhouse/deckhouse#3444]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Azure doesn't enable SNAT for a transport protocol (i.e. TCP/UDP) outbound connections unless a load balancer for a corresponding transport protocol exists.

This leads to blocked outbound UDP connections on nodes without external IP address, so `chrony` wouldn't work unless there are some UDP load balancing rules are created.
Further info available at https://github.com/pivotal-cf/terraforming-azure/issues/25.

### Proposed Solution

Automatically create UDP load balancing rule like in https://github.com/pivotal-cf/terraforming-azure/commit/3ea2b49b6fa0f7f9841ccf65b521dd1a09373e7a.

**Comment by EvgenySamoylov** [comment]
PR #3943
