### ISSUE TITLE
[LINSTOR] collect telemetry

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#3454]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Need to know LINSTOR usage in clusters managed by Flant.

### Proposed Solution

Add exporter and collect telemetry.

**Comment by EvgenySamoylov** [comment]
Part of the #2010

**Comment by kvaps** [comment]
fixed by https://github.com/deckhouse/deckhouse/pull/3615
