### ISSUE TITLE
Helm library usage

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3464]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to add the documentation about all helm lib template functions and their usages.
At the moment you have to search the code to understand, what is implemented in the helm lib

### Proposed Solution

- Write the documentation for all functions
- How to connect/use helm lib in 3rd party modules
- How to handle helm_lib versioning

**Comment by EvgenySamoylov** [comment]
PR is here #3665
