### ISSUE TITLE
Addon-operator follow-up

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3466]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need a functionality to handle the trigger from deckhouse to reload modules in the `external` directory in the addon-operator

### Proposed Solution

Need research. Seems it could be one more function for the `go_lib/deckhouse-config`. We have the addon-operator instance there

Obvious solution: restart Deckhouse on a signal

**Comment by EvgenySamoylov** [comment]
Added here: #3629
