### ISSUE TITLE
Deckhouse-config module: handle external modules

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3467]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need a trigger for reloading modules from an external source. Also we have to validate their schemas

### Proposed Solution

- [x] handle a signal from the `external module manager` module 
  - [ ] find `ModuleConfig` for external modules
  - [ ] enable specified modules
  - [ ] load and validate openapi schema
- [x] add one more column to the ModuleConfig list which will show the source of a module: `embeded` | `external: $repo-name` (#3531)

**Comment by EvgenySamoylov** [comment]
#3531
