### ISSUE TITLE
[cni-cilium] CNI cilium grafana dashboard

### ISSUE THREAD

**Issue by fl64** [deckhouse/deckhouse#3497]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We do not have grafana dashboard for CNI cilium metrics

### Proposed Solution

Add grafana dashboard for CNI cilium

**Comment by RomanenkoDenys** [comment]
https://github.com/deckhouse/deckhouse/pull/3949
