### ISSUE TITLE
[cloud-provider-yandex] YandexClusterConfiguration allows setting coreFraction to 0

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#3551]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42

### Expected Behavior

It is impossible to set coreFraction = 0.

### Actual Behavior

It is possible to set coreFraction = 0, but yandex console doesn't allow it.

**Comment by EvgenySamoylov** [comment]
It needs just remove 0 from the [array](https://github.com/deckhouse/deckhouse/blob/main/candi/cloud-providers/yandex/openapi/cluster_configuration.yaml#L231).
