### ISSUE TITLE
[ingress-nginx] inlet loadBalancerWithProxyProtocol processes with an error the parameter acceptRequestsFrom

### ISSUE THREAD

**Issue by stratnevpy** [deckhouse/deckhouse#3565]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42.4

### Expected Behavior

I want to use acceptRequestsFrom parameter with inlet loadBalancerWithProxyProtocol, to filter incoming connection by ip.

### Actual Behavior

When i set up acceptRequestsFrom, ingress controller continues to process requests from all sources.

### Steps To Reproduce

1. Configure parameter acceptRequestsFrom to accept connection only from your ip address and deploy ingress controller with inlet loadBalancerWithProxyProtocol
2. Put some resource behind ingress controller.
3. Check availability this resource from your ip address and from another different.

**Comment by EvgenySamoylov** [comment]
It needs to add [realIPHeader](https://deckhouse.io/documentation/v1/modules/402-ingress-nginx/cr.html#ingressnginxcontroller-v1-spec-loadbalancer-realipheader) parameter to the loadBalancerWithProxyProtocol object.

**Comment by EvgenySamoylov** [comment]
As a workaround we suggest to use the sourceRanges function in the clouds.

**Comment by konstantin-axenov** [comment]
[acceptRequestsFrom](https://deckhouse.io/documentation/v1/modules/402-ingress-nginx/cr.html#ingressnginxcontroller-v1-spec-acceptrequestsfrom) works as expected.
> Regardless of the inlet type, the source IP address gets always verified (the original_address field in logs) (the address that the connection was established from) and not the “address of the client”

You should use annotation [nginx.ingress.kubernetes.io/whitelist-source-range](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range) or config map parameter [whitelist-source-range](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#whitelist-source-range).
