### ISSUE TITLE
[prometheus] Support setting custom CA for remote_write

### ISSUE THREAD

**Issue by gmaiorov** [deckhouse/deckhouse#3572]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are no option to configure custom CA in [D8's PrometheusRemoteWrite CRD](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/crds/prometheusremotewrite.yaml#L104), but Prometheus-Operator's CRD [has such feature](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml#L5219).
Some clients forced to use `insecureSkipVerify`, which is not secure.

### Proposed Solution

Implement `ca` property in D8's PrometheusRemoteWrite CRD.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
