### ISSUE TITLE
proposal: [documentation] LocalPathProvisioner examples are not clear enough

### ISSUE THREAD

**Issue by mac2000** [deckhouse/deckhouse#363]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Takes me a few days to realize how everything works 🤷‍♂️

Thankfully engineers from the Flant did help with answers and guidance 💪

### Proposed Solution

Example section of LocalPathProvisioner should shout about storage class and have complete usage examples so it will become really obvious how to use it

### Additional Information

#360 - related issue about retention policy

This issue is a template to create and link PR for docs, hopefully it will be accepted 🤞

**Comment by RomanenkoDenys** [comment]
Fixed by #561
