### ISSUE TITLE
[control-plane-manager] keep more audit logs on masters

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#3653]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are 1GB of logs on every master, but sometimes it isn't enough, cause it can hold only ~4hours of logs on average cluster.

### Proposed Solution

It is reasonable to gzip logs after rotation. But it isn't obvious how to do it. Need investigation.
Mb, it is enough to gzip /var/log/kube-audit/audit-*.log every 10 minutes.

**Comment by EvgenySamoylov** [comment]
It will be fixed by implementing Loki as the new module: #2532

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
Loki feature was implemented.
