### ISSUE TITLE
[ingress-nginx] Add controller v1.5.1 support

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3730]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Our latest controller is 1.1 while upstream has 1.5.1 with a lot of improvements, such as:
- leader election via lease
- EndpointSlices usage instead of Endpoints
- Fix a lot of CVEs
- Bump nginx version
- and much more

### Proposed Solution

Add 1.5.1 images
Check [release-notes](https://github.com/kubernetes/ingress-nginx/releases) between 1.1 and 1.5.1 and update template parametes, RBAC and others

**Comment by EvgenySamoylov** [comment]
Fixed in #3923
