### ISSUE TITLE
[candi] Update containerd config in candi bashible steps

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3751]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We updated containerd to 1.6.14, and maybe need update its config in bashible steps (now it's generated in 1.4.3)

### Proposed Solution

Update config [here](https://github.com/deckhouse/deckhouse/blob/main/candi/bashible/common-steps/node-group/050_configure_and_start_containerd.sh.tpl#L47)

**Comment by RomanenkoDenys** [comment]
@duckhawk why we need to update config ?

**Comment by apolovov** [comment]
I think, the point is to sync our config with `containerd config default`.

**Comment by duckhawk** [comment]
In fact, AIS, no critical changes, so we don't need it. Close.
