### ISSUE TITLE
[ingress-nginx] Ability to add custom labels to Prometheus metrics

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3755]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It would be useful to have the ability to add additional metric labels, to use it for advanced monitoring.
There was [issue](https://github.com/kubernetes/ingress-nginx/issues/4754) in upstream, but it closed

### Proposed Solution

Research this case, maybe it already implemented. Maybe create patch in upstream.

**Comment by konstantin-axenov** [comment]
This can be solved by such expression and custom dashboard
```
ingress_nginx_detail_backend_info{ingress="d8-connect"} * on (ingress, namespace) group_left (label_app) (kube_ingress_labels)
```

**Comment by konstantin-axenov** [comment]
Closing this issue because the previous [solution](https://github.com/deckhouse/deckhouse/issues/3755#issuecomment-1623169984) seems enough for most cases.

**Comment by konstantin-axenov** [comment]
Closing this issue because the previous https://github.com/deckhouse/deckhouse/issues/3755#issuecomment-1623169984 seems enough for most cases.
