### ISSUE TITLE
[ingress-nginx] Improve logs formatting

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3762]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Log formatting in the ingress nginx controller could be more intelligent. It uses a plain text template to compose a JSON.

1. Fields similar by the meaning represent different variable types, e.g., `status` is a number, and `upstream_status` is a string.
2. The JSON is only sometimes valid because variables representing numbers may be absent. Example:
```json
{"status": ,"upstream_status": 500}
```

### Proposed Solution

I see two possible options to solve the problem:
1. Deal with all edge cases by diving deeper. 
2. Using log_by_lua stage to print JSON messages.

### Additional Information

https://flant.slack.com/archives/C03B7S7P8FP/p1698326984309379?thread_ts=1698258105.226539&cid=C03B7S7P8FP

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
