### ISSUE TITLE
[candi] No alert about fatal error in case of invalid initial config

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3776]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.42.7

### Expected Behavior

Alert user in case of fatal error in deckhouse pod due installation

### Actual Behavior

There was an error in initial config
Deckhouse pod crashed with error
```
{"level":"error","msg":"Fatal: init module manager: load overridden initial config: config not valid: 2 errors occurred:\n\t* 'global' section in ConfigMap/deckhouse is not valid\n\t* global.modules.storageClass is a forbidden property\n\n","time":"2023-02-06T14:02:31Z"}
```
And installer stucked in checking logs state:
```
│ ┌ Waiting for Deckhouse to become Ready
│ │ Deckhouse pod found: deckhouse-748684954f-thnzf (Pending)
│ │ Deckhouse pod found: deckhouse-748684954f-thnzf (Pending)
│ │ Deckhouse pod found: deckhouse-748684954f-thnzf (Running)
│ │ Running pod found! Checking logs...

```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
We can add validation in preflight checks if we replace InitConfiguration with ModuleConfig.

**Comment by konstantin-axenov** [comment]
Show info and logs for deckhouse pods that are not in running or pending state.

**Comment by yuriygoryaev** [comment]
depends on #5073

**Comment by raabdullaev-fl** [comment]
Implemented in https://github.com/deckhouse/deckhouse/pull/6061.
