### ISSUE TITLE
[linstor] Allow to use ZFS storage backend driver

### ISSUE THREAD

**Issue by gmaiorov** [deckhouse/deckhouse#3808]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Linstore module in Deckhouse provides LVM as a sole storage backend driver option.
This configuration is prone to [silent data corruption](https://en.wikipedia.org/wiki/Data_corruption#Silent) as LVM doesn't check data checksums.
However, ZFS could be used to mitigate such risks, seamlessly checking data and metadata checksums, and it is supported by Linstore.

### Proposed Solution

Linstore module could expose ZFS storage backend driver provided by Linstore.

### Additional Information

Additional information about e2e data integrity and how ZFS can be used to combat silent data corruption could be found in the following work:
https://research.cs.wisc.edu/wind/Publications/zfs-corruption-fast10.pdf

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
We don't have plans to add ZFS support. We don't have any requests on this feature. Closing the issue. Feel free to reopen it if the feature really required.
