### ISSUE TITLE
Grafana dashboard provisioner deletes existing dashboards

### ISSUE THREAD

**Issue by Ruthercode** [deckhouse/deckhouse#3823]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.43.4 CE

### Expected Behavior

Creating new and saving existing dashboards

### Actual Behavior

Deletion existing dashboards created by GrafanaDashboardDefinition CR’s

### Steps To Reproduce

1. Create a dashboard 
2. See logs of dashboard provisioner

### Additional Information

This could be in previous versions of v1.43, the version provided at the time of finding the bug

### Logs

```shell
{"binding":"dashboard_resources","event":"kubernetes","hook":"dashboard_provisioner.sh","level":"info","msg":"ERROR: definition.uid is mandatory field","output":"stderr","queue":"main","task":"HookRun","time":"2023-02-09T16:05:00Z"}
{"binding":"dashboard_resources","event":"kubernetes","hook":"dashboard_provisioner.sh","level":"info","msg":"ERROR: definition.uid is mandatory field","output":"stderr","queue":"main","task":"HookRun","time":"2023-02-09T16:05:14Z"}
{"binding":"dashboard_resources","event":"kubernetes","hook":"dashboard_provisioner.sh","level":"info","msg":"ERROR: definition.uid is mandatory field","output":"stderr","queue":"main","task":"HookRun","time":"2023-02-09T16:05:27Z"}
```

**Comment by EvgenySamoylov** [comment]
Please check the log mentioned error message: `"ERROR: definition.uid is mandatory field"`
Probably this will fix it.

**Comment by Ruthercode** [comment]
Didn't quite understand the documentation and created dashboards without `definition.uid`, the new update with validation dashboards removed existing ones
