### ISSUE TITLE
[bashible] ContainerD rpm dependencies

### ISSUE THREAD

**Issue by gyrter** [deckhouse/deckhouse#3827]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.43.4 CE

### Expected Behavior

Auto-update for CRI on cluster nodes without problems.

### Actual Behavior

Bashible install pacvkages with very progressive versions from CentOS 9 Stream. 
```
 container-selinux.x86_64.rpm depends on
Feb 09 17:04:43 dc01-dev1-k8s-master01 bashible.sh[358578]:         selinux-policy >= 38.1.2-1.el9 is needed by container-selinux-3:2.198.0-1.el9.noarch
Feb 09 17:04:43 dc01-dev1-k8s-master01 bashible.sh[358578]:         selinux-policy-base >= 38.1.2-1.el9 is needed by container-selinux-3:2.198.0-1.el9.noarch
Feb 09 17:04:43 dc01-dev1-k8s-master01 bashible.sh[358578]:         selinux-policy-targeted >= 38.1.2-1.el9 is needed by container-selinux-3:2.198.0-1.el9.noarch
```

But CentOS Stream is a rolling update Linux Distribution. We use Rocky Linux 9.1

### Steps To Reproduce

1. Install on Rocky Linux 9.1
2. Use Beta release channel

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
