### ISSUE TITLE
[ci] Enabled staged builds for container images

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#3830]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

werf.io is a primary tool for building images for Deckhouse. For Docker files, it always merges all layers into a single final layer and saves it to the registry. 

Caching stages and rebuilding images partially is impossible with this approach. Yet, a great feature is available in werf to preserve layers, which should be enabled manually. We hope that enabling this feature will drastically reduce used space in the registry and the time of rebuilds.

### Proposed Solution

The example of `werf.yaml` with the feature enabled.
```yaml
configVersion: 1
project: x
---
image: x
dockerfile: ./Dockerfile
staged: true
```

### Additional Information

:warning: **CAUTION!**:warning: 

* Container images will be rebuilt.
* More tags in the registry.
* Less space consumption.

**Comment by nabokihms** [comment]
https://github.com/werf/werf/issues/2215

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Feature is ready in werf.

**Comment by vitaliy-sn** [comment]
We need runners with Buildah.
```shell
│ │ common/distroless/stage/apk_extractor/WORKDIR  Staged build of Dockerfile is not available for Docker Server backend.Please  ↵
either:
│ │ common/distroless/stage/apk_extractor/WORKDIR   * switch to Buildah backend;
│ │ common/distroless/stage/apk_extractor/WORKDIR   * or disable staged build by setting `staged: false` for the image in the    ↵
│ │ common/distroless/stage/apk_extractor/WORKDIR  werf.yaml.
│ │ common/distroless/stage/apk_extractor/WORKDIR  
```

**Comment by raabdullaev** [comment]
Not planned. Werf.yaml will be used.
