### ISSUE TITLE
[monitoring] Add alert about RO-mounted filesystems in pods

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3893]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There can be different problems if filesystem in pod became RO. (e.g. broken postgresql, errors in web-apps, etc)

### Proposed Solution

Add alert about RO-mounted filesystems in pods

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Application have to distinctly detect that it's working improperly. If the application has correct readiness probe, then it is unready when filesystem is RO. User can enable extended monitoring and receive alert about unavailable replicas. This seems like flow that solves the case. But still, feature looks like nice to have.
