### ISSUE TITLE
[linstor] prohibit removal of a node with linstor volumes

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#3894]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

While removing node with active linstor volumes, data loss is possible (e.g. in case of a volume with one replica)

### Proposed Solution

Create/modify webhook to check this situation and forbid node removal.

**Comment by duckhawk** [comment]
When we have static cluster with linstor, recommended path is to move linstor volumes from node with linstor pool: 
`linstor evacuate node`
And then `kubectl delete node`
But if you simply do `kubectl delete node` on node with linstor storage pool, it will be deleted without any warning, and we can potentially get data corruption/volume loss.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by altermann1** [comment]
partially fixed in https://github.com/deckhouse/deckhouse/pull/6400
