### ISSUE TITLE
[docs] Azure vNetCIDR parameter

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#3944]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Docs do not give enough information for the parameter

### Proposed Solution

The description of the parameter in the documentation should have been made more detailed. It is not clear what are the risks of creating two or more clusters with the same vNetCIDR (peering for example). It should be described in more detail

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
