### ISSUE TITLE
Add CIS Benchmark periodic tasks and report

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3948]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This is quite often requested report.

### Proposed Solution

Run periodic task and generate metrics for prometheus. Consider adding dashboard.

**Comment by konstantin-axenov** [comment]
Also enable NodeRestriction and fix other fails for master
```
[FAIL] 1.1.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Automated)
[FAIL] 1.2.16 Ensure that the admission control plugin NodeRestriction is set (Automated)
[FAIL] 1.2.20 Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Automated)
```

**Comment by EvgenySamoylov** [comment]
[Trivy operator](https://devopstales.github.io/trivy-operator/2.5/functions/cis-benchmark/) could realise CIS Benchmark.
