### ISSUE TITLE
Ingress inlet HostPort with `httpsPort: 6443` deployed on control-plane nodes breaks Kubernetes API

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#3961]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44

### Expected Behavior

Looks like misconfiguration that should be prevented.

### Actual Behavior

Kubernetes API breaks.

### Steps To Reproduce

Create IngressNginxCongroller `inlet: HostPort` and `httpsPort: 6443`. Set nodeSelector to control-plane nodes.

**Comment by yalosev** [comment]
Consider migrating to the OpenAPI 3.x to have `not` keyword support =/
