### ISSUE TITLE
Deny the start of the container if High or Critical CVEs are detected in the image

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#3965]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We've [realized](https://github.com/deckhouse/deckhouse/pull/3858) operator-trivy module that constantly scans container images for CVEs. But it doesn't prevent containers from being launched with CVEs detected though, which is not a security best practice.

### Proposed Solution

Deny the start of the container if High or Critical CVEs are detected in the image + log the event + alert the administrator.

**Comment by nabokihms** [comment]
This can be achieved by using an external data provider for OPA Gatekeeper. There is [an example of a working one](https://github.com/sozercan/trivy-provider), but we can develop our version suitable for our needs.

**Comment by yalosev** [comment]
https://github.com/aquasecurity/trivy/discussions/4354

**Comment by yalosev** [comment]
Have to check `trivy-server`. Maybe it has some http handlers to interact with
