### ISSUE TITLE
Wrong disk order in the Openstack for AltLinux

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#3973]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main 2023-03-02

### Expected Behavior

Correctly identify a drive for etcd regardless of its name.

### Actual Behavior

When you first start the instance, the order of the disks is incorrect.

### Additional Information

This issue is currently known to only occur on our openstack cluster (tfcloud).

```
# first run after creating instance
[root@dev3-master-0 ~]# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda      8:0    0  10G  0 disk 
sdb      8:16   0  20G  0 disk 
└─sdb1   8:17   0  20G  0 part /
[root@dev3-master-0 ~]# reboot
...
# after reboot
[altlinux@dev3-master-0 ~]$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda      8:0    0  20G  0 disk 
└─sda1   8:1    0  20G  0 part /
sdb      8:16   0  10G  0 disk
```

**Comment by nabokihms** [comment]
Related https://github.com/deckhouse/deckhouse/pull/3555

**Comment by vitaliy-sn** [comment]
As of now, using deckhouse from the main branch, this issue no longer reproduces.
