### ISSUE TITLE
deckhouse-controller cannot edit absent secret  d8-static-cluster-configuration

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#3983]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v.1.43.8

### Expected Behavior

deckhouse-controller shoul have the ability to create StaticClusterConfiguration resource.

### Actual Behavior

deckhouse-controller fails to create StaticClusterConfiguration resource.

### Logs

```shell
[root@ ~]# kubectl -n d8-system exec -ti deploy/deckhouse -- deckhouse-controller edit static-cluster-configuration
Connect to Kubernetes API
Get Kubernetes API client
INFO[0000] Kubernetes client is configured successfully with 'out-of-cluster' config  operator.component=KubernetesAPIClient
Succeeded!

Get Kubernetes API client
Waiting for Kubernetes API to become Ready
Succeeded!

Waiting for Kubernetes API to become Ready
Connect to Kubernetes API
deckhouse-controller: error: secrets "d8-static-cluster-configuration" not found, try --help
command terminated with exit code 1
```
```

**Comment by nabokihms** [comment]
It does make sense.

For now, we need to consider what users will see if they try to edit an empty config. Empty window? Some template?
Maybe there should always be a secret in the cluster without any settings.

**Comment by nabokihms** [comment]
The real-world case is when a cluster was bootstrapped without providing internal networks, but it turned out that one was required.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/pull/9689
