### ISSUE TITLE
Bootstrap script error with yandex cloud provider

### ISSUE THREAD

**Issue by drudrum** [deckhouse/deckhouse#40]
`dhctl bootstrap --ssh-user=user   --ssh-agent-private-keys=/tmp/.ssh/id_rsa   --config=/config.yml   --resources=/resources.yml --yes-i-want-to-drop-cache`

terraform give me unexcepted error
```
Error: key unmarshal fail: invalid character 'a' looking for beginning of value

  on ../layouts/without-nat/base-infrastructure/providers.tf line 15, in provider "yandex":
  15: provider "yandex" {
```

**Comment by toywar** [comment]
@drudrum try to run docker by using this command (added mount json to container):
`docker run -it -v "$PWD/config.yml:/config.yml" -v "$HOME/.ssh/:/tmp/.ssh/" \
>  -v "$PWD/resources.yml:/resources.yml" -v "$PWD/dhctl-tmp:/tmp/dhctl"  registry.deckhouse.io/deckhouse/ce/install:stable bash`
It works well for me.

**Comment by drudrum** [comment]
I put one line json content of `deckhouse-sa-key.json` to field `serviceAccountJSON`.

"a JSON key generated by yc iam key create"  = one line json content of `deckhouse-sa-key.json`

**Comment by shurup** [comment]
> "a JSON key generated by yc iam key create" = one line json content of `deckhouse-sa-key.json`

Thank you for this useful remark! Will fix it in our Getting Started as it's not the first time the same issue arises.
