### ISSUE TITLE
[candi] Set `network_acceleration_type=SoftwareAccelerated` for new nat instances in Yandex Cloud

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#4000]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Nat instance performance is crucial for layout with nat instance in Yandex Cloud.

### Proposed Solution

- Set `network_acceleration_type=SoftwareAccelerated` for new nat instances. It can be enabled manually for old nat instances.
- Tune `sysctl -w net.netfilter.nf_conntrack_max=1048576` with cloud init

**Comment by nabokihms** [comment]
With the limited contrack table, users can face unexpected connection errors on reaching the limit.
