### ISSUE TITLE
[candi] Get rid of packer in the installation instructions for vSphere

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#4013]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Packer brings extra complexity to the installation process.

### Proposed Solution

Using correct images with updated cloud-init should work out of the box. Consider removing packer.

**Comment by name212** [comment]
deleted
https://deckhouse.io/gs/vsphere/step3.html#preparing-a-virtual-machine-image
