### ISSUE TITLE
[log-shipper] Graylog destination

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4053]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The [GELF codec](https://vector.dev/docs/reference/configuration/sinks/http/#encoding.codec) was introduced in vector.

### Proposed Solution

Add a new destination for Graylog.
TODO: think about design.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
