### ISSUE TITLE
[log-shipper] Batch exceeds Loki limit

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4054]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44.0

### Expected Behavior

No error.

### Actual Behavior

Vector tries to send batches bigger than the limit.

### Steps To Reproduce

?

### Additional Information

log-shipper logs:
```
2023-03-06T21:48:31.889603Z  WARN sink{component_kind="sink" component_id=destination/cluster/loki component_type=loki component_name=destination/cluster/loki}:request{request_id=1328}: vector::sinks::util::retries: Retrying after error. error=Server responded with an error: 500 Internal Server Error
2023-03-06T22:48:31.960842Z  WARN sink{component_kind="sink" component_id=destination/cluster/loki component_type=loki component_name=destination/cluster/loki}:request{request_id=1328}: vector::sinks::util::retries: Retrying after error. error=Server responded with an error: 500 Internal Server Error
```

Loki logs:
```
level=warn ts=2023-03-06T21:48:31.888040661Z caller=logging.go:71 traceID=2a98a5f6d32e4992 msg="POST /loki/api/v1/push (500) 35.155768ms Response: \"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4751759 vs. 4194304)\\n\" ws: false; Accept-Encoding: identity; Content-Length: 4752377; Content-Type: application/json; User-Agent: Vector/0.24.2 (x86_64-unknown-linux-gnu); "
level=warn ts=2023-03-06T22:48:31.959181972Z caller=logging.go:71 traceID=3a84feb2c48d5e12 msg="POST /loki/api/v1/push (500) 37.811727ms Response: \"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4751759 vs. 4194304)\\n\" ws: false; Accept-Encoding: identity; Content-Length: 4752377; Content-Type: application/json; User-Agent: Vector/0.24.2 (x86_64-unknown-linux-gnu); "
```

**Comment by miklezzzz** [comment]
Couldn't reproduce the issue with default configuration. 
Spent hours twitching and tuning vector and was able to get similar problem in 0.24.2 (the version when the issues was reported) and 0.28.1 (current one) when had `batch.max_size` sink parameter set to something bigger than 5MB (default value is 1MB which is pretty safe for Loki's grpc limits). With default settings couldn't get vector to flush more than 
`2023-05-30T13:07:40.200180Z DEBUG hyper::proto::h1::io: flushed 961790 bytes`.
