### ISSUE TITLE
[bashible] add how to debug scripts

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4128]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

in case of problems on static nodes with execution bashible. it is not clear how to collect more information to fix or write issues

### Proposed Solution

1. add to documentation
```
systemctl stop bashible.timer
systemctl stop bashible.service
BASHIBLE_SKIP_UPDATE=yes /var/lib/bashible/bashible.sh --local
#or 
/bin/bash -eEo pipefail -c "export TERM=xterm-256color; unset CDPATH; cd  /var/lib/bashible/; source /var/lib/bashible/bashbooster.sh; source component.sh"
```
2. add error information to node events

**Comment by konstantin-axenov** [comment]
We already have this [feature](https://github.com/deckhouse/deckhouse/pull/3122) during cluster bootstrap. We can improve it and do it on regular bashible runs. Just need to consider on what failed attempt number to start debug output.

**Comment by yalosev** [comment]
Also we [have events](https://github.com/deckhouse/deckhouse/pull/3351) with errors in the default namespace

**Comment by RomanenkoDenys** [comment]
Lets add debug info same way as we do in bootstrap - after 3 unsuccesful attempts add `set -x`
