### ISSUE TITLE
[log-shipper] Investigate Loki out of order rewrite timestamp

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4129]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The out-of-order action for Loki destination is hard coded to `rewrite_timestamp` 
https://github.com/deckhouse/deckhouse/blob/7a47d938e8b48164d9fbc65d09ad5e8e62206283/modules/460-log-shipper/hooks/internal/vector/destination/loki.go#L128

It is required not to lose logs for Loki <=2.4 
https://vector.dev/docs/reference/configuration/sinks/loki/#out_of_order_action

However, with this configuration, users cannot rely on the timestamps of log samples to investigate the time events actually happened.

### Proposed Solution

Investigate and drop support for old Loki versions at some point.

### Additional Information

As a workaround, it is possible to use [extra labels](https://deckhouse.io/documentation/v1/modules/460-log-shipper/cr.html#clusterlogdestination-v1alpha1-spec-extralabels) to add another label with the original timestamp from log messages.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Solution looks like this
```
extraLabels:
  original_timestamp: "{{ timestamp }}"
```
