### ISSUE TITLE
HA mode for deckhouse pod.

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#4163]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Now we have only one replica of deckhouse controller pod, and in case if node with deckhouse is not ready, we should manually delete pod to reschedule it on another node. This is because deckhouse pod tolerates every taints. Such toleration is needed to allow deckhouse pod to work on cluster bootstrap, on cluster with errors, etc. 
We want to have HA for deckhouse pod.

### Proposed Solution

Deckhouse pod's HA mode should be similar to Kubernetes components:
for example, 3 deckhouse pods on 3 master nodes with leader election.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
