### ISSUE TITLE
[runtime-audit-engine] Tune buffers for faster stdout output of kube-apiserver audit

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#4194]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to see filtered events after reasonable time. There are delays of up to ten minutes before logs are shown in stdout of falco containerd. 

### Proposed Solution

Tune webhook [settings](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#batching).

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Seems that default in apiserver are quite reasonable. Closing for now.
