### ISSUE TITLE
[node-manager] Cluster API support

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4254]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Cluster API tool that proposes using a Kubernetes cluster to create other Kubernetes clusters. In addition to the API, it also has a command-line utility called clusterctl. It has support for the vast majority of existing cloud providers, which can help us to add support for more cloud providers in the future.

It consists of several controllers for the initial creation of infrastructure, creation of nodes for the control plane, creation of machines.

But first and foremost, Cluster API is an API that describes how objects in Kubernetes should look like.

![image](https://user-images.githubusercontent.com/32434187/228477936-46f42863-3f2a-4a3e-9b10-fbfa123e584d.png)

One of the main unresolved issues with Cluster API is the chicken-and-egg problem. To deploy a cluster, you need a cluster. The community suggests solving this problem by spinning up any local cluster (such as kind, rancher desktop), installing Cluster API on it, and transferring all state from the local cluster to the new cluster.

To create machines, Cluster API has different kinds of controllers - Machine* (controlled by capi-controller-manager, similar to Machine* in Deckhouse) and <Provider>Machine* (controlled by infra-operator, similar to InstanceClass and other provider-specific CRDs in Deckhouse). capi-controller-manager knows how to create machines from machines sets and machine deployments, infra operator knows how to go to a provider and order an instance according to created machines.

### Proposed Solution

1. Part of the process of creating a cluster in Deckhouse is not ideal from an API standpoint, but replacing it with Cluster API may worsen the creation of independent clusters.

    It is necessary to think about how to make the API more declarative. For example, remove masterNodeGroup and nodeGroup from the provider configuration and make them separate objects.

2. To create machines, switch to using Cluster API:
    * Install capi-controller-manager along with the node-manager module.
    * Install infra-operator along with the cloud-provider-* module.
3. Make sure that our hooks can work with different versions of the API (we don't want to take an intermediate version of MCM to cluster-api migration into operation).
4. Make sure that old NodeGroups continue to work with MCM, while new ones work only with Cluster API.
    * Upon startup, collect already created node groups, save the list somewhere.
    * In Helm, write an IF statement that creates an old instance class and old machine deployment if the node group already exists.
    * If the old node group is deleted, remove it from the list of old groups.
5. Two cluster autoscalers work simultaneously.
6. Think about how to incorporate MachinePools (you can already benefit from using them).
7. There is an abstraction around the cloud config - bootstrap provider. It is necessary to implement our own bootstrap provider for Bashible. An example of [bootstrap provider](https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap.html).
8. Come up with a hook for auto-relocation (safe daemonset update, but for nodes).

### Additional Information

Documentation https://cluster-api.sigs.k8s.io/

**Comment by RomanenkoDenys** [comment]
linked https://github.com/deckhouse/deckhouse/issues/5178
