### ISSUE TITLE
helm executable in deckhouse pod doesn't support some sprig functions

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#4277]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44

### Expected Behavior

helm bin should be identical to built-in helm library.
Or consider getting rid of it (40MB btw).

### Actual Behavior

```
cp -r /deckhouse/modules/300-prometheus/ /tmp/
cd /tmp/300-prometheus
deckhouse-controller module values prometheus > values.yaml
helm template  --repository-cache /tmp/ ./

Error: parse error at (prometheus/charts/deckhouse_lib_helm/templates/_resources_management.tpl:39): function "mulf" not defined
```

**Comment by konstantin-axenov** [comment]
Yes. It's better to get rid of this binary.
