### ISSUE TITLE
[loki] Protect with kube-rbac-proxy

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4315]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Anyone can write and read logs now.

### Proposed Solution

Protect Loki with kube-rbac-proxy like Prometheus and other software.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by borg-z** [comment]
@nabokihms  it looks like this problem is already fixed in 1.59 https://github.com/deckhouse/deckhouse/releases/tag/v1.59.0

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/pull/6911
