### ISSUE TITLE
change-registry.sh will not work at version 1.45+ because of init containter pull change from tag to sha256

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#4326]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.0

### Expected Behavior

change-registry.sh changes registry correctly

### Actual Behavior

change-registry.sh will be broken after v1.45.0 because of change init-container image format from
`image: ${REGISTRY_ADDRESS}${REGISTRY_PATH}:${DECKHOUSE_INIT_EXTERNAL_MODULES_CONTAINER_TAG}`
to 
`image: ${REGISTRY_ADDRESS}${REGISTRY_PATH}@${DECKHOUSE_INIT_EXTERNAL_MODULES_CONTAINER_SHA256}`

**Comment by nabokihms** [comment]
Let's rewrite it in go as a subcommand of the deckhouse-controller. With this, an actual working version of the script will always be in a deckhouse cluster.

**Comment by duckhawk** [comment]
> Let's rewrite it in go as a subcommand of the deckhouse-controller. With this, an actual working version of the script will always be in a deckhouse cluster.

It'll be perfect solution!
