### ISSUE TITLE
change-registry.sh don't add imagePullSecrets in case of switching from CE to FE

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#4328]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44.4

### Expected Behavior

change-registry.sh add imagePullSecrets in case of switching from CE to FE

### Actual Behavior

Have constantly ImagePullBackoff of Deckhouse pod

**Comment by nabokihms** [comment]
This case should be covered while rewriting the script in go
See https://github.com/deckhouse/deckhouse/issues/4326#issuecomment-1505142659
