### ISSUE TITLE
Add api-server port 6443 availability check.

### ISSUE THREAD

**Issue by SpecialForce3331** [deckhouse/deckhouse#4439]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

After deckhouse installation sometimes we have a situation, when 6443 port not available. It's might me firewall or another network probles. It's will be good to notify about this problem.

### Proposed Solution

Pre|Post install port availability check. It's can be simple netcat or telnet check.
First check on master node to itself.
Second check from manage node (where i run dhctl) to master node.

**Comment by konstantin-axenov** [comment]
Maybe we need just to remove `-s` flag from [curl](https://github.com/deckhouse/deckhouse/blob/main/candi/bashible/bashible.sh.tpl#LL87C16-L87C16).

**Comment by RomanenkoDenys** [comment]
Good solution, do it
