### ISSUE TITLE
[operator-trivy] Duplicate CVEs

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#4444]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44.4

### Expected Behavior

There are no duplicates in the dashboard table.

### Actual Behavior

Since we are using `sum(trivy_image_vulnerabilities{severity="Critical", namespace=~"$namespace"})` PromQL, we are not taking into consideration multiple pods or image_tags.

**Comment by EvgenySamoylov** [comment]
Doesn't it duplicate #4656?
