### ISSUE TITLE
Prevent usage of vulnerable tsl ciphers.

### ISSUE THREAD

**Issue by RomanenkoDenys** [deckhouse/deckhouse#4468]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

By default deckhouse components use the standard tls cipher list (inherited from the go crypto/tls library) which includes the vulnerable 3des. Several security scanners give us an error about insecure algorithms. We want to have ability to change list of used tsl ciphers for deckhouse components.

### Proposed Solution

Remove insecure tls ciphers from go code of deckhouse components.
Phase 1:
- [ ] Remove insecure tls ciphers from [kube-rbac-proxy](https://github.com/deckhouse/deckhouse/tree/main/modules/000-common/images/kube-rbac-proxy).
      * create patch to do not use 3des cipher by default.
      * create patch to avoid use of bash entrypoint (check secure-listen-address has ip is set from code).
      * remove bash entrypoint.
      * bump version of kube-rbac-proxy.

- [ ] Remove insecure tls ciphers from [bashible-apiserver](https://github.com/deckhouse/deckhouse/blob/main/modules/040-node-manager/images/bashible-apiserver).

Phase 2:
- [ ] after merge https://github.com/deckhouse/deckhouse/pull/4635 move kube-rbac-proxy to use common/distroless image as base.
- [ ] after merge https://github.com/deckhouse/deckhouse/pull/4635 move bashible-apiserver to use common/distroless image as base.

Phase 3:
- [ ] Remove insecure tls ciphers from another deckhouse components.

### Additional Information
```
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Forward Secrecy not supported by any cipher
```

Need to disable TLS_RSA_WITH_3DES_EDE_CBC_SHA и TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA.

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/issues/4440
