### ISSUE TITLE
[user-authz] ClusterAuthorizationRule get rid of regexes

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4489]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It has been more than three years since we released the first version of the API. It aged well, but some things are worth being refactored.

### Proposed Solution

Replace regular expressions for namespace picking with a [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).

As a substitution, it is possible to use the `namespace configurator` module and automatically set namespaces labels.

**Comment by yalosev** [comment]
@nabokihms don't you want to use the same pattern `matchNames`, `excludeNames`, `labelSelector` as [log-shipper](https://github.com/deckhouse/deckhouse/blob/main/modules/460-log-shipper/crds/cluster-logging-config.yaml#L59)
and [admission-policy-engine](https://github.com/deckhouse/deckhouse/blob/main/modules/015-admission-policy-engine/crds/operation-policy.yaml#L148)?

**Comment by yalosev** [comment]
Plan:
1. Make ClusterAuthorizationRule v1 version storable
2. Add field `namespaceLabelSelector` to the v1
3. Mark field `limitNamespaces` as deprecated
4. Add version v2alpha1
  - remove `limitNamespaces` field
  - add `labelSelector` field


I don't think we can migrate via v1 and v2alpha1 so we have to force users to do it manually
Also we have to react on different CRD versions in hooks
