### ISSUE TITLE
[global] Distribute binaries for users to air-gapped environments

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4493]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In air-gapped environments with no internet access, users cannot download a kubectl binary to operate the cluster from a PC.

### Proposed Solution

Distribute all required binaries with the platform and provide a way to download them. Probably using OCI images is the only option. The main problem there is that Dechkouse should contain, e.g., kubectl binaries for all Kubernetes versions (five) for Mac, Linux, and Windows, which makes it 15 binaries in total (~40 MB each).

Examples of clients we want to distribute:
- kubectl
- virtctl

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
