### ISSUE TITLE
[global] Set status that Deckhouse reacted to custom resource changes

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4526]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are custom resources controlled by Deckhouse. Deckhouse uses helm and the main queue to create resources by iterating on the list of custom resources discovered from the cluster.

When a user creates a CR, there is no feedback from Deckhouse that it sees the change and that the resource has been processed.

### Proposed Solution

Define a common structure in the status for all Deckhouse CRD with two fields:

```yaml
lastReactedResourceVersion: <int> # the version of the resource collected by a hook
lastProcessedResourceVersion: <int> # the version of the resource deployed with a helm
``` 

How to set these fields? Well, the first one can be controlled by a hook, but the second one is much more complicated. There should be an `after helm` hook that will set the field after the successful deploy.

**Comment by nabokihms** [comment]
Use CEL to show a human-readable status instead of integers.

**Comment by yalosev** [comment]
Do we really need `lastProcessedResourceVersion` field? We have a common `metadata.resourceVersion` field which we can use

**Comment by yalosev** [comment]
Add `lastReactedResourceVersion` when an object is getting into a snapshot
`lastProcessedResourceVersion` could be realized via `OnAfterHelm` hook but this hook have to be done with some generic code in the `go_lib`
