### ISSUE TITLE
[deckhouse] Expose Deckhouse API

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4527]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse has an API that provides info on the state of its internal storage, queues, preflight patches, and more.
This API is now exposed via the Unix socket and can be accessed with the deckhouse-controller CLI.

### Proposed Solution

Made it publically available and protected with a kube-rbac-proxy. By exposing API, we can provide users with more info, e.g., in UI.

**Comment by yalosev** [comment]
1. Move metrics port listener (9650) in the shell-operator to the localhost (optionally, via the env variable)
2. Add debug endpoints (/debug) to this listener
3. Proxy the requests via the kube-rbac-proxy
