### ISSUE TITLE
AWS Cloud Provider - ability to enable IMDSv2 only for metadata access

### ISSUE THREAD

**Issue by artem-eliseyev** [deckhouse/deckhouse#4547]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Instance Metadata Service (IMDS) provides a convenient way to access metadata available for a running Amazon EC2 instance such as hostname, network configuration, associated security groups, and so on. The EC2 instances that allow IMDSv1 are exposed to Server Side Request Forgery (SSRF) attacks, which could allow theft of IAM roles. IMDSv2 uses session-oriented requests to mitigate several types of vulnerabilities that could be used to attempt to access the IMDS, protecting against malicious activities such as SSRF attacks.

### Proposed Solution

Implement changes to AWSInstanceClasses.deckhouse.io to allow enable this feature. At the moment, Amazon allow enable IDMSv2-only mode while starting of a new machine or manually for a running instance.

**Comment by konstantin-axenov** [comment]
Will be resolved by https://github.com/deckhouse/deckhouse/issues/4583
