### ISSUE TITLE
[e2e] Add more OS to test in the air gapped environments

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#4572]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Our clients use a wide range of OSs in air-gapped environments.

### Proposed Solution

Add all the supported OSs to e2e tests in the air-gapped environments.

**Comment by name212** [comment]
I think we need design first here

**Comment by name212** [comment]
- We need to add one more node to static layout in terraform https://github.com/deckhouse/deckhouse/blob/main/testing/cloud_layouts/Static/infra.tpl.tf
- For each node let assign its own  OS, we need to use `Astra`, `Redos` and `AltLinux`
- Upload `Redos` and `AltLinux` images into openstack. Astra already exists
- In test script, we need join nodes in the cluster (one node will be master node)
- Verify that all nodes were joined in the cluster and in the Ready and `Uptodate` state.
