### ISSUE TITLE
[deckhouse-web] Rename module

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4584]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The name does not speak for itself and is misleading.

### Proposed Solution

Use something like `docs`, or `deckhouse-docs`, `deckhouse-doc`, `documentation`.

**Comment by konstantin-axenov** [comment]
@z9r5 Which name do you prefer?

**Comment by z9r5** [comment]
I vote for the `documentation`

**Comment by z9r5** [comment]
What about web domain?  The current domain (deckhouse.) does not hint at documentation, IMHO
