### ISSUE TITLE
[cni-cilium] Investigate cilium BGP capabilities

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4586]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Investigate wether cilium could be a metallb replacement 
https://nicovibert.com/2022/07/21/bgp-with-cilium/

### Proposed Solution

R&D.

### Additional Information

Related issue
https://github.com/deckhouse/deckhouse/issues/4366

**Comment by apolovov** [comment]
It works, but we don't have plans to get rid of metallb module.
