### ISSUE TITLE
smoke-mini prevents cluster-autoscaler downscale

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#46]
Smoke mini is a StatefulSet (5 statefulsets). And if you have <= 5 nodes statefulsets rollout on each node and block it.
Cluster autoscaler tries to remove the empty node but can't evict smoke-mini from it and abandon the downscale.

**Comment by shvgn** [comment]
Should we add more conditions to decide the node is not schedulable? If a node is not schedulable from the perspective of the hook, it removes pods from the node.

https://github.com/deckhouse/deckhouse/blob/main/modules/500-upmeter/hooks/smokemini/internal/snapshot/node.go#L61
