### ISSUE TITLE
[monitoring-kubernetes] Add alert about high TCP memory usage

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#4605]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases, applications on the node begin to work incorrectly.
Symptoms: high CPU usage, unable to connect via TCP to other services.

``dmesg`` shows:
```
TCP: out of memory -- consider tuning tcp_mem
```

The `Node/Sockstat Memory Size` graph shows extremely high memory usage.

After increasing each component of the vector `net.ipv4.tcp_mem` the problem goes away.

The source of the problem is the client application. After restarting, memory consumption in the `Node/Sockstat Memory Size` graph drops to the minimum values.

We should alert client to a possible node problem when TCP-stack memory consumption reaches any threshold.

### Proposed Solution

Node exporter exports a metric of `node_sockstat_TCP_mem_bytes` total memory usage.
Unfortunately, I couldn't find any metrics that could indicate the limits specified in `net.ipv4.tcp_mem`.
So I have to patch node exporter or write my own exporter like [this](https://github.com/deckhouse/deckhouse/tree/main/modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter)

**Comment by name212** [comment]
File in /proc with `net.ipv4.tcp_mem` settings:

`/proc/sys/net/ipv4/tcp_mem`

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
