### ISSUE TITLE
[operator-trivy] Remove duplicate CVEs for container replicas

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#4656]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44.4

### Expected Behavior

CVEs get duplicated by the count of vulnerable pod/container replicas.

### Actual Behavior

CVEs get multiplied by the count of replicas since we use an incorrect partial grouping:

```
sum(trivy_image_vulnerabilities{severity="Critical", namespace=~"$namespace"})
```

**Comment by EvgenySamoylov** [comment]
Doesn't it duplicate #4444?

**Comment by zuzzas** [comment]
It does!
