### ISSUE TITLE
[node-manager] Cluster-autoscaler is partially broken for kubernetes 1.25+

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#4662]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.0

### Expected Behavior

Cluster-autoscaler works without errors

### Actual Behavior

`policy/v1beta1/PodDisruptionBudget` was remove in the kubernetes 1.25. Cluster-autoscaler in these clusters is reporting about errors:
```
I0516 15:15:08.541556       1 scale_down.go:917] No candidates for scale down
W0516 15:15:15.068278       1 reflector.go:324] github.com/gardener/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
E0516 15:15:15.068312       1 reflector.go:138] github.com/gardener/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309: Failed to watch *v1beta1.PodDisruptionBudget: failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
```

Also, some functions are not working, at least I have found that priorities backoff is not working ( It doesn't fallback to the ng with lower priority)

### Additional Information

I think we have to bump cluster-autoscaler version to the [1.26.2](https://github.com/gardener/autoscaler/releases/tag/v1.26.2) and then check its workability

**Comment by vitaliy-sn** [comment]
![image](https://github.com/deckhouse/deckhouse/assets/32643620/6c2dfe4c-66da-497b-a649-87282648c525)
