### ISSUE TITLE
[user-authz] Conduct an audit of the rights of different roles

### ISSUE THREAD

**Issue by alex123012** [deckhouse/deckhouse#4676]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is necessary to think over and rework the rights for different [roles of module](https://github.com/deckhouse/deckhouse/blob/main/modules/140-user-authz/templates/cluster-roles.yaml), as well as to revise the role model as a whole

### Proposed Solution

Rework [`ClusterRoles` for user-authz module](https://github.com/deckhouse/deckhouse/blob/main/modules/140-user-authz/templates/cluster-roles.yaml)

**Comment by raabdullaev** [comment]
Looks like tasks from RBAC 2.0.
