### ISSUE TITLE
[flant-integration] Create dashboards for controllers resource consumption

### ISSUE THREAD

**Issue by alex123012** [deckhouse/deckhouse#4679]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

After adding [metrics for controller metric consumption](https://github.com/deckhouse/deckhouse/pull/4352) we need to create dashboards to visualize them. 

### Proposed Solution

Create dashboards:)

**Comment by raabdullaev** [comment]
Done in DOP dashboard.
