### ISSUE TITLE
[flant-integration] Move to external-modules

### ISSUE THREAD

**Issue by alex123012** [deckhouse/deckhouse#4680]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We can make this module pluggable and and exclude it from the main deckhouse modules.

### Proposed Solution

Rewrite module and make it an external-module

**Comment by alex123012** [comment]
I think, this can bel related #4660

**Comment by yalosev** [comment]
Rewrite, according to the [manual](https://fox.flant.com/deckhouse/docs-external-modules)
