### ISSUE TITLE
[descheduler] Pod stuck in the CrashLoopBackOff state when a cluster size is 0 or 1

### ISSUE THREAD

**Issue by asviel** [deckhouse/deckhouse#4703]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.9

### Expected Behavior

I want descheduler module not to run at all if I have one node.

### Actual Behavior

The `descheduler` module runs and gets stuck in the CrashLoopBackOff state with a quite logical error message. As an admin/user, CrashLoopBackOffs scare me.

### Steps To Reproduce

0. **Edition:** EE, **OS:** AlterOS 7.5
1. Follow the installation steps for bare metal
2. Use default config
3. Untaint the only master node

### Logs

```shell
{"ts":1684742211918.2808,"msg":"The cluster size is 0 or 1 meaning eviction causes service disruption or degradation. So aborting..","v":1}
```

**Comment by konstantin-axenov** [comment]
We lost [previous solution](https://github.com/deckhouse/deckhouse/blob/32ba11b15b0bc1edcae12786d2dec7ae857b0cfb/modules/400-descheduler/hooks/calc_deployment_replicas.go#L42-L52) during refactoring.
