### ISSUE TITLE
[deckhouse] get rid of deprecated cm deckhouse

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#4705]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Old ConfigMap `deckhouse` is not used anymore but it presence confuses users.

### Proposed Solution

- Remove `deckhouse` ConfigMap [creation](https://github.com/deckhouse/deckhouse/blob/main/dhctl/pkg/kubernetes/actions/deckhouse/install.go#L175) from dhctl
- Add migration hook to remove deprecated `deckhouse` cm
- Check hooks and remove bindings to the cm `deckhouse`

**Comment by RomanenkoDenys** [comment]
1. Add migration hook to remove deprecated deckhouse cm
2. Check hooks and remove bindings to the cm deckhouse
3. Remove deckhouse ConfigMap from dhctl after successful bootstrap.
4.
