### ISSUE TITLE
[flant-integration] Malformed URL schema in madison data on registration

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#4723]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

grafana url in the module flant-integration  is not added correctly url schema is no longer exhibited correctly 
So now the link for prometheus object in madison consists of certmanager:\/\/grafanaurl 
it used to be https:\/\/grafanaurl 

### Proposed Solution

In the old patch they removed the block with url schema parsing, from which https was retrieved
https://github.com/deckhouse/deckhouse/pull/2133/files#diff-28a84256e7acbd2dd7b08ff6649896d2e1de326f1ce5362989face1fd5b67435L114

**Comment by yalosev** [comment]
1. I guess if snapshot not found, we have to return `http` [here](https://github.com/deckhouse/deckhouse/blob/main/ee/modules/600-flant-integration/hooks/madison/registration.go#L199)
2. Value is set to the secret with the help of helm-lib - https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/prometheus-https-mode-secret.yaml#L10
3. [this function](https://github.com/deckhouse/lib-helm/blob/main/charts/helm_lib/templates/_module_https.tpl#L3) looks good but maybe we have to check this and write some tests for it with the input values based on module and global values
