### ISSUE TITLE
[Feature gates] Add StatefulSetAutoDeletePVC feature gate (and maybe add possibility to enable some feature gates in cluster)

### ISSUE THREAD

**Issue by duckhawk** [deckhouse/deckhouse#4796]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

One of our clients wants to use this feature

### Proposed Solution

Enable this feature for all setups, or make a setting to change feature gates, enabled in cluster

**Comment by konstantin-axenov** [comment]
We don't want Alpha features to be enabled in Deckhouse clusters. This feature will be enabled in Beta or in GA when this feature is stable enough and can't have influence on working cluster.
