### ISSUE TITLE
[monitoring] Set appropriate protocol for links on grafana start page in "Web Interfaces"

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4844]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases http port does not listen. it uses https for display.

### Proposed Solution

```js
var currentProtocol = window.location.protocol;
console.log(currentProtocol);
```
or pass it through a request to prometheus

**Comment by konstantin-axenov** [comment]
![image](https://github.com/deckhouse/deckhouse/assets/14013249/089ea737-d468-466a-bc55-4e3ee0d1240b)
