### ISSUE TITLE
Collect all the bug related info with one command and send it to vendor for troubleshooting

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#487]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's not a rare case that we set up Deckhouse on the infrastructure we don't have any access to. We still need to support that installation though. Troubleshooting might be a nightmare in the case. We need to provide customers with the possible easiest way to collect all the bug-related info from the different cluster sources and provide it to us for further investigation. 

### Proposed Solution

TBD

**Comment by shvgn** [comment]
If deckhouse had GUI, we could provide easily accessable button for clients. E.g. "Download system report" resulting in .zip file with YAMLs.

**Comment by kvaps** [comment]
`dhctl debug-report` would be really nice 👌

**Comment by EvgenySamoylov** [comment]
Looks like it's already addressed here: #1787. Closing.
