### ISSUE TITLE
[150-user-authn] the dex-tls certificate was generated for the old domain

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#4881]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44

### Expected Behavior

certificate renewal works every time the publicDomainTemplate is changed.

### Actual Behavior

With low probability the certificate update does not happen. other ingress d8-* are updated and so are their secrets.

### Steps To Reproduce

1. When testing on a test cluster deployed in e2e, this behavior could not be reproduced.

### Additional Information

https://github.com/deckhouse/deckhouse/blame/d5876c4f111128b490727d174cb7ffbedd795f78/modules/150-user-authn/hooks/order_dex_tls_certificate.go#LL30C3-L30C42
https://t.me/deckhouse_ru/21217
https://t.me/deckhouse_ru/21484

**Comment by konstantin-axenov** [comment]
We need to wait until the next time when this problem is reproduced somewhere.

**Comment by alex123012** [comment]
the problem is reproduced:
https://t.me/deckhouse_ru/23120
