### ISSUE TITLE
[deckhouse][docs] Add information than running Deckhouse on CloudEphemeral nodes isn't correct

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#4890]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.11

### Expected Behavior

A Machines is always bootstrapped correctly.

### Actual Behavior

If Deckhouse is not working (for example, when it's scheduled on a Node that still needs to be bootstrapped), a Node will never get bootstrapped, since Deckhouse generates the bootstrap token.

**Comment by konstantin-axenov** [comment]
Deckhouse is not working was the real cause of the problem. We dramatically optimized deckhouse-controller, so now it doesn't influence control-plane nodes. And soon Deckhouse will work in [HA mode](https://github.com/deckhouse/deckhouse/issues/4163).

**Comment by konstantin-axenov** [comment]
@z9r5 We need to add in the documentation that it's not correct to launch Deckhouse on CloudEphemeral nodes and if there is only one node in NodeGroup.

**Comment by z9r5** [comment]
Done in #4905
