### ISSUE TITLE
[d8-pull] need to check the version of docker so that the --pull key is available

### ISSUE THREAD

**Issue by sadon** [deckhouse/deckhouse#4912]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.45.5

### Expected Behavior

downloaded images

### Actual Behavior
Env: Clean CentOS 7
1. Script use outdated docker flags --pull=allways
 ![image](https://github.com/deckhouse/deckhouse/assets/2854508/15b8e4a2-3a8d-4551-95ad-1b90ee3f8bd3)
2. Cant upload scopeo image
![image](https://github.com/deckhouse/deckhouse/assets/2854508/e1abc799-e245-4118-9601-642369484cb3)
3. Next, During script run I've got messages: scopeo not found
![image](https://github.com/deckhouse/deckhouse/assets/2854508/8ae9e446-ce41-451e-87c6-d57efb105a30)

### Steps To Reproduce

run the script with flags:
`./d8-pull.sh --release v1.45.5 --edition ce --output-dir ./dh-1.45/`

### Additional Information

It is dufficult to migrate script inside a docker container because it uses docker socket inside themself.

So, my suggetions here:
0) Make the script runnable

1) Create d8-pull/d8-push container 
2) Integrate it with jq, scopeo etc, put all dependencies inside the container
3) create docker-compose.yaml with shared folder where will be located downloaded containers' files

**Comment by sadon** [comment]
Env: 
1. Windows 
![image](https://github.com/deckhouse/deckhouse/assets/2854508/11df4d06-d4d9-4ed9-bfde-ddc900d81cc7)
$ docker -v
Docker version 20.10.24, build 297e128
флага --pull нет

2. docker (default in CentOS 7)
![image](https://github.com/deckhouse/deckhouse/assets/2854508/68e4513c-b0d4-44a3-818d-dd961aef1c39)
флага --pull нет

**Comment by yalosev** [comment]
Don't think it's actual. d8-pull is going to be [rewritten in Go](https://github.com/deckhouse/deckhouse/issues/4954)
