### ISSUE TITLE
[common] Add commonName to all deckhouse certificate

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#4926]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Request from internal client 

### Proposed Solution

Add `commonName` field equals to all certificates.
For example, https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/grafana/ingress.yaml#L82

**Comment by name212** [comment]
https://github.com/deckhouse/deckhouse/issues/772

**Comment by RomanenkoDenys** [comment]
We need to add commonName field with first array entry of dnsNames to all Certificates resources. Also we should check that entry is not longer than 64 symbols (https://github.com/cert-manager/cert-manager/issues/1462). I think we should add this check to the helm_lib_module_public_domain helm helper.
