### ISSUE TITLE
[operator-trivy] Add CA to operator scan jobs

### ISSUE THREAD

**Issue by alex123012** [deckhouse/deckhouse#4950]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In the isolated environments with private container registry with self-signed CA operator trivy can't run scan jobs because it can't pull trivy-db:
```text
2023-06-16T06:19:56.708Z        INFO    Need to update DB
2023-06-16T06:19:56.708Z        INFO    DB Repository: custom.registry.com/deckhouse/security/trivy-db
2023-06-16T06:19:56.708Z        INFO    Downloading DB...
2023-06-16T06:19:56.742Z        FATAL   init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
        * Get "https://custom.registry.com/v2/": x509: certificate signed by unknown authority
```

### Proposed Solution

1. The first option is to add `--insecure` flag for http registry [in this func](https://github.com/aquasecurity/trivy-operator/blob/main/pkg/plugins/trivy/plugin.go#L1096) for trivy command (refer to `trivy --help`)
1. The second option is to add [custom CA to trusted certificates](https://stackoverflow.com/a/67232164) in trivy alpine image (for example in `initContainers` or in entrypoint in [operator-trivy deployment](https://github.com/deckhouse/deckhouse/blob/main/ee/modules/500-operator-trivy/templates/deployment.yaml#L31)).
1. The third option is to add support for trivy-db download with custom CA in [trivy](https://github.com/aquasecurity/trivy) and then add customization of scan jobs in [trivy-operator](https://github.com/aquasecurity/trivy-operator) (preferable option)

**Comment by yalosev** [comment]
Well, Have to try this in the reverse order - 3 -> 2 -> 1
