### ISSUE TITLE
[prometheus] Make lookback delta equal to x2 scrape interval for main

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#4951]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The lookback delta (`--query. lookback-delta`) in Prometheus equals 5 minutes by default.
If there is no metric on the next scrape, Prometeus will still return the value for it for 5 minutes.

It leads to the evaluation failure of rules (both recording and alerting).

P.S. Only the main Prometheus is affected by the problem.

### Proposed Solution

Consider lowering the delta. As per VictoriaMetrics suggestion, using the 2x scrape interval is sane.

### Additional Information

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/209#issuecomment-542345971

**Comment by yalosev** [comment]
According to [this](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.QuerySpec) documentation
we have to add parameter [here](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/prometheus/prometheus.yaml#L61)

Scrape interval is set [here](https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/templates/prometheus/prometheus.yaml#L134). Have to double this value
