### ISSUE TITLE
[chore] rewrite d8-pull.sh / d8-push.sh scripts with Go

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#4954]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to have more predictable and useful CLI tool without external dependencies

### Proposed Solution

Realize CLI tool with [skopeo](https://github.com/containers/skopeo) inside. We want to have 3 features:
- Pull images to the directory (tar archive)
- Push images from the directory to the desired repository
- Stream images from a source repository to a destination repository
    - extra feature: continue synchronization on abort/interrupt

Details could be taken from [openshift tool](https://docs.openshift.com/container-platform/4.10/installing/disconnected_install/installing-mirroring-disconnected.html)

### Additional Information

I see something like
```bash
dhctl mirror pull --release=v1.45.5 --edition=ce --output-dir=./ 
```

```bash
dhctl mirror push --user=foo --password=bar --from=./v1.45.5-ce.tar.gz my.registry.com/deckhouse
```

```bash
dhctl mirror sync registry.deckhouse.io/deckhouse my-company.registry.com/deckhouse --dest-user=foo --dest-password=bar
```

or just
```bash
dhctl mirror <source-repo> <target-repo> [options]
```

**Comment by konstantin-axenov** [comment]
We already distribute dhctl as docker image, so it seems the best option to add mirror command into it.
