### ISSUE TITLE
D8PrometheusLongtermFederationTargetDown alert not working properly

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#4972]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.41

### Expected Behavior

D8PrometheusLongtermFederationTargetDown should fire if prometheus longterm can not scrape main prometheus.

### Actual Behavior

Have next situation.

Longterm prometheus cannot scrape main prometheus with timeout error (we have very large prometheus).
But we don't recieve D8PrometheusLongtermFederationTargetDown alert.
In the prometheus board we see that alert begin fire in pending status periodically:

![Screenshot from 2023-06-20 12-57-03](https://github.com/deckhouse/deckhouse/assets/30695496/4aed9680-fab1-48b7-9874-1ac03929f83a)

It do not fire because we have 10 min pending interval

Periodicaly we don't have data for  `longterm_federate_scrape_successful` and `up{job="federate"}` metrics for last time (because in this time longterm prometheus is in scraping, i think)

![Screenshot from 2023-06-20 13-14-09](https://github.com/deckhouse/deckhouse/assets/30695496/e88b4bc7-480d-44c0-b0d0-558127d8d5ed)

![Screenshot from 2023-06-20 12-52-38](https://github.com/deckhouse/deckhouse/assets/30695496/e3c8fa1d-dd28-4b89-b5b4-b41cb5e1a216)

Probably solution
Use next query
`scalar(longterm_federate_scrape_successful == 0 OR on() vector(0))`

or better

`max_over_time(longterm_federate_scrape_successful[10m]) == 0`

**Comment by konstantin-axenov** [comment]
Seems best
```
max_over_time(longterm_federate_scrape_successful[10m]) == 0
```
