### ISSUE TITLE
Add additional fields to D8KruiseControllerMalfunctioning

### ISSUE THREAD

**Issue by SpecialForce3331** [deckhouse/deckhouse#4976]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

At now we see only this fields:
`
trigger | = | D8KruiseControllerMalfunctioning,D8KruiseControllerPodIsRestartingTooOften
-- | -- | --
kubernetes | = | stage
prometheus | = | deckhouse
tier | = | cluster
`

### Proposed Solution

Need to add namespace, controller name, pod name fields.

**Comment by konstantin-axenov** [comment]
Add more info how to solve problem, e.g. check logs.

**Comment by miklezzzz** [comment]
@konstantin-axenov well, I will added some useful cmds to get logs but at the moment I'm not sure we can clearly state that we know how to solve controller's problems apart from reading logs in hope there are some meaningful errors there.

**Comment by miklezzzz** [comment]
@konstantin-axenov review please https://github.com/deckhouse/deckhouse/pull/4995
