### ISSUE TITLE
Deckhouse pod init container Init-external-modules terminates with an error

### ISSUE THREAD

**Issue by verdel** [deckhouse/deckhouse#5031]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1-45-11

### Expected Behavior

Launching the deckhouse container without errors

### Actual Behavior

Init contaner `init-external-modules` stop with error in log:
```
chown: /deckhouse/external-modules: Operation not permitted
```

### Additional Information

In the init container of deckhouse pod, the launch command looks like this:
```
command: ['sh', '-c', 'mkdir -p /deckhouse/external-modules/modules && chown -h 65534 /deckhouse/external-modules /deckhouse/external-modules/modules && chmod 0700 /deckhouse/external-modules /deckhouse/external-modules/modules']
```
As I understand it, it is impossible to change the owner and rights to the volume mount point.
Perhaps the startup command should look like this:
```
command: ['sh', '-c', 'mkdir -p /deckhouse/external-modules/modules && chown -h 65534 /deckhouse/external-modules/modules && chmod 0700 /deckhouse/external-modules/modules']
```

**Comment by yalosev** [comment]
@verdel could you give a bit more details, please?
Cloud-provider/bare-metal, which OS do you use?
Docker/Containerd and `ps aux | grep "containerd\|docker"` command output

**Comment by verdel** [comment]
Deckhouse deployed in yandex.cloud managed kubernetes cluster `v1.24.8`. They use `Ubuntu 20.04.5 LTS` for worker nodes.

Information about docker:
```shell
> docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:56 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by miklezzzz** [comment]
@verdel Hello! couldn't reproduce the issue with a fresh 1.24.8 yandex managed k8s.
![image](https://github.com/deckhouse/deckhouse/assets/41360396/3d4b572b-15d3-422e-8b57-1e72164babfe)
Could it happen there were some cluster-related peculiarities?
If so, could you please check once again and provide some additional info if the problem persists?

**Comment by verdel** [comment]
I apologize for wasting your time. The problem was really on our side. For some reason the container `init-external-modules` in the pod `deckhouse` was missing  [securityContext](https://github.com/deckhouse/deckhouse/blob/b85e225961e804da5a3925558fd2572890595764/modules/002-deckhouse/templates/deployment.yaml#L99-L101).

Thank you again so much for the wonderful product.
