### ISSUE TITLE
Installation on the bare metal server using dhctl is performed with error

### ISSUE THREAD

**Issue by Isteb4k** [deckhouse/deckhouse#5048]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.10

### Expected Behavior

Installation on the bare metal server using the command below is performed without errors.
```
dhctl bootstrap --ssh-user=<username> --ssh-host=<master_ip> --ssh-agent-private-keys=/tmp/.ssh/id_rsa \
  --config=/config.yml
```

### Actual Behavior

An error occurred in the step _070_install_control_plane.sh_:

> │ │ Cannot remove node.kubernetes.io/exclude-from-external-load-balancers label from node
> │ │ ++ exit 1

### Steps To Reproduce

1. Run cmd:
```
dhctl bootstrap --ssh-user=<username> --ssh-host=<master_ip> --ssh-agent-private-keys=/tmp/.ssh/id_rsa \
  --config=/config.yml
```
2. Wait the error:
> │ │ Cannot remove [node.kubernetes.io/exclude-from-external-load-balancers](http://node.kubernetes.io/exclude-from-external-load-balancers) label from node
> │ │ ++ exit 1

### Additional Information

Step _070_install_control_plane.sh_  cannot be executed because _dhctl bootstrap_ executes this command: `bb-kubectl --kubeconfig=/etc/kubernetes/admin.conf label node "$(hostname)" node.kubernetes.io/exclude-from-external-load-balancers-`

$(hostname) here is `Ubuntu-2204-jammy-amd64-base`, but the node name is `ubuntu-2204-jammy-amd64-base` (lower case)

Since the name is case-sensitive, an error occurs in the process

### Logs

```shell
│ │ ++ bb-kubectl --kubeconfig=/etc/kubernetes/admin.conf label node Ubuntu-2204-jammy-amd64-base                     ↵
│ │ node.kubernetes.io/exclude-from-external-load-balancers-
│ │ ++ kubectl --request-timeout 60s --kubeconfig=/etc/kubernetes/admin.conf label node Ubuntu-2204-jammy-amd64-base            ↵
│ │ node.kubernetes.io/exclude-from-external-load-balancers-
│ │ Error from server (NotFound): nodes “Ubuntu-2204-jammy-amd64-base” not found
│ │ ++ echo ‘Cannot remove node.kubernetes.io/exclude-from-external-load-balancers label from node’
│ │ Cannot remove node.kubernetes.io/exclude-from-external-load-balancers label from node
│ │ ++ exit 1
```

**Comment by name212** [comment]
it is part of https://github.com/deckhouse/deckhouse/issues/4896
