### ISSUE TITLE
[preflight-check] Check the compatibility of the dhctl installer versions and the Deckhouse version being installed

### ISSUE THREAD

**Issue by aleksey-su** [deckhouse/deckhouse#5073]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Preventing failures before bootstrap execution

### Proposed Solution

Before performing bootstrap, check the compatibility of the dhctl installer versions and the Deckhouse version being installed

### Additional Information

* use version Deckhouse from the file /deckhouse/version for deployment. May be, use the golang compile time constants for setting deckhouse version ```go build -ldflags "-X config.Version=1.0.0" ...```
* additionally, we can check the hash sum SHA256 of the Deckhouse image
* additionally, we may need to move the releaseChannel installation from configOverrides to the last bootstrap step.

**Comment by konstantin-axenov** [comment]
Dhctl version matches deckhouse version being installed. Parameter releaseChannel is just copied to config.
