### ISSUE TITLE
[preflight-check] checking for the necessary images in Registry

### ISSUE THREAD

**Issue by aleksey-su** [deckhouse/deckhouse#5078]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Preventing failures

### Proposed Solution

Before performing bootstrap, check for the necessary images in Registry

**Comment by konstantin-axenov** [comment]
dhctl should only check that required deckhouse controller image exists. Other images are checked by deckhouse itself. Check https://github.com/deckhouse/deckhouse/issues/5098

**Comment by raabdullaev** [comment]
Not relevant.
