### ISSUE TITLE
[bootstrap] Cleaning up the previous Deckhouse installation

### ISSUE THREAD

**Issue by aleksey-su** [deckhouse/deckhouse#5079]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Preventing failures before bootstrap execution

### Proposed Solution

During installation, create a cleaningup.sh script on the server and if this file is found during the reinstallation, suggest cleaning the previous Deckhouse installation.

**Comment by konstantin-axenov** [comment]
1. Create cleanup script on nodes.
2. Automatically run cleanup on bootstrap failures.
