### ISSUE TITLE
[deckhouse] Check required images in registry

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5098]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We have to check if registry has all necessary images when Deckhouse uses registry other than registry.deckhouse.io. We can't control consistency of internal registries, especially in air-gapped environments. When deckhouse release is updated and some images are missing, it can lead to downtimes.

### Proposed Solution

Add global hook that checks images availability before release update or first deckhouse installation in the cluster.
- WARNING: If image is missing but isn't required for any module
- ERROR: If image is missing and required. Stop deckhouse update or installation
- Check all images, show report about all images. Consider adding events in d8-system namespace.

**Comment by yalosev** [comment]
1. Create list of all images (from global values. like: `deckhouse-controller global values -o json | jq .global.modulesImages`)
2. Get registry from global values (`deckhouse-controller global values -o json | jq .global.modulesImages.registry`) and initialize client
3. Make HEAD requests, mark unavailable images with specified modules
4. Get list of enabled modules
5. Check intersection between enabled modules and absent modules, if anything found - return with error

Add logs, event, metrics

**Comment by raabdullaev** [comment]
Described in #7938 - https://deckhouse.io/documentation/v1/deckhouse-faq.html#manually-uploading-images-to-an-air-gapped-registry
