### ISSUE TITLE
[deckhouse] Release update delay

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5147]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse has feature to control notifications about updates. There is parameter [minimalNotificationTime](https://deckhouse.io/documentation/v1/modules/002-deckhouse/configuration.html#parameters-update-notification-minimalnotificationtime). But some users use pull model to get information about releases. They can't be sure that they get information about release and this information will be in their internal system for required period of time.

There is a client with 50+ clusters. It is necessary to get information about the upcoming release and notify users a week before in advance that there is a new release in the cluster that will be applied during the upgrade window.

### Proposed Solution

- Openapi spec allows setting `minimalNotificationTime` without configuring notification webhook. Check that everything works as expected
- Update the docs

**Comment by yalosev** [comment]
1. Have to set [this](https://github.com/deckhouse/deckhouse/blob/main/modules/002-deckhouse/hooks/internal/updater/updater.go#L130-L142) under the `if condition` - if webhookURL is set
2. Also pay attention [here](https://github.com/deckhouse/deckhouse/blob/main/modules/002-deckhouse/hooks/internal/updater/updater.go#L111). Have to remove ManualMode condition
3. Probably we have to add some event about upcoming release but don' think that anyone can see it
4. Update the docs



Task seems easy but the hard part here - the testing. Simplest one would be add unit tests, like [here](https://github.com/deckhouse/deckhouse/blob/main/modules/002-deckhouse/hooks/update_deckhouse_image_test.go#L526)
