### ISSUE TITLE
[user-authz] Add possibility to add custom AccessLevel and use it in AuthorizationRule

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#5154]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It gives more flexibility to client if exists possibility to add custom AccessLevel and use it in AuthorizationRule. Now in AuthorizationRule we can use accessLevel only with allowed values: User, PrivilegedUser, Editor, Admin

### Proposed Solution

1. Add possibility to add custom AccessLevel
2. Remove validation for field spec.accessLevel in AuthorizationRule for only allowed values

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
This issue will be solved in RBAC 2.0.
