### ISSUE TITLE
[dhctl] Disable deckhouse logs if bootstrap was successful 

### ISSUE THREAD

**Issue by alex123012** [deckhouse/deckhouse#5163]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes errors appear in the deckhouse pod during the cluster bootstrap, which disappear over time. This confuses the engineer, despite the successful start of the cluster.

### Proposed Solution

Disable deckhouse logs if the cluster bootstrap was successful. Show them only if the initial bootstrap fails (something like "stacktrace").

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by name212** [comment]
Closed by #8281
