### ISSUE TITLE
[deckhouse] Support for secured registry in `.local` domain

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5187]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47

### Expected Behavior

Deckhouse works with registries that have domain `.local`.

### Actual Behavior

If registry has `.local` domain, then request is automatically changed from https to http.
```
status: "HookError: 002-deckhouse/hooks/check_deckhouse_release.go: module hook
    '002-deckhouse/hooks/check_deckhouse_release.go' failed: GET http://my-registry.local:5000/v2/:
    unexpected status code 400 Bad Request: <html>\r\n<head><title>400 The plain HTTP
    request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad
    Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>nginx/1.16.1</center>\r
```

**Comment by unreturned** [comment]
If registry have address from private address pool it's also forces the http protocol
https://github.com/google/go-containerregistry/blob/a0658aa1d0cc7a7f1bcc4a3af9155335b6943f40/pkg/name/registry.go#L65
https://github.com/google/go-containerregistry/blob/a0658aa1d0cc7a7f1bcc4a3af9155335b6943f40/pkg/name/registry.go#L85

It's normal situation, that in closed environment we have own CA that issued certificates for `.local` domains with IP SANs (that from private pool)

Looks like we need avoid
```
	if r.isRFC1918() {
		return "http"
	}

	if reLocal.MatchString(r.Name()) {
		return "http"
	}
```
from https://github.com/google/go-containerregistry/blob/a0658aa1d0cc7a7f1bcc4a3af9155335b6943f40/pkg/name/registry.go#L81

**Comment by unreturned** [comment]
Maybe this issue will be suppressed by https://github.com/deckhouse/deckhouse/issues/8026
