### ISSUE TITLE
Cluster-autoscaler cannot delete pod from deployment with replicas=1

### ISSUE THREAD

**Issue by VadimDobryninFlant** [deckhouse/deckhouse#5191]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Cluster-autoscaler cannot delete pod from deployment with replicas=1, even it is the only one pod on the node.

### Proposed Solution

Set --min-replica-count=0 for nodegroup can solve this situation.

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1689245001110089

_No response_

**Comment by konstantin-axenov** [comment]
Can we solve this problem with descheduler?

**Comment by raabdullaev** [comment]
It works like this by design.
