### ISSUE TITLE
[ingress-nginx] hpa does not scaling nodes

### ISSUE THREAD

**Issue by alexey-demyanov** [deckhouse/deckhouse#5192]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.11, ingress-nginx: 1.1

### Expected Behavior

after cpu utilization on node reaches 50%, new front node is going to be ordered

### Actual Behavior

nothing is happening, and ingress-controllers are working slowly

metrics are taken from ds but there are also other parasitic loads on the nodes that are not taken into account in the metrics.

### Additional Information
https://flant.slack.com/archives/CML93AWG2/p1689241695814089

_No response_

**Comment by alexey-gavrilov-flant** [comment]
1. You can add a value control for fine control of hpa. https://github.com/deckhouse/deckhouse/blob/cd841eb70994e251205fa8230999febf643075c9/modules/402-ingress-nginx/templates/controller/hpa.yaml#L45

2. And also add a metric to hpa that will look at the load of the nodes on which the controller is running.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
This problem is not relevant for now.
