### ISSUE TITLE
[deckhouse] deckhouse-config-webhook does not migrate with dh

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5196]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47.4

### Expected Behavior

will roll over when dh is ready

### Actual Behavior

does not track the situation when dh restarts on another master and deckhouse-config-webhook stays on the old node even though they share the same mount point.

### Steps To Reproduce

1. dh scale 0
2. cordon old master
3. dh scale 1

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1689256390282559

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Resolved in https://github.com/deckhouse/deckhouse/pull/5566.
