### ISSUE TITLE
[Docs] Working directories deckhouse exceptions for Kaspersky

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#5226]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When running, kaspersky overreads and sometimes blocks deckhouse from running
sometimes asks to add deckhouse working directories to the exclusion. 

### Proposed Solution

Add to documentation
Add to Kaspersky Exception list:
Directory assignment
/mnt/kubernetes-data (this directory exists only in cloud installations, when a separate disk is used for etcd)
/var/lib/etcd (etcd database)
/var/lib/deckhouse/ (deckhouse modules dynamically loaded from registry)
/var/lib/upmeter (upmeter database)
/etc/kubernetes (static manifests and pki)
/var/lib/bashible (node configuration files)
/var/lib/containerd (files of images and containers running on the node)
/mnt/vector-data (checkpoints of sent logs)
/var/log/containers (logs of containers when using containerd)
/var/lib/kubelet/ (kubelet configuration files)
master nodes:
/mnt/kubernetes-data (this directory is available only in cloud installations, when a separate disk is used for etcd)
/var/lib/etcd
/var/lib/deckhouse/
/var/lib/upmeter
/etc/kubernetes
/var/lib/bashible
/var/lib/containerd
/mnt/vector-data
/var/log/containers
/var/lib/kubelet/
worker nodes:
/etc/kubernetes
/var/lib/bashible
/var/lib/containerd
/mnt/vector-data
/var/log/containers
/var/lib/kubelet/

**Comment by konstantin-axenov** [comment]
@z9r5 Please, verify this list.

**Comment by qw1mb0** [comment]
It is also necessary to add directories to the exclusion:
**/opt/cni/bin/** - сontains CNI plugin executables;
**/opt/deckhouse/bin/** - сontains all executable files required for Deckhouse to work;
**/var/log/pods/** - contains logs of all Pod containers that are running on this cluster node;
**/etc/cni/** - configuration for the CNI plugin to use. The contents of the directory differ depending on the Deckhouse CNI used in the cluster.
