### ISSUE TITLE
[deckhouse] deckhouse-config-webhook can't start if external-module-manager disabled

### ISSUE THREAD

**Issue by EvgeniiAl** [deckhouse/deckhouse#5227]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47.4 CE

### Expected Behavior

deckhouse-config-webhook successfully started without external-module-manager

### Actual Behavior

deckhouse-config-webhook deployment is stuck in containerCreating status, because /var/lib/deckhouse/external-modules/modules doesn't exist

### Additional Information

deckhouse deployment's initContainter for creation directories is under flag  but deckhouse-config-webhook's volume is not 

https://github.com/deckhouse/deckhouse/blob/3d3ed456a5d3d5b89cad93b7dd9c19d6495c7415/modules/002-deckhouse/templates/deployment.yaml#L93

https://github.com/deckhouse/deckhouse/blob/3d3ed456a5d3d5b89cad93b7dd9c19d6495c7415/modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml#L117a

**Comment by yalosev** [comment]
Surround [volume](https://github.com/deckhouse/deckhouse/blob/main/modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml#L115) and [volume-mount](https://github.com/deckhouse/deckhouse/blob/main/modules/003-deckhouse-config/templates/deckhouse-config-webhook/deployment.yaml#L102) with
```
{{- if (.Values.global.enabledModules | has "external-module-manager") }}
...
{{- end -}}
```
