### ISSUE TITLE
[cloud-provider-yandex] add family_id field to YandexInstanceClass as an alternative to image_id

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5250]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

family_id allows you to specify ubuntu-2204-lts rather than a specific image, which allows you to create updated ubuntu rather than a specific image_id where packages are outdated and have potential vulnerabilities.

### Proposed Solution

add family_id

**Comment by konstantin-axenov** [comment]
This leads to a different node behavior in one node group. This is totally wrong.
