### ISSUE TITLE
[flant-integration] in new clusters empty mc module leads to blocking of main queue

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5251]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.48.1

### Expected Behavior

skip module configuration until the configuration appears in mc

### Actual Behavior

queue stalls on flant-integration

### Steps To Reproduce

1. init cloud cluster ee version
2. add system ng

### Logs

```shell
[a] root@gavrilov-master-0 ~ # k.get.deckhouse.queue.list 
Defaulted container "deckhouse" out of: deckhouse, init-external-modules (init)
Queue 'main': length 140, status: 'sleep after fail for 32s (12s left of 32s delay)'

 1. ModuleHookRun:main:kubernetes:600-flant-integration/hooks/pricing/envs_from_deckhouse_secret.go:deckhouseSecret:OperatorStartup:failures 23:2 errors occurred:
        * cannot apply values patch for module values
        * flantIntegration.kubeall.host is required


 2. ModuleHookRun:main:kubernetes:600-flant-integration/hooks/pricing/envs_from_nodes.go:node:OperatorStartup
 3. ModuleHookRun:main:kubernetes:600-flant-integration/hooks/pricing/envs_from_provider_cluster_configuration_secret.go:providerClusterConfigurationSecret:OperatorStartup
 4. ModuleRun:main:flant-integration:doStartup:OperatorStartup
```

**Comment by konstantin-axenov** [comment]
If the module is enabled, it has to be configured. Disable module explicitly or configure.
