### ISSUE TITLE
[node-manager] Cluster autoscaler can add taints ToBeDeletedByClusterAutoscaler and DeletionCandidateOfClusterAutoscaler for Static or CloudPermanent nodes.

### ISSUE THREAD

**Issue by name212** [deckhouse/deckhouse#5252]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.47

### Expected Behavior

Cluster autoscaler should not add taints ToBeDeletedByClusterAutoscaler and DeletionCandidateOfClusterAutoscaler for Static or CloudPermanent nodes.

### Actual Behavior

Cluster autoscaler is using all nodes (not only provisioned by mcm) for scale down procedure. CA can start deliting procedure (despite the fact that the CA will not be able to remove them) and add next taints
```
    - effect: PreferNoSchedule
      key: DeletionCandidateOfClusterAutoscaler
      value: "1689080276"
    - effect: NoSchedule
      key: ToBeDeletedByClusterAutoscaler
      value: "1689080589"
```

### Steps To Reproduce

1. Up hybrid cluster
2. Add CloudEphemeral nodegroup with minPerZone != maxPerzone (for enabling cluster autoscaller)
3. Add static node group with one node. Node should not have workloads
4. Wait until CA add taints  

### Additional Information

We need to add annotation `"[cluster-autoscaler.kubernetes.io/scale-down-disabled](http://cluster-autoscaler.kubernetes.io/scale-down-disabled)": "true"` for CloudPermaent and Static node in [hook](https://github.com/deckhouse/deckhouse/blob/main/modules/040-node-manager/hooks/handle_node_templates.go)

**Comment by konstantin-axenov** [comment]
Which CA version is affected by this problem? Should we fix CA instead of using annotations?
