### ISSUE TITLE
[tools] expand helm renderer

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5254]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We can create more generic solution for rendering helm templates

### Proposed Solution

1. Rename [this](https://github.com/deckhouse/deckhouse/tree/main/tools/authz_generate_rules_for_roles) package
2. Separate authz render to a function
3. Add function to render other modules. For example @z9r5 have to render [these prom rules](https://github.com/deckhouse/deckhouse/tree/main/modules/340-extended-monitoring/monitoring/prometheus-rules/extended-monitoring)
4. Change [call of this tool](https://github.com/deckhouse/deckhouse/blob/main/tools/generate_docs.go) to specify an argument to render

This tool should be easily expandable and have a first argument to specify, which resource do you want to render

**Comment by z9r5** [comment]
E.g., the tool should help to get alerts (rendered YAML) from [this template](https://github.com/deckhouse/deckhouse/blob/main/modules/340-extended-monitoring/monitoring/prometheus-rules/image-availability/image-checks.tpl).
