### ISSUE TITLE
[upmeter] upmeterhookprobes.deckhouse.io is not scaled to 1

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5264]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.48.2

### Expected Behavior

should remove the extra upmeterhookprobes.deckhouse.io

### Actual Behavior

3 pieces left after switching to single master variant
And also the D8UpmeterTooManyHookProbeObjects alert was triggered

### Steps To Reproduce

1. single master
2. to 3 master
3. to single master

### Logs

```shell
[xxxx] a.gavrilov@xxxxxx-master-0 ~ $ kubectl get upmeterhookprobes.deckhouse.io
NAME       INITED                                 MIRROR                                 AGE
52a443cf   18b572ce-ff9f-4183-9099-69255a3ce836   18b572ce-ff9f-4183-9099-69255a3ce836   613d
ef316bb1   12713dda-d683-4170-b619-5a6d2601f78e   12713dda-d683-4170-b619-5a6d2601f78e   109m
f5a0e30b   0f043d2e-aa87-4af4-b9eb-c3d37917409a   0f043d2e-aa87-4af4-b9eb-c3d37917409a   109m
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
https://github.com/deckhouse/deckhouse/issues/2327
