### ISSUE TITLE
[operator-trivy] Add support for BDU

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5278]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We want to discover problems in containers that are based on various distros, e.g. redos or astra.

### Proposed Solution

Download and prepare trivy database from https://bdu.fstec.ru/files/documents/vulxml.zip

**Comment by yalosev** [comment]
1. Fork trivy-db
2. Add BDU parser
3. Add job for rebuilding the DB
