### ISSUE TITLE
[cloud-provider-aws] Pull ec2_describe_tags binary from the Deckhouse repository

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5300]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

`ec2_tags_binary` is pulled [here](https://github.com/deckhouse/deckhouse/blob/main/candi/cloud-providers/aws/bashible/common-steps/bootstrap-networks.sh.tpl)
Github could be unavailable due to some reasons, it's safer to pull it as any other binaries - from the Deckhouse registry

### Proposed Solution

Put the binary image [here](https://github.com/deckhouse/deckhouse/tree/main/modules/007-registrypackages/images)
Rewrite the script to use prebuilt image

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
