### ISSUE TITLE
[ci] Deploy workflow must fail if an incorrect cooldown time is specified

### ISSUE THREAD

**Issue by z9r5** [deckhouse/deckhouse#5306]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If you specify the wrong time format in the [cooldown](https://github.com/deckhouse/deckhouse/blob/main/.github/workflows/deploy-alpha.yml#L37) workflow parameter, all jobs pass and there is a error in the Deckhouse log, such as:
```
[error][deckhouse] - parse cooldown(ee,ce) error: parsing time "ee,ce" as "2006-01-02T15:04:05Z07:00": cannot parse "ee,ce" as "2006"
```

### Proposed Solution

Deploy workflow must fail if an incorrect time is specified.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
