### ISSUE TITLE
[monitoring] add livenessProbe for node-exporter

### ISSUE THREAD

**Issue by Beastlex** [deckhouse/deckhouse#5312]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes node-exporter stucks. Without livenessProbe client have to recreate pod by hand.
```
# kubectl -n d8-monitoring exec -it node-exporter-7r8wx -- sh
Defaulted container "node-exporter" out of: node-exporter, kubelet-eviction-thresholds-exporter, kube-rbac-proxy
/ # wget -O - http://127.0.0.1:9101/metrics
Connecting to 127.0.0.1:9101 (127.0.0.1:9101)
^C
```

### Proposed Solution

Add tcp or http livenessProbe to node-exporter

**Comment by AlexandrBoltris** [comment]
Additional information. Something happened with `kube-rbac-proxy` container.

```text
2023/07/21 19:52:26 http: proxy error: context canceled
2023/07/21 19:52:49 http: proxy error: context canceled
2023/07/21 19:52:56 http: proxy error: context canceled
2023/07/21 19:53:19 http: proxy error: context canceled
2023/07/21 19:53:26 http: proxy error: context canceled
```
