### ISSUE TITLE
[multitenancy-manager] Reject deletion of a ProjectType if used in Projects

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#5316]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It leads to an error in module rendering:
```
ModuleRun failed in phase ‘CanRunHelm’. Requeue task to retry after delay. Failed count is 6. Error: execution error at (multitenancy-manager/templates/user-resources-templates.yaml:143:133): No ProjectType with name ‘test-project-type’ found for Project ‘test-project’.
```

### Proposed Solution

Use validating webhook to check wether ProjectType is used and disallow its deletion if so

**Comment by yalosev** [comment]
As an example, you can use hook like [this](https://github.com/deckhouse/deckhouse/blob/main/modules/150-user-authn/webhooks/validating/group)

Get snapshot with all Projects and check ProjectType usage
