### ISSUE TITLE
[external-module-manager] Error on module absent on a channel

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5326]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.48.0

### Expected Behavior

Don't know. Have to discuss

### Actual Behavior

If the module has not been released on a release channel, an error will be displayed (see screenshot).

We can catch this error and hide a module from the available ones, but this may confuse a user - why he created the module, but it is not in the available ones. Although the problem lies in the fact that he has not released the module.

![image](https://github.com/deckhouse/deckhouse/assets/14013249/e10f8fba-f8f4-4324-b71b-2d3d8d2e734a)

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
You can use [ModuleUpdatePolicy](https://github.com/deckhouse/deckhouse/pull/6668) to set custom channel for module. This resolves the issue. Of course, you still can't deploy the module if it's not released. Seems obvious.
