### ISSUE TITLE
Add the ability to enable cpu manager for Nodes

### ISSUE THREAD

**Issue by fl64** [deckhouse/deckhouse#5330]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

VMs with dedicated cores are supposed to be used in virtualization module, for this purpose `cpuManagerPolicy: static` parameter should be enabled in kubelet configuration. 
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

### Proposed Solution

Add the `enableDedicatedCPU` parameter to the NodeGroup. The default value is `false`.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/pull/7199
