### ISSUE TITLE
[monitoring] Sending Grafana alerts using GrafanaAlertsChannel and CustomAlertmanager.

### ISSUE THREAD

**Issue by EvgeniiAl** [deckhouse/deckhouse#5359]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are two resources called CustomAlertmanager and GrafanaAlertsChannel in deckhouse, and I tried to make them work together to send Grafana alerts, but it didn't work out.

The CustomAlertmanager deploys alertmanager with an HTTPS service and a self-signed certificate. This works for sending Prometheus alerts since SSL certificate validation is disabled in the Prometheus configuration.

However, in the Grafana notification channel, there is no such option.

### Proposed Solution

switch from self-signed certificates to certificate signed with kube CA

**Comment by konstantin-axenov** [comment]
You have to use ingress to send alerts from Grafana to CustomAlertManager.

**Comment by EvgeniiAl** [comment]
It looks like if HA mode is enabled in mc prometheus we can't use ingress for sending alerts because an alert should be sent to every pod of AlertManager without loabbalancing as mentioned [here](https://github.com/prometheus/alertmanager#high-availability)

> Important: Do not load balance traffic between Prometheus and its Alertmanagers, but instead point Prometheus to a list of all Alertmanagers. The Alertmanager implementation expects all alerts to be sent to all Alertmanagers to ensure high availability.
