### ISSUE TITLE
[deckhouse] check_deckhouse_release.go doesn't work in air-gapped environments without authentication

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#5429]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.49

### Expected Behavior

It must work.

### Actual Behavior

There is an error:
```
Module hook failed, requeue task to retry after delay. Failed count is 125. Error: module hook '002-deckhouse/hooks/check_deckhouse_release.go' failed: GET https://nexus.example.com:9001/v2/token?scope=repository%3Ad8%2Fdeckhouse%2Fee%2Frelease-channel%3Apull&service=https%3A%2F%2Fnexus.example.com%3A9001%2Fv2%2Ftoken: unexpected status code 401 Unauthorized
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by konstantin-axenov** [comment]
Only token authentication work for now. We need to add more authentication flows in future.
