### ISSUE TITLE
[monitoring-kubernetes] Empty mountpoint for "/" in kubelet_eviction_nodefs_bytes

### ISSUE THREAD

**Issue by verdel** [deckhouse/deckhouse#5430]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.48.8

### Expected Behavior

In `kubelet_eviction_nodefs_bytes` metric `mountpoint` label for `/` must be equal `/`
![kubelet_eviction_nodefs_bytes](https://s.csssr.com/U019SC8BZAB/2023-08-03-02-00-48-1Um3jXNLdcoZ.jpg)

### Actual Behavior

In `kubelet_eviction_nodefs_bytes` metric `mountpoint` label absent for `/`
![kubelet_eviction_nodefs_bytes](https://s.csssr.com/U019SC8BZAB/2023-08-03-02-01-22-y9B55pNyhLwH.jpg)

### Additional Information

I made a mistake in PR #4888. If the mount point for the requested folder is `/` then`getMountpoint()` function returns an empty string. In this case, the mountpoint label will be missing in the metric.

I will create a new PR as soon as possible with code correcting the behavior of the function.

**Comment by konstantin-axenov** [comment]
@verdel Thanks for your contribution
