### ISSUE TITLE
[prometheus] Use endpointslices api instead of endpoints

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5437]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to use endpointslices due to https://github.com/deckhouse/deckhouse/issues/5435

### Proposed Solution

To be discussed.

**Comment by yalosev** [comment]
Prometheus-operator does not support it nativly yet:
- https://github.com/prometheus-operator/prometheus-operator/pull/5291
- https://github.com/prometheus-operator/prometheus-operator/issues/3862#issuecomment-1068260430
