### ISSUE TITLE
Add support for Debian 12

### ISSUE THREAD

**Issue by wowsel** [deckhouse/deckhouse#5446]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The release of Debian 12 and its first patch (12.1) signals that it is ready for use in production environments. Given the benefits and new features of Debian 12, supporting this new version in Deckhouse would be valuable to our project and its users. This update has brought many new features and improvements that can potentially benefit our project greatly. Currently, users running Debian 12 cannot use Deckhouse due to the lack of support. By adding this support, we could broaden our user base and stay up-to-date with the latest technological advancements.

### Proposed Solution

Add debian 12 support for core master bootstrap and new nodes. Check for compatibility with other components.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
