### ISSUE TITLE
[monitoring] export availability metrics for node groups

### ISSUE THREAD

**Issue by alchazov** [deckhouse/deckhouse#5459]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

```
# kubectl get nodegroups.deckhouse.io worker
NAME     TYPE             READY   NODES   UPTODATE   INSTANCES   DESIRED   MIN   MAX   STANDBY   STATUS   AGE
worker   CloudEphemeral   2       2       2          2           2         2     5                        2y315d
```

Export current status metrics for nodegroups
It's help make alerts of availability nodes on cluster

For example - make metrics for READY / NODES / UPTODATE / INSTANCES / DESIRED / MIN / MAX / STANDBY / AGE

### Proposed Solution

-

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
