### ISSUE TITLE
[priority-class] Pods of chrony and node-local-dns have too low priority

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#5470]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Pods of modules `chrony`, `node-local-dns` have a low priority class like `cluster-medium` (7000) or `cluster-low` (2000) which often causes them to be evicted by higher priority workload and they can't trigger a horizontal scale up. In the result, we have an alert we can't do much about.

### Proposed Solution

Increase priority for such pods.

**Comment by konstantin-axenov** [comment]
Seems that this is quite ok. Evictions of node-local-dns and chrony show problems with capacity planning. But it seems that node-local-dns and chrony have to be evicted prior to user applications with `production-high` PriorityClass.

**Comment by raabdullaev-fl** [comment]
Everything works as expected.
