### ISSUE TITLE
[candi] kubernetes config

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#5482]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When running the deckhouse cluster bootstrap job, from the dh install container.
everything installed, but kubectl did not work.
The problem was that the kube config for the root user was not pulled up.
When running the kubectl config view command I get null values
since bootstrap is creating a link for /root/.kube/
but I have $HOME = /home/root/
that's why the config didn't pull up
<img width="469" alt="image" src="https://github.com/deckhouse/deckhouse/assets/90387970/c68f77ac-0468-42b7-b83e-e7639b54f602">

### Proposed Solution

add step to boostrap.sh search $HOME and do link
mkdir -p $HOME/.kube
link -s /etc/kubernetes/admin.conf $HOME/.kube/config

**Comment by name212** [comment]
closed by
https://github.com/deckhouse/deckhouse/pull/5626
