### ISSUE TITLE
[helm] rename the module to monitoring-helm

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5489]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

the current name is misleading for dh https://deckhouse.io/documentation/v1/#module-bundles users and does not reflect its contents.

### Proposed Solution

rename the module to monitoring-helm

**Comment by konstantin-axenov** [comment]
Can we move module content to monitoting-kubernetes?

**Comment by alexey-gavrilov-flant** [comment]
I need to check the runtime of HelmReleasesHasResourcesWithDeprecatedVersions and HelmReleasesHasResourcesWithUnsupportedVersions if there is a reboot of dh pods
