### ISSUE TITLE
[control-plane-manager] Changing kubernetesVersion to Automatic can trigger downgrade by more than 1 version

### ISSUE THREAD

**Issue by asviel** [deckhouse/deckhouse#5497]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.49.3

### Expected Behavior

Deckhouse prevents downgrade that can break the cluster.

### Actual Behavior

If I use `kubernetesVersion`, for example 1.27, and then change it to `Automatic`, deckhouse will start downgrading to the default version (currently 1.23)

**Comment by konstantin-axenov** [comment]
Add validating webhook to checks
- When switching from exact version to Automatic, version can't be downgraded. User have to provide exact version that he wants to switch too.
- When switching to Automatic from exact version, version can't be downgraded. User have to provide exact version that he wants to switch too.

**Comment by yuriygoryaev** [comment]
Solution:
- Somewhere store (e.g. in secret) the maximum version of Kubernetes that was used in the cluster (version greater than 1 from the maximum).
- If there will be a version more than 1 from the maximum, then enable notification.
