### ISSUE TITLE
[deckhouse] Add before update preflight check that verifies deprecated api usage

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5544]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Safe update of Deckhouse version

### Proposed Solution

Notify user that here are deprecated api in the cluster. User have to approve deckhouse update manually in this case.

- Add alert about deprecated api usage
- Check that this alert and alert for deprecated resources in helm releases are not firing before update

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
Implemented in #7401
