### ISSUE TITLE
[candi] Delete ssh keys after bootstrapping a node

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#5585]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

By using the default SSH key, it is possible to access all nodes by default. The risks of this are high and can be minimized.

### Proposed Solution

1. Generate SSH key in `dchtl` during bootstrap, and upload it to a secret in a Kubernetes cluster by default (instead of asking a user for a key).
2. Delete the default SSH key after bootstrap (optional, maybe NodeGroupConfiguration example will be enough).
3. Use the `kubectl debug` command in all possible cases (push a debug pod to the Deckhouse registry to use in air-gapped environments).

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
