### ISSUE TITLE
[ingress-nginx] there are data skips at rare metrics from protobuf-exporter

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5592]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50.1

### Expected Behavior

Sampling formulas should take this feature of the exporter into account.

### Actual Behavior

In all charts that use metrics from protobuf-exporter. metrics do not start from 0 but from 1, which gives data skipping on dashboards in grafana where "rate" is used. 

### Steps To Reproduce

1. grafana dashboards vhosts
2.  graph 4xx 
3. there is a 404 error that happens once 2h it is not visible on the charts. 

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1692116907047179
https://github.com/deckhouse/deckhouse/blob/main/modules/402-ingress-nginx/images/protobuf-exporter/rootfs/etc/protobuf_exporter/mappings.yaml

**Comment by alexey-gavrilov-flant** [comment]
```
  clamp_min(
      sum by (vhost, location) (
          sum by (vhost, location) (
            ingress_nginx_detail_responses_total{app=~".*",content_kind=~".*",controller=~".*",ingress=~".*",job="nginx-ingress-controller",location=~"$location",namespace=~".*",node=~".*",service=~".*",service_port=~".*",status=~"4..",vhost=~"$vhost"}
          )
        or
          clamp_max(
            absent(notExists{job="nginx-ingress-controller",location="$location",status="400",vhost="$vhost"}),
            0
          )
      )
    -
      sum by (vhost, location) (
          sum by (vhost, location) (
            ingress_nginx_detail_responses_total{app=~".*",content_kind=~".*",controller=~".*",ingress=~".*",job="nginx-ingress-controller",location=~"$location",namespace=~".*",node=~".*",service=~".*",service_port=~".*",status=~"4..",vhost=~"$vhost"} offset 1m
          )
        or
          clamp_max(
            absent(notExists{job="nginx-ingress-controller",location="$location",status="400",vhost="$vhost"}),
            0
          )
      ),
    0
  )
>
  0

**Comment by nabokihms** [comment]
@miklezzzz had a solution for this also: to expose zero metric values for the first scrape and the actual values to the next to catch the rate.

**Comment by nabokihms** [comment]
This case never worked.
