### ISSUE TITLE
[candi] Fqdn node names have to work

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5594]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's convenient for users to have fqdn node names. Seem that they don't work because of some odd reason.

### Proposed Solution

Research previous problem when we decided to use short names for nodes. If it is possible, we need to prepare a migration plan.

**Comment by nabokihms** [comment]
The task's main goal is to figure out why there was a problem with CentOS bootstrapping.

**Comment by RomanenkoDenys** [comment]
We have the step - `/var/lib/bashible/bundle_steps/003_set_short_hostname.sh`. We should try to use full fqdn as node name. 
Test cases:
1. Old nodes with short fqdn should work.
2. New nodes should add with full fqdn name.
3. Test nodes add on all distros (especially on Centos-based).

Note: need to check length of fqdn, it will be not more than 64 symbols. We should truncate name if it is more than 64 symbols (node name used as label which cannot be more 64 symbols).

**Comment by nelegal50** [comment]
Hi there!
how long to fix it?

**Comment by yuriygoryaev** [comment]
Good afternoon!
The task has been studied by engineers. It is put in the queue for realization.
