### ISSUE TITLE
[candi] Don't use /tmp for cluster bootstrap and package installation from registry

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5595]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

CIS Benchmark recommends mounting /tmp with `noexec` option
```
./linux-bench --check="1.1.3,1.1.4,1.1.5,1.1.8,1.1.9,1.1.10"
[INFO] 1 Initial Setup
[INFO] 1.1 Filesystem Configuration
[PASS] 1.1.3 Ensure nodev option set on /tmp partition
[PASS] 1.1.4 Ensure nosuid option set on /tmp partition
[PASS] 1.1.5 Ensure noexec option set on /tmp partition
[PASS] 1.1.8 Ensure nodev option set on /var/tmp partition
[PASS] 1.1.9 Ensure nosuid option set on /var/tmp partition
[PASS] 1.1.10 Ensure noexec option set on /var/tmp partition
```
And cluster bootstrap doesn't work if tmp mounted with noexec:
```
│ ┌ bootstrap.sh
│ │ bash: /tmp/bootstrap.sh: Permission denied
│ └ bootstrap.sh (4.25 seconds) FAILED
└ ⛵ ~ Bootstrap: Initial bootstrap (4.25 seconds) FAILED

run /tmp/candi-bundle-140617726/bootstrap/bootstrap.sh: execute on remote: exit status 126
```
If `noexec` option is removed, bootstrap works
```
cat /etc/fstab | grep tmp
UUID=8764654f-f6cd-4580-9290-d05c7a77ba03 /tmp                    ext4    defaults,nodev,nosuid 1 2
/tmp /var/tmp none rw,nosuid,nodev,bind 0 0
tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,relatime 0 0
```
Also package installation won't work because we use /tmp to run install scripts
```
ls -lah /tmp/tmp.UtbZmnn7Af/
total 3.8M
drwx------.  2 root root 4.0K Aug 19 15:16 .
drwxrwxrwt. 24 root root 4.0K Aug 19 15:24 ..
-rwxr-xr-x.  1 root root  660 Apr 24 22:21 install
-rwxr-xr-x.  1 root root 3.8M Apr 24 22:21 jq
-rwxr-xr-x.  1 root root  632 Apr 24 22:21 uninstall

bb-rp [INFO] Installing package 'jq'
++ pushd /tmp/tmp.PbAamcLTUC
++ ./install
/var/lib/bashible/bashbooster.sh: line 1797: ./install: Permission denied

```

### Proposed Solution

Use /var/lib/bashible/tmp instead of /tmp. But CIS recommends to mount `/var` also with no exec option. Needs investigation and research.

**Comment by konstantin-axenov** [comment]
https://github.com/deckhouse/deckhouse/issues/5484

**Comment by nabokihms** [comment]
Just an idea: One way to solve this is to compile all bash code in one script and execute it from the network buffer directly without saving files to the host.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
/opt/deckhouse/tmp is used
