### ISSUE TITLE
[candi] Cleanup tmp directory after cluster bootstrap

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#5597]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We can't rely on OS /tmp cleanup, so it's better to remove tmp files required for installation after installation is completed.

### Proposed Solution

Dhctl have to remove it's tmp files in the last step.

**Comment by RomanenkoDenys** [comment]
1. We need to add cleanup of registry packages in the case of unsuccesful install.
2. We need to add a bashible bootstrap step which cleans tmp files at the bootstrap end.
3. Remove using of tmp files in the bashible code when it is possible.
4. Avoid [using of /tmp dir](https://github.com/deckhouse/deckhouse/issues/5595) at all, use `/opt/deckhouse/tmp`.

**Comment by name212** [comment]
https://github.com/deckhouse/deckhouse/pull/5739
