### ISSUE TITLE
[log-shipper] Collect logs from Kafka and send them to Kafka

### ISSUE THREAD

**Issue by artem-eliseyev** [deckhouse/deckhouse#560]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We need to send logs to the kafka. For now we are using vector, that send logs to kafka in parallel with log-shipper. If log-shipper will have feature to send logs directly to Kafka we can stop using Vector. For now vector and log-shipper run in parallel and do similar work.

### Proposed Solution

Logs should be sent to the kafka/vector directly from log-shipper module. See thread

**Comment by nabokihms** [comment]
Firstly, we need to stabilize current sinks (elastic, logstash, loki). We will think about adding new sinks later.

**Comment by nabokihms** [comment]
There is a concern about the Vector sink. How do we provide balancing across all Vector instances? The only idea was to tune the connections keepalive option, but it does not seem to work (still worth checking, though).

**Comment by nabokihms** [comment]
Also, do not forget to tune retry_max_duration_secs for the Vector sink because it equals an hour by default.
