### ISSUE TITLE
[deckhouse] deckhouse_kube_snapshot_bytes metric is empty

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#5619]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50

### Expected Behavior

The grafana dashboard `Main / Deckhouse / Snapshots / Snapshots size` must be working.

### Actual Behavior

The dashboard says `No data`. And the `deckhouse_kube_snapshot_bytes` metric is empty.

**Comment by nabokihms** [comment]
This is normal, I deleted the metric a long time ago but forgot to delete the panel in Grafana. 
1. There was a performance issue
2. The metric itself was not correct, misleading I would say

**Comment by nabokihms** [comment]
So the task is to delete the panel from Grafana
