### ISSUE TITLE
Unification of enable/enabled and auto/automatic parameters

### ISSUE THREAD

**Issue by raabdullaev** [deckhouse/deckhouse#5627]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

People see a parameter in one place, assume that it is like this everywhere, and start using it everywhere, but in some places it does not work.

### Proposed Solution

Enable/enabled and auto/automatic parameters should be unified.
Correct:
- enabled
- auto

**Comment by nabokihms** [comment]
Can be solved by implementing a settings migration.
The example can be found here https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/settings-conversion/conversion.go

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
