### ISSUE TITLE
[user-authz] webhook crashes if it called without data

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#5644]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

-

### Expected Behavior

Webhook shouldn't crash while calling without data.

### Actual Behavior

Webhook call without data:
`curl https://127.0.0.1:40443/ -k --cert /etc/kubernetes/pki/front-proxy-client.crt --key /etc/kubernetes/pki/front-proxy-client.key -XPOST`

> root@dev2-master-0:~/pt# kubectl -n d8-user-authz get pods  -w
> NAME                       READY   STATUS    RESTARTS        AGE
> user-authz-webhook-g9rzx   1/1     Running   6 (6s ago)      8m17s
> user-authz-webhook-hkzqd   1/1     Running   2 (6m13s ago)   8m15s
> user-authz-webhook-ssjht   1/1     Running   6 (2m16s ago)   8m18s
> user-authz-webhook-g9rzx   0/1     Error     6 (15s ago)     8m26s
> user-authz-webhook-g9rzx   0/1     CrashLoopBackOff   6 (4s ago)      8m30s
> user-authz-webhook-ssjht   0/1     CrashLoopBackOff   6 (0s ago)      8m32s

Webhook call with data:
`curl https://127.0.0.1:40443/ -k --cert /etc/kubernetes/pki/front-proxy-client.crt --key /etc/kubernetes/pki/front-proxy-client.key -XPOST -d '{}'`

**Comment by libmonsoon-dev** [comment]
After changes:
![image](https://github.com/deckhouse/deckhouse/assets/39344422/15495f8b-d194-48c6-8d64-edcc5e48fc25)
