### ISSUE TITLE
[candi] disable_swap doesn't work sometimes

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#5655]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50.0

### Expected Behavior

Either one of two options:
1. Swap is always disabled
2. If swap is still enabled after bootstrap, show an error 

### Actual Behavior

For example, on astralinux swap sometimes is not disabled. After reboot, kubelet doesn't start. However, users can only see that after reboot Kubernetes API is not available.

![image](https://github.com/deckhouse/deckhouse/assets/32434187/1fd6e4be-7b5e-4c4c-94f7-b1204ef3a6a8)

### Additional Information

Starting from Kubernetes 1.22, kubelet can utilize swap
https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/

However, the feature is still in the alpha stage

**Comment by sprait** [comment]
may be related to https://github.com/deckhouse/deckhouse/pull/8680

**Comment by raabdullaev** [comment]
Fixed in #8680
