### ISSUE TITLE
[metallb] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5673]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.50.3

### Expected Behavior

update the crd used

### Actual Behavior

in the logs complains about using an outdated api

### Steps To Reproduce

1. add bgp config
2. k -n d8-metallb logs controller-5f756fd85d-r7xdz  --tail=10

### Logs

```shell
W0829 11:18:01.185769       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W0829 11:26:29.193816       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
```

**Comment by nabokihms** [comment]
Seems like we already migrated to `IPAddressPool`.
https://github.com/deckhouse/deckhouse/blob/6a0f13f6592f600601053618d0fa361e79227275/ee/modules/380-metallb/templates/controller/ipaddresspools.yaml#L4

need to check and close the issue
