### ISSUE TITLE
[admission-policy-engine] Baseline profile for Pod Security Standards should be default with ability to switch it

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#5749]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

https://kubernetes.io/docs/concepts/security/pod-security-standards/
The most of platforms use Baseline profile as default with ability to swith it.
We should do the same.

### Proposed Solution

1. Set Baseline profile as default for all namespaces, except ours.
2. Make an option in the module to change the default profile.
3. Make migration for the current clusters so that the default profile is Privileged, and for all new clusters - Baseline.
4. Documentation.

**Comment by yalosev** [comment]
```
      podSecurityStandards:
        type: object
        properties:
          policy:
            type: string
            default: Baseline
            enum:
              - Baseline
              - Restricted
              - Privileged
          action:
            type: string
            default: "Deny"
            enum:
              - Deny
              - Warn
              - Dryrun
 ```

or keep old fields

```
      pssProfile:
        type: string
        default: Baseline
        enum:
          - Baseline
          - Restricted
          - Privileged
      enforcementAction:
        type: string
        default: "Deny
        enum:
          - Warn
          - Deny
          - Dryrun
```
