### ISSUE TITLE
[module] Add deckhouse dependency handling

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#5769]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Set module activation based on the deckhouse version

### Proposed Solution

To the `module.yaml` add:

```yaml
dependency:
  deckhouse: >=1.51
```

Activate module only for the suitable deckhouse version

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
