### ISSUE TITLE
[dhctl] installation in air-gapped environments

### ISSUE THREAD

**Issue by yuriygoryaev** [deckhouse/deckhouse#5780]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

This is important because the Internet is not always available. The deckhouse should be installed on the user's PC without internet.

### Proposed Solution

- Check at which stages and which deckhouse packages are needed.
- Understand why they are needed.
- Then consider whether it is possible and appropriate to put them in the registry.

**Comment by konstantin-axenov** [comment]
Check that dhctl works in air-gapped environments.

**Comment by raabdullaev** [comment]
The issue is unclear. Dhctl already works air-gapped environments.
