### ISSUE TITLE
Changing resources for a Yandex NAT instance

### ISSUE THREAD

**Issue by flant-team-zulu** [deckhouse/deckhouse#5823]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Could you add the ability to change [these](https://github.com/deckhouse/deckhouse/blob/ae9c97ac080018caf789e9e69a2c7fa2e4ef62b5/candi/cloud-providers/yandex/terraform-modules/vpc-components/nat_instance.tf#L114-L118) hardcoded parameters? We have cases, where we need more than 2 CPU/2 RAM instance. For example, if we have more than 90K connection per second

### Proposed Solution

configuration like for master-nodes

```[tasklist]
### Tasks
```

**Comment by konstantin-axenov** [comment]
Seems that it's better to migrate to https://cloud.yandex.com/en-ru/docs/vpc/concepts/gateways
