### ISSUE TITLE
Module hook failed, requeue task to retry after delay

### ISSUE THREAD

**Issue by yuriygoryaev** [deckhouse/deckhouse#5836]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.50.6

### Expected Behavior

 `ModuleHookRun task for Synchronization of 'main' group binding, trigger is ReloadAllModules
ModuleHookRun task for Synchronization of 'main' group binding, trigger is ReloadAllModules
Module hook failed, requeue task to retry after delay. Failed count is 1. Error: module hook '000-common/hooks/get_cni_secret.go': dynamic module values update error: merge module 'common' values failed: add operation does not apply: doc is missing path: "/common/internal/cniSecretData": missing value
I0914 21:03:09.238743      13 request.go:682] Waited for 1.0972695s due to client-side throttling, not priority and fairness, request: GET:[https://10.222.0.1:443/apis/rbac.authorization.k8s.io/v1/namespaces/d8-system/roles?resourceVersion=0&resourceVersionMatch=NotOlderThan](https://10.222.0.1/apis/rbac.authorization.k8s.io/v1/namespaces/d8-system/roles?resourceVersion=0&resourceVersionMatch=NotOlderThan)`

### Actual Behavior

The common module is in the list and can be enabled. It will be enough not to put a folder with it in the final image. This also applies to registypackages.

**Comment by raabdullaev-fl** [comment]
Fixed in deckhouse-controller refactoring https://github.com/deckhouse/deckhouse/pull/6495.
