### ISSUE TITLE
[bashible] apt update step constantly restarting

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#5837]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.51.0

### Expected Behavior

Bashible "apt update" dont stuck in infinite loop when "apt update" bug happened

### Actual Behavior

In Ubuntu 22.04 os, when apt-daily service freezes due to a [bug](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/2003851) , the update process started by bashible is constantly restarted due to the inability to obtain apt lock - this causes the Deckhouse queue to freeze.

### Additional Information

This problem now solving in-place by running command `service apt-daily stop`, which killing stuck apt process and releasing lock.
My suggestion is to use the same command in bashible automatically before executing the apt update command.
Another solution is to tune system-wide apt timeouts by creating config file:
`#cat /etc/apt/apt.conf.d/99timeout`
`Acquire::http::Timeout "120";`

Very similar problem solved by this [issue](https://github.com/deckhouse/deckhouse/issues/5035)

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/issues/5035
