### ISSUE TITLE
[multitenancy-manager] Rename things

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#5851]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Now there is a mixture of _environment_ and _project_ terms as well as _template_ and _type_. I think the doc and CRDs themselves should be clearly aligned with their purpose and responsibility.

### Proposed Solution

1. Rename CRD `ProjectType` → `ProjectTemplate`
   1.  Hence `Project#spec.projectTypeName` → `Project#spec.templateName`
1. Rename `Project#spec.template` → `Project#spec.templateValues`
   1.   the doc states it must contain values for Helm template, so this is not a template itself
   2. `templateValues` is symmetrical to `templateName`
   3. it could also be `projectTemplateName` and `projectTemplateValues`, but that would not bring new sense IMO
~~1. `ProjectType#spec.subjects` seems weird, because I'd like to give access project-wise, not type(template)-wise~~
   ~~1. Bring subjects to `Project` or, probably, to a new CRD (`ProjectBinding`?)~~
   ~~1. Probably, it should  be renamed to `members` (project members, not so abstract 'subjects')~~
1. Rename `ProjectType#spec.resourcesTemplate` → `ProjectTemplate#spec.template` 
   1. Naming kubernetes resources as 'resources' brings no new information
1. Rename `ProjectType#spec.openAPI` → `ProjectTemplate#spec.valuesSchema`
   1. If one has template, it has values (or context), the connection of `template` + `valuesSchema` seem a little more obvious
   1. There is no need to formulate the contract ('openAPI'), it is the purpose that it meaningful (value)
   1. Finally, it is JSON Schema, no HTTP API is implied 
   1. Rename `{{ params }}` field in helm templates to `{{ templateValues }}` according to 2 paragraph
3. ~~Rename `ProjectType#spec.subjects.role` → `ProjectType#spec.subjects.accessLevel`, since the thing is directly reused from [AuthorizationRule#spec.accessLevel](https://deckhouse.io/documentation/latest/modules/140-user-authz/cr.html#authorizationrule-v1alpha1-spec-accesslevel)~~

### Additional Information

Also, a fix should be considered for "name", "namespace" and similar fields where a number can be accidentally rendered.

https://github.com/deckhouse/deckhouse/blob/main/ee/modules/160-multitenancy-manager/templates/user-resources-templates.yaml#L121-L123

![image](https://github.com/deckhouse/deckhouse/assets/5133540/3acc91f8-d89d-4c42-8069-a0e0999e3df1)

**Comment by raabdullaev-fl** [comment]
Check OpenAPI vs params.
