### ISSUE TITLE
[prometheus] Some container restart status for pods during deploy

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#59]
In the `Namespace/Controller` dashboard, we show the `Some containers restart` status if there is a problem with the number of controller replicas. Showing something like `Some containers are not running` would be more accurate.

**Comment by nabokihms** [comment]
Not ready pods also cause the `some containers restart` status.

**Comment by konstantin-axenov** [comment]
Closed in https://github.com/deckhouse/deckhouse/commit/2051202446af3efb1d131159a860e0c9bbca9a6a
