### ISSUE TITLE
[bashible] add to kubelet to hold parameters to customize numa 

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#5967]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

when using servers with numa it should be possible to seat pod containers on a single numa to improve performance

### Proposed Solution

two scenarios are possible to add the ability to set values for --topology-manager-scope and --topology-manager-policy or to be able to add arbitrary parameters for kubelet in nodeGroup settings

### Additional Information

https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
https://flant.slack.com/archives/C78AQG5EY/p1695807192710719

**Comment by konstantin-axenov** [comment]
Consider adding topology options to NodeGroup
