### ISSUE TITLE
[operator-trivy] scan some images from quay.io failed

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#6012]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.51.6

### Expected Behavior

Should create report

### Actual Behavior

Scan failed with error:
```
{"level":"error","ts":"2023-10-02T09:24:44Z","logger":"reconciler.scan job","msg":"Scan job container","job":"d8-operator-trivy/scan-vulnerabilityreport-9bd8cdff8","container":"fluentd-elasticsearch2","status.reason":"Error","status.message":"2023-10-02T09:24:42.238Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: unable to initialize a scanner: unable to initialize the remote docker scanner: 4 errors occurred:\n\t* unable to inspect the image (quay.io/fluentd_elasticsearch/fluentd:v2.5.2): Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\t* containerd socket not found: /run/containerd/containerd.sock\n\t* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory\n\t* unsupported MediaType: \"application/vnd.docker.distribution.manifest.v1+prettyjws\", see https://github.com/google/go-containerregistry/issues/377\n\n\n","stacktrace":"github.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).processFailedScanJob\n\t/src/pkg/vulnerabilityreport/controller/scanjob.go:299\ngithub.com/aquasecurity/trivy-operator/pkg/vulnerabilityreport/controller.(*ScanJobController).reconcileJobs.func1\n\t/src/pkg/vulnerabilityreport/controller/scanjob.go:81\nsigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:103\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226"}
```

and vuln report not generated

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2023-09-21T09:08:08Z"
  generation: 1
  labels:
    k8s-app: fluentd-logging
  name: fluentd-elasticsearch2
  namespace: default
  resourceVersion: "72222850"
  uid: 319b63a3-b582-4e6d-8a86-57cda83f8933
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: fluentd-elasticsearch2
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: fluentd-elasticsearch2
    spec:
      containers:
      - image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        imagePullPolicy: IfNotPresent
        name: fluentd-elasticsearch2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

### Additional Information

Problem with Schema v1 images.
Probably it was fixed [here](https://github.com/google/go-containerregistry/pull/1626)
We can try to update tryivy/trivy-operator images

**Comment by miklezzzz** [comment]
after some research, it seems to me it's impossible to workaround the schema v1 problem if it is the only media type a registry provides. The [aforementioned](https://github.com/google/go-containerregistry/pull/1626) changes to go-containerregistry provides only partial support for schemav1 and some methods which trivy uses, such as ConfigFile(), aren't [implemented](https://github.com/google/go-containerregistry/pull/1626/files#diff-24daa75a8ef3d5298c65e08b85f670cc7b15491ada0e7b4051c6e9dca0a40b2fR71-R73). As I understand, quay.io deliberately decided to not convert users' images schema from v1 to v2 forcibly as it would involve messing up with image digests and it's more up to users if and when to renew their images' schemas. And indeed, there are newer images which actually can be downloaded and checked by the trivy as they are of oci v2 schema.

(main)$ ./trivy image quay.io/keycloak/keycloak:23.0.3
2023-12-25T12:57:14.305+0300	INFO	Vulnerability scanning is enabled
2023-12-25T12:57:14.305+0300	INFO	Secret scanning is enabled
2023-12-25T12:57:14.305+0300	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-12-25T12:57:14.305+0300	INFO	Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret/#recommendation for faster secret detection

<requested media types>
[application/vnd.docker.distribution.manifest.v1+json application/vnd.docker.distribution.manifest.v1+prettyjws application/vnd.docker.distribution.manifest.v2+json application/vnd.oci.image.manifest.v1+json application/vnd.docker.distribution.manifest.list.v2+json application/vnd.oci.image.index.v1+json]

<provided media types>
application/vnd.oci.image.index.v1+json
application/vnd.oci.image.manifest.v1+json

2023-12-25T12:57:16.257+0300	INFO	Detected OS: redhat
2023-12-25T12:57:16.257+0300	INFO	Detecting RHEL/CentOS vulnerabilities...
2023-12-25T12:57:16.266+0300	INFO	Number of language-specific files: 1
2023-12-25T12:57:16.266+0300	INFO	Detecting jar vulnerabilities...

quay.io/keycloak/keycloak:23.0.3 (redhat 9.3)

Total: 19 (UNKNOWN: 0, LOW: 11, MEDIUM: 8, HIGH: 0, CRITICAL: 0)
```
