### ISSUE TITLE
[ingress-nginx] after upgrading from 1.1 to 1.6 CPU consumption increased by 20%

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6042]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52.8

### Expected Behavior

 CPU consumption did not increase at the other clients.

### Actual Behavior

one of the clients has increased CPU consumption after the upgrade 

### Steps To Reproduce

1. ?

### Additional Information

possibly related to https://github.com/kubernetes/ingress-nginx/issues/9848
https://flant.slack.com/archives/CML93AWG2/p1694701483882739

```
[11:06:51][ssh][a.gavrilov@...] ~ $ k get ingressnginxcontrollers.deckhouse.io  main-host-port -oyaml
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: main-host-port
spec:
  chaosMonkey: false
  disableHTTP2: true
  hostPort:
    behindL7Proxy: true
    httpPort: 80
    httpsPort: 443
    realIPHeader: X-Forwarded-For
  hsts: false
  ingressClass: nginx
  inlet: HostPort
  maxReplicas: 2
  minReplicas: 2
  underscoresInHeaders: false
  validationEnabled: true
  waitLoadBalancerOnTerminating: 60
```

**Comment by miklezzzz** [comment]
couldn't reproduce the issue, tested with our ingress images (1.1, 1.6, 1.9) as well as with original ones.

our images showed pretty equal load
![image](https://github.com/deckhouse/deckhouse/assets/41360396/413a6c09-d7de-4fde-b8bc-e54d9ac5596f)
![image](https://github.com/deckhouse/deckhouse/assets/41360396/42afddc2-3d6c-4dcf-9715-c8d834fbaffd)

original images - the same
![image](https://github.com/deckhouse/deckhouse/assets/41360396/16582a06-0dc7-4714-bf64-0acf21ada557)

tests with some extra load from config reloads showed nothing remarkable
https://files.slack.com/files-pri/T037FSPS9-F06HLDU4VQR/image.png
![image](https://github.com/deckhouse/deckhouse/assets/41360396/86f9a3be-69de-4277-a89f-19bf0d595bc6)
