### ISSUE TITLE
[bashible] when joining a cluster, wait for nodes to be created in the cluster

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6057]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52.0

### Expected Behavior

wait until the nodes object is added and then try to add the annotation afterwards 

### Actual Behavior

Now when adding a node an error is thrown for the first time when trying to add an annotation

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1696422148883149

### Logs

```shell
=== Step: /var/lib/bashible/bundle_steps/098_remove_old_binaries.sh
===
===
=== Step: /var/lib/bashible/bundle_steps/099_reboot.sh
===
Error from server (NotFound): nodes "d8-worker-01" not found
Failed to annotate node d8-worker-01 with annotation node.deckhouse.io/configuration-checksum=1a70a8d65e313a67e50812691167a61679101b455faa86d0a9a215fc0783cdef ... retry in 10 seconds.
```

**Comment by konstantin-axenov** [comment]
Check other places where `Error` is shown in output. There must be no `Error` during bootstrap.
