### ISSUE TITLE
[multitenancy-manager] Rename ProjectType to ProjectTemplate

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#6104]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

-

### Proposed Solution

ProjectType should be renamed to ProjectTemplate. Don't forget about the documentation.

**Comment by shvgn** [comment]
Are there going to be any structure changes? Or is it just CRD name? 

I see the task is in progress. May somebody please link the PR to this issue?

**Comment by shvgn** [comment]
I suggest closing this issue in favor of redesign agreements in https://github.com/deckhouse/deckhouse/issues/5851
