### ISSUE TITLE
[dhctl] Upload bootstrap log to Kubernetes cluster

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6108]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If the cluster installation is successfully completed, it is not always immediately clear that the cluster is not working, and the installation logs are the most valuable in such cases.

### Proposed Solution

Save output to the secret bootstrap-log in kube-system namespace

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1696499012076399

**Comment by raabdullaev** [comment]
Such cases should be resolved through alerts.
