### ISSUE TITLE
[candi] When restarting the pods on the node, there is an error that the disc cannot be mounted

### ISSUE THREAD

**Issue by yuriygoryaev** [deckhouse/deckhouse#6130]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.0.0

### Expected Behavior

  You shouldn't get an error like this

### Actual Behavior

When restarting the pods on the node, there is an error that the disc cannot be manaunched

`kubelet  MountVolume.MountDevice failed for volume "pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e" : rpc error: code = Internal desc = device already in use and mounted elsewhere`

Go to the node where the pod is running and see that the disc is mounted there.
`k8s-prod-dc01-system-aec182fc-66766-jcwcv:~$ mount | grep pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e/globalmount type ext4 (rw,relatime)`

unmount the drive

`sudo umount /dev/sdc`

and everything is successfully mounted

`mount | grep pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e
/dev/sdc on /var/lib/kubelet/pods/7ea5f594-56f5-4ccf-894b-e90334658641/volumes/kubernetes.io~csi/pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e/mount type ext4 (rw,relatime)
/dev/sdc on /var/lib/kubelet/pods/7ea5f594-56f5-4ccf-894b-e90334658641/volume-subpaths/pvc-785e8f1e-2bc1-4cc6-a319-3b58d58d185e/fix-permissions/0 type ext4 (rw,relatime)`

**Comment by konstantin-axenov** [comment]
The problem seems to be already mitigated in most cases by manual actions. If there are still occurrences of this problem, then PrometheusRule and NodeGroupConfiguration can be deployed in cluster. Closing for now. https://github.com/deckhouse/deckhouse/pull/6853 with possible fix is also closed.
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    prometheus: main
    component: rules
    heritage: deckhouse
  name: failed-mount-for-on-node
  namespace: d8-system
spec:
  groups:
  - name: node.failedmount
    rules:
    - alert: NodeHasFailedMount
      annotations:
        description: |
          The node `{{ $labels.node }}` has one or more mounts in the old format for persistent volumes.
          Metrics are not available for these persistent volumes and on restart the Pod may hang in the Terminating state until the node manually unmounts the volume.
          To fix this, drain and restart the node.
        plk_markup_format: markdown
        plk_protocol_version: "1"
        plk_create_group_if_not_exists__nodehasfailedmounting: "NodeHasFailedMounting,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
        plk_grouped_by__nodehasfailedmounting: "NodeHasFailedMounting,tier=cluster,prometheus=deckhouse,kubernetes=~kubernetes"
        summary: |
          The node has one or more mounts in the old format for persistent volumes 
      expr: max by (node) (kube_node_labels{label_node_deckhouse_io_failed_mount="true"}) >= 1
      labels:
        severity_level: "4"
---
apiVersion: deckhouse.io/v1alpha1
kind: NodeGroupConfiguration
metadata:
  name: label-node-with-failed-mounts.sh
spec:
  weight: 100
  nodeGroups: ["*"]
  bundles: ["*"]
  content: |
    #!/bin/bash
    function kubectl_exec() {
      kubectl --request-timeout 60s --kubeconfig=/etc/kubernetes/kubelet.conf ${@}
    }

    MAX_RETRIES=10

    function label_node() {
      attempt=0
      until kubectl_exec label --overwrite node $(hostname -s) ${@} 1> /dev/null; do
        attempt=$(( attempt + 1 ))
        if [ -n "${MAX_RETRIES-}" ] && [ "$attempt" -gt "${MAX_RETRIES}" ]; then
          >&2 echo "ERROR: Failed to label node node $(hostname -s) with label ${@} after ${MAX_RETRIES} retries."
          exit 1
        fi
        >&2 echo "Failed to label node $(hostname -s) with label ${@} ... retry in 10 seconds."
        sleep 10
      done
    }

    declare -a mounted_elsewhere_pvcs
    mapfile -t mounted_elsewhere_pvcs < <(journalctl --since "2 min ago" -u kubelet.service |
      grep "device already in use and mounted elsewhere" | \
      grep -oE "pvc-[[:alnum:]]{8}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{12}" | \
      sort -u)

    found=""
    for pvc in "${mounted_elsewhere_pvcs[@]}"; do
      mount="$(mount | grep -oE "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/$pvc/globalmount")"
      if [ "$mount" == "" ]; then
        continue
      fi
      found="yes"
      break
    done

    if [ "$found" == "yes" ]; then
      label_node node.deckhouse.io/failed-mount="true"
    else
      label_node node.deckhouse.io/failed-mount-
    fi
 ```
