### ISSUE TITLE
[tests] wrong behavior in a fake cluster

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#6167]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52.2

### Expected Behavior

Fake cluster should return "" "" as apiVersion, kind

### Actual Behavior

When you iterate over list items
```go
for _, item := range list.Items {
   fmt.Println(item.APIVersion, item.Kind)
}
```
real cluster will return: `"" ""`
when fake cluster will return `"discovery.k8s.io/v1" "EndpointSlice"`

We have to set fake cluster answer as real to prevent unexpected behavior

### Steps To Reproduce

1. Create hook with some objects listing
```go
list, err := client.DiscoveryV1().EndpointSlices(d8Namespace).List(context.Background(), metav1.ListOptions{})
```
2. Iterate over list items
```go
for _, es := range list.Items {
   fmt.Println(es.APIVersion, es.Kind)
}
```

**Comment by raabdullaev** [comment]
Not relevant.
