### ISSUE TITLE
[chrony] windows ntp is not considered valid for obtaining accurate time

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6170]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.51.0

### Expected Behavior

to be able to use such time servers

### Actual Behavior

synchronization doesn't work

### Steps To Reproduce

1. usage windows ntp https://deckhouse.ru/documentation/v1/modules/470-chrony/configuration.html#parameters-ntpservers

### Additional Information

https://www.suse.com/support/kb/doc/?id=000020824
It is necessary to be able to set maxdistance to reduce the accuracy of time synchronization

maxdistance 16.0

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by meatuses** [comment]
Tested v1.63.10 `chrony` module against freshly installed Windows Server 2022 AD NTP service with all defaults and it works fine.
Testing was performed over WAN with about 60ms of round-trip time.
![image](https://github.com/user-attachments/assets/2157e93e-4551-44d8-85a4-898d0c1f3c27)


`root dispersion` was too big (>7s) only immediately after `w32time` service restart. Shortly after it would stabilise on low values.
![image](https://github.com/user-attachments/assets/974ae4d9-60e6-424e-a9fe-a74a3252e0c8)
![image](https://github.com/user-attachments/assets/b0d75ac6-d1c5-47e0-b1fc-96f0c0ba724f)

**Comment by meatuses** [comment]
Therefore we assume, if Windows NTP server has high dispersion (>1s), the probable cause is misconfiguration on the Windows side
