### ISSUE TITLE
[node-manager] checksum calculation ignores default value for diskSize

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#619]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.29

### Expected Behavior

When diskSizeGb is not specified in the instance class and the default value is used, it is ignored when calculating the checksum

### Actual Behavior

When adding diskSizeGb with a default value to the instance class, the checksum should not change

**Comment by EvgenySamoylov** [comment]
@vitaliy-sn Could you please specify, which cloud provider this is actual for?
