### ISSUE TITLE
NodeDiskBytesUsage alert doesn't work

### ISSUE THREAD

**Issue by pkonovalov** [deckhouse/deckhouse#6209]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.51.10

### Expected Behavior

There must be an alert `NodeDiskBytesUsage` if used disk space on node's root mountpoint is more than 70%

### Actual Behavior

`NodeDiskBytesUsage` doesn't work if used disk space on node's root mountpoint is more than 70%

### Steps To Reproduce

0. There must be some nodes with disk space usage > 70%
1. run query in prometheus
```
(max by (node, mountpoint) ((node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes) * 100 unless (max by (node, mountpoint) ({__name__=~"kubelet_eviction_.+_bytes",type="hard"}))) > on (node) group_left () (max by (node) (extended_monitoring_node_threshold{threshold="disk-bytes-warning"}))
```
you will get `Empty query result`
2. Remove `mountpoint` from right side of expression (after `unless`):
```
(max by (node, mountpoint) ((node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes) * 100 unless (max by (node) ({__name__=~"kubelet_eviction_.+_bytes",type="hard"}))) > on (node) group_left () (max by (node) (extended_monitoring_node_threshold{threshold="disk-bytes-warning"}))
```
you will get:
```
{mountpoint="/", node="kube-node-4"}
72.54412447849529
{mountpoint="/", node="kube-node-6"}
85.75308519168343
```

**Comment by asviel** [comment]
https://github.com/deckhouse/deckhouse/pull/5431

**Comment by yalosev** [comment]
Source [thread](https://flant.slack.com/archives/CML93AWG2/p1697458595759629)
