### ISSUE TITLE
[cluster-api] static provider added standby

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6237]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In a static cluster, it is also necessary to be able to have standby nodes that are ready to take the load immediately. because moving a node from the stockpile involves changes that are not guaranteed to be completed immediately or successfully.

### Proposed Solution

move the standby parameter from cloudInstances to a higher level to be able to always use it.
https://deckhouse.io/documentation/v1/modules/040-node-manager/cr.html#nodegroup-v1-spec-cloudinstances-standby

### Additional Information

https://flant.slack.com/archives/CML93AWG2/p1697548820521239

**Comment by RomanenkoDenys** [comment]
You can do it by adding taints to nodes.
