### ISSUE TITLE
[getting-started] Use nip.io like service for the "Getting Started" instructions

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#630]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

As of today, we suggest adding entries for Deckhouse modules to the `/etc/hosts` file on a user's PC in our "Getting Started" documentation. With this approach, users cannot order certificates, access cluster resources from many machines, etc.

### Proposed Solution

Use https://nip.io/ to avoid adding entries to the /etc/hosts file. We will achieve the experience of using a real DNS without having a DNS server.

**Comment by nabokihms** [comment]
We still want this, it is a lot better then writing entries to the hosts file.

**Comment by z9r5** [comment]
Note, that some providers block resolving nip.io and similar services.

**Comment by z9r5** [comment]
[Done](https://github.com/deckhouse/deckhouse/pull/3256)
