### ISSUE TITLE
[external-module-manager] Registry secret is not renewed

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#6358]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.0

### Expected Behavior

When the dockerCfg is changed in the module source, in the values of the module it stays the same.

### Actual Behavior

The dockerCfg is injected as a default value right to the opanapi/values.yaml https://github.com/deckhouse/deckhouse/blob/1a15c0ad33fcd6f2252d1007962afe9f18abee6d/modules/005-external-module-manager/hooks/handle_sources.go#L617

This values is changed only when the new version of the module is downloaded.

### Steps To Reproduce

1. Create a module source
2. Change the dockerCfg 
3. Check the module values
4. Restart deckhouse
5. Check again

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
