### ISSUE TITLE
[deckhouse] Do not allow to create module configs for unknown modules

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#6359]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If a user deploys a new module config for an unknown module, it will bypass the validation an be create. The main problem is when the module will be downloaded, e.g., from the module source, deckhouse will fail to start with the openapi validation error (in case of the invalid config).

### Proposed Solution

Prevent creating module configs for unknown modules (at least it will fix the bootstrap case).

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
