### ISSUE TITLE
[candi] Remove previous containerd systemd unit

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#6365]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Users can make mistake and start old unit

### Proposed Solution

Remove the old one
```
root@k-aksenov-master-0:~# systemctl status containerd | head -n 3
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; disabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2023-10-12 12:31:17 UTC; 2 weeks 3 days ago
root@k-aksenov-master-0:~# systemctl status containerd-deckhouse | head -n 3
● containerd-deckhouse.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd-deckhouse.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-10-26 20:05:42 UTC; 3 days ago
```

**Comment by mvasl** [comment]
This would violate astralinux security policy, preventing "Ready for Astra" certification
