### ISSUE TITLE
[user-authz]  user-authz-webhook livenessProbe not work

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6368]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.52.8

### Expected Behavior

add curl to the image or stop using curl in livenessProbe

### Actual Behavior

livenessProbe does not work because there is no curl in the image

### Logs

```shell
# kubectl -n d8-user-authz get events --sort-by='.metadata.creationTimestamp'
LAST SEEN   TYPE      REASON      OBJECT                         MESSAGE
19s         Warning   Unhealthy   pod/user-authz-webhook-fxn7k   (combined from similar events): Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "d25b290304bcbac3fddfb1c70ae64b0015e8d03734714b08e1c76bbaf2bcd10b": OCI runtime exec failed: exec failed: unable to start container process: exec: "curl": executable file not found in $PATH: unknown
```

**Comment by yalosev** [comment]
Add http probe with `scheme: HTTPS`

```
If scheme field is set to HTTPS, the kubelet sends an HTTPS request skipping the certificate verification.
```

I think it will be enough
