### ISSUE TITLE
[cloud-provider-yandex] need to decrease the shutdown_grace_period value for preemptible nodes

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6414]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.3

### Expected Behavior

pods should report that they are shutting down before the displaced node is hard shutdown.
https://github.com/deckhouse/deckhouse/blob/58c141d7431eb1d2922d2dac94362e3419bdf5f2/candi/cloud-providers/yandex/bashible/common-steps/all/000_set_cloud_variables.sh.tpl#L17

### Actual Behavior

pods don't have time to start deleting from the evicted node before it shuts down.

### Additional Information

https://support-center.cloud.yandex.ru/tickets/HL663946

**Comment by alexey-gavrilov-flant** [comment]
```
Прерываемые инстансы отзываются облаком в любой момент и убиваются в течение 30 сек.

Касательно работы с прерываймыми ВМ в контексте кластера k8s. Для согласования таймингов процесса в качестве параметров kubelet используются:

shutdownGracePeriod: 25s - время ожидания грейс-завершения обычных подов;

shutdownGracePeriodCriticalPods: 10s для системных.
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
