### ISSUE TITLE
[Managing nodes] Improving the script for connecting the node to the master.

### ISSUE THREAD

**Issue by Zhbert** [deckhouse/deckhouse#6427]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When connecting a new node to the created cluster, an error appears at the end of the step `100_disable-ntp-on-node.sh`:
```
=== Step: /var/lib/bashible/bundle_steps/100_disable-ntp-on-node.sh
===
Removed /etc/systemd/system/dbus-org.freedesktop.timesync1.service.
Removed /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service.
Error from server (NotFound): nodes "gs-test-worker-2" not found
Failed to annotate node gs-test-worker-2 with annotation node.deckhouse.io/configuration-checksum=dac66c8ee95be7046b7dd0402131ac36b4f6be5bdfc2c3a67f7e4dd732a87307 ... retry in 10 seconds.
```
It doesn't affect anything, but it can confuse those who connect new nodes to the cluster for the first time.

### Proposed Solution

Modify the script so that if it is impossible to hang the annotation on the node the first time, the script does not fall with an error, but either waits or hides this message.

**Comment by raabdullaev-fl** [comment]
In the future we plan to abstain from using script manually and bootstrap cluster nodes using Cluster API Provider Static.
