### ISSUE TITLE
[deckhouse] update.windows setting is not respected on manual update mode

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#6444]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.3

### Expected Behavior

Updates applied only during update.windows settings, even if update.mode=Manual, because no other behavior is specified in the documentation

### Actual Behavior

Updates are applied immediately upon approval (but respecting applyAfter delay of the canary release mechanics)

### Additional Information

Update windows not checked during update process in source files:
https://github.com/deckhouse/deckhouse/blob/343f5606c14586dc3b27882a0841ff8d58d4da51/modules/002-deckhouse/hooks/internal/updater/updater.go#L216

PR with update delay in canary :
https://github.com/deckhouse/deckhouse/pull/6249

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
This is how it works by design.
