### ISSUE TITLE
[prometheus] Consider using separate labels for all metrics ingested from deckhouse components

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#645]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some exporters (namely, `kubecost`) may duplicate metric names with those scraped from deckhouse exporters. Consequently, recording and alerting rules may fail.

### Proposed Solution

Use labels from deckhouse exporters so that all our rules will work only with deckhouse metrics.

**Comment by EvgenySamoylov** [comment]
We've added support of the ServiceMonitors and PodMonitors from user-space which could be good workaround for this case: #604
