### ISSUE TITLE
Kubernetes CIS Benchmark not compliant

### ISSUE THREAD

**Issue by qw1mb0** [deckhouse/deckhouse#6454]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.3

### Expected Behavior

Full compliance of the Deckhouse platform with Kubernetes CIS Benchmark.

### Actual Behavior

There are currently 2 checks that fail the Kubernetes CIS Benchmark:
```
[WARN] 1.1.9 Ensure that the Container Network Interface file permissions are set to 600 or more restrictive (Manual)
# stat -c permissions=%a /etc/cni/net.d/05-cilium.conf
permissions=644
```

```
[WARN] 4.2.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Manual)
These options are not explicitly set in the Kubelet configuration file.
```

### Steps To Reproduce

1. Setup Deckhouse Platform
2. Run [kube-bench](https://github.com/aquasecurity/kube-bench) with [cis 1.25](https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md#cis-kubernetes-benchmark-support)

**Comment by qw1mb0** [comment]
Also, check 4.1.1 does not pass:
```
[FAIL] 4.1.1 Ensure that the kubelet service file permissions are set to 600 or more restrictive (Automated)
```

```
# stat -c permissions=%a /opt/deckhouse/bin/kubelet
permissions=755
```

**Comment by vitaliy-sn** [comment]
```
[WARN] 1.1.9 Ensure that the Container Network Interface file permissions are set to 600 or more restrictive (Manual)
# stat -c permissions=%a /etc/cni/net.d/05-cilium.conf
permissions=644
```

File permissions hardcoded into [Cilium](https://github.com/cilium/cilium/blob/v1.14.5/daemon/cmd/cni/config.go#L289).
At the moment I also cannot reproduce this WARN.

**Comment by AndreyPavlovFlant** [comment]
The 1.1.9 test only checks the CNI plugin configuration files if Docker is used in the cluster.
However, since version 1.24, K8S does not support Docker, so this part of the test will always succeed.

The test also checks the files in the `/var/lib/cni/networks` folder, which contain files of the ipam host-local plugin. 
In plugin version 1.4.0, the permissions were changed from 644 to 600. When we update the plugin version to 1.4.0, test 1.1.9 should start to complete successfully.
