### ISSUE TITLE
[logs] logging pods in journald

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6455]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

in case of network problems there are no logs left on the server to find out details after the incident.

### Proposed Solution

change pod log storage location from files to journald

**Comment by konstantin-axenov** [comment]
The correct solution is to enable log-shipper module and turning on [buffer](https://deckhouse.ru/documentation/v1/modules/460-log-shipper/cr.html#clusterlogdestination-v1alpha1-spec-buffer).
