### ISSUE TITLE
[user-authn] Dex misses logs for sign out and bad credentials

### ISSUE THREAD

**Issue by kozhin** [deckhouse/deckhouse#6458]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For better InfoSec observability it would be great to have logs indicating:
- which user signed out
- which credentials (user name and password) failed on signing in

This is already done for "sing in" action. Actions below are missing.

### Proposed Solution

Add dex pod logging on a similar manner for signing in:
```
{"level":"info","msg":"login successful: connector \"local\", username=\"admin\", preferred_username=\"\", email=\"admin@example.com\", groups=[]","time":"2023-11-07T15:44:57Z"}
```
For signing out:
```
{"level":"info","msg":"logout successful: connector \"local\", username=\"admin\", preferred_username=\"\", email=\"admin@example.com\", groups=[]","time":"2023-11-07T15:44:57Z"}
```
For bad credentials:
```
{"level":"info","msg":"login failed: connector \"local\", username=\"admin\", preferred_username=\"\", email=\"admin@example.com\", groups=[], reason=\"bad credentials\"","time":"2023-11-07T15:44:57Z"}
```

**Comment by konstantin-axenov** [comment]
- Logout can't be logged because there is no logout in dex. It's made in dex-authenticator
- If bad credentials are provided for password authentication attempt [401 error is returned](https://github.com/deckhouse/deckhouse/pull/6045). Errors have to be logged on provider's side for other authentication providers.
