### ISSUE TITLE
[linstor] no node label in D8DrbdPeerDeviceIsOutOfSync alert

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#6462]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.53.3

### Expected Behavior

node label to add or modify the alert instruction

### Actual Behavior

no node label in D8DrbdPeerDeviceIsOutOfSync alert

### Additional Information

https://polk.flant.ru/incidents/f9505598-4b1f-4887-a4ef-61e12a85e1e8
https://github.com/deckhouse/deckhouse/blob/096b2705e9ec1467ff58819c975e547b4d6ebf96/modules/041-linstor/monitoring/prometheus-rules/drbd-devices.yaml#L194

**Comment by konstantin-axenov** [comment]
![image](https://github.com/deckhouse/deckhouse/assets/14013249/5fd77226-dee5-4b8d-8cb2-cbb7092d7979)

**Comment by alexey-gavrilov-flant** [comment]
This problem is caused by a past change https://github.com/deckhouse/deckhouse/pull/5121. I need to roll back some of the changes in modules/041-linstor/templates/linstor-node/podmonitor.yaml.
