### ISSUE TITLE
Add some checks and alerts for the controllers

### ISSUE THREAD

**Issue by EvgenySamoylov** [deckhouse/deckhouse#649]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's important to have the correctly configured PDB, VPA, and PriorityClasses for all the cluster controllers. However it's not validated now so that user can create controllers with no PDB, VPA and PriorityClasses specified.

### Proposed Solution

We need to check if each created controller has proper PDB, VPA, and PriorityClass in place. Or maybe add some extra validation to not allow to create controller without PDB, VPA, and PriorityClass.

**Comment by EvgenySamoylov** [comment]
Related with #1603

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/dmt/
