### ISSUE TITLE
[go_lib] Getting rid of obsolete CRDs and preventing deckhouse update if they are in use

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#6632]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

For example, in cilium 1.14 some CRDs were removed (`CiliumEgressNATPolicy` and `CiliumBGPLoadBalancerIPPool`). We need to get rid of them and develop the right way for cleaning up crd list.

### Proposed Solution

To write a hook that discovers obsolete CRDs and configure a requirement that blocks the update. It is better to develop a lib for this.

**Comment by konstantin-axenov** [comment]
We don't need a general solution, it's an overcomplicated feature. This have to be done for cilium if needed.
