### ISSUE TITLE
Add support for application_credentials in the OpenStack

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#685]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Authentication in the cloud may only be available via application credentials.

### Proposed Solution

Terraform [supports](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs), but additional research needs to be done in CCM, MCM, CSI.

**Comment by raabdullaev** [comment]
It will be reconsidered while migration to CAPI.
