### ISSUE TITLE
When downgrading, the kubelet is rolled back to more than 1 version

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#6855]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

main

### Expected Behavior

The difference between the control-plane and kubelet versions should be 1 minor version.

### Actual Behavior

control-plane is rolled back to version 1 as expected, but kubelet is rolled back to the user-specified one

### Steps To Reproduce

1. cluster with kubernetes 1.28
2. change kubernetesVersion to 1.24
3. wait

### Additional Information

```
root@dev-master-0:~# kubectl get no -o wide 
NAME                              STATUS                     ROLES                  AGE   VERSION    INTERNAL-IP     EXTERNAL-IP    OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
dev-master-0                      Ready                      control-plane,master   68d   v1.24.17   192.168.4.180   9.7.123.3      Ubuntu 22.04.1 LTS   5.15.0-46-generic   containerd://1.6.24
dev-worker-58bd4cc2-56b6f-fjcrx   Ready                      worker                 62d   v1.24.17   192.168.4.226   <none>         Ubuntu 22.04.1 LTS   5.15.0-46-generic   containerd://1.6.24
root@dev-master-0:~# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.17
Kustomize Version: v4.5.4
Server Version: v1.27.8
WARNING: version difference between client (1.24) and server (1.27) exceeds the supported minor version skew of +/-1
root@dev-master-0:~# kubelet --version
Kubernetes v1.24.17
```

**Comment by raabdullaev-fl** [comment]
Connected https://github.com/deckhouse/deckhouse/issues/5497.
