### ISSUE TITLE
[cni-cilium] DNS based network policies

### ISSUE THREAD

**Issue by maksim239k** [deckhouse/deckhouse#6899]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If some application used CDN then the use of egress policies becomes almost impossible.  
Because it is almost impossible to get a complete list of IP addresses in a CDN and keep it up to date.

### Proposed Solution

Add `enable-l7-proxy: true` to cilium config  
https://github.com/deckhouse/deckhouse/blob/main/modules/021-cni-cilium/templates/configmap.yaml

### Additional Information

https://docs.cilium.io/en/latest/security/policy/language/#dns-based

**Comment by konstantin-axenov** [comment]
This feature is enabled by default.
```
root@k-aksenov-master-0:~# kubectl -n d8-cni-cilium exec -ti agent-jnj58 -c cilium-agent -- cilium config get enable-l7-proxy
true
```
Please, provide more information for this issue.

**Comment by maksim239k** [comment]
For some reason previously, when I tried it, it didn't work. Maybe it was my mistake in configuration)
Now it works! Thanks)
