### ISSUE TITLE
Use cache-repo in assembly of Deckhouse editions

### ISSUE THREAD

**Issue by raabdullaev** [deckhouse/deckhouse#6904]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

-

### Proposed Solution

FE should be assembled first, which contains 100% of the Deckhouse images. When assembling EE and CE we can simply use cache-repo and then the stages cache will be reused and the assembly will be faster.

**Comment by raabdullaev-fl** [comment]
Will be implemented in Basic Edition.
