### ISSUE TITLE
Checking existence of script "cleanup_static_node.sh" on static nodes and otherwise adding it

### ISSUE THREAD

**Issue by cds111** [deckhouse/deckhouse#6918]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The script `cleanup_static_node.sh` was added only starting from version **1.52**. If a node was set up in version **1.51** or below, after the update, the documentation for the cluster may differ from the actual situation.

### Proposed Solution

Include a check in Bashible for the presence of cleanup_static_node.sh and add it to the node if the script is not already present

**Comment by konstantin-axenov** [comment]
You have to use documentation for an exact version of deckhouse. If you can't find documentation for your version on deckhouse.io or deckhouse.ru then you need to check documentation in your cluster.
