### ISSUE TITLE
[user-authz] Forbidden access for logged in user if CAR has changed

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#6928]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55

### Expected Behavior

If you apply changes to `ClusterAuthorizationRule`, new permissions should update accordingly for users logged in through `kubelogin`

### Actual Behavior

Changes to `ClusterAuthorizationRule` result in forbidden access for user until manual re-login.

### Steps To Reproduce

1. Create `user`, `group`, add `user` to `group`
2. Create ClusterAuthorizationrule, add `group` and set some permissions
3. Create config for the `user` via `kubeconfig-generator`
3. Use the config on a local machine, login with `kubelogin`+`dex`
4. Expected permissions are working
5. Make some edits: create `group2`, add the `user` to `group2`
6. `kubectl edit clusterauthorizationrule` edit the CAR, change `group` to `group2`
7.  No relogin via kubelogin, any action result in `forbidden` error, no permissions are applied.
8. Wait 10 minutes - indefinitely, still no permissions, no prompt to re-login via dex

### Additional Information

Cleaning up tokens from `~/.kube/cache/oidc-login/* ` helps to trigger a login and permissions would work again.

**Comment by unreturned** [comment]
DKP v1.62.6 problem exists
