### ISSUE TITLE
Fix orphan secret alert description

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#705]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v0.30.1

### Expected Behavior

Alerts are separate with distinct descriptions.

### Actual Behavior

Both alerts:
1. Based on the [annotation](https://github.com/deckhouse/deckhouse/blob/main/modules/101-cert-manager/hooks/orphan_secrets_metrics.go#L140).
2. Based on the [label](https://github.com/deckhouse/deckhouse/blob/main/modules/101-cert-manager/hooks/legacy_orphan_secrets_metrics.go#L81).

Results in the [alert](https://github.com/deckhouse/deckhouse/blob/main/modules/101-cert-manager/monitoring/prometheus-rules/certificate.yaml#L63) that requires a user to delete the annotation.

**Comment by nabokihms** [comment]
We do not have these alerts anymore, so no description changes are required.
