### ISSUE TITLE
[admission-policy-engine] Admission policy engine in baseline/restricted mode forbids launching workloads with istio sidecars

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#7075]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.55

### Expected Behavior

Hasn't been decided yet. We might add additional admission-policy-engine policies for istio-enabled namespaces, or we could recommend setting admission-policy-engine mode to privileged for such namespaces.

### Actual Behavior

`Добрый день коллеги
Хочу включить istio 
Насколько понял надо добавить лейбл в namespace istio-injection=true
Теперь я на деплойменте ловлю такую ошибку 
admission webhook "admission-policy-engine.deckhouse.io" denied the request: [d8-pod-security-baseline-deny-default] init container <istio-init> has a disallowed capability. Allowed capabilities are ["AUDIT_WRITE", "CHOWN", "DAC_OVERRIDE", "FOWNER", "FSETID", "KILL", "MKNOD", "NET_BIND_SERVICE", "SETFCAP", "SETGID", "SETPCAP", "SETUID", "SYS_CHROOT"]`

### Steps To Reproduce

see Actual Behavior

**Comment by raabdullaev-fl** [comment]
There is a right way to reduce capabilities for istio sidecar containers - https://istio.io/latest/docs/setup/additional-setup/pod-security-admission/.
