### ISSUE TITLE
[upmeter] make the ingressClass configuration prettier

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#7097]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There is only configuration section `smokeMini.ingressClass`, but the `smoke-mini` component hasn't an Ingress. But there are two Ingresses for `webui` and `status` without ingressClass configuration.

### Proposed Solution

To configure a common `upmeter.ingressClass` openapi section.

**Comment by vladimirGuryanov** [comment]
Done in [PR](https://github.com/deckhouse/deckhouse/pull/10266)
