### ISSUE TITLE
[monitoring-kubernetes] Events exporter

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#71]
Add Kubernetes events exporter to be able to alert based on them and draw event graphs/tables. This is a not recommended way to treat events like metrics, but it allows us to be more accurate.

**Comment by 31337Ghost** [comment]
[Eventrouter](https://github.com/heptiolabs/eventrouter) can be used for this purpose.

**Comment by EvgenySamoylov** [comment]
Done at ceb1883aa5868e2bfd595133dd6808f3058c44c8
