### ISSUE TITLE
[monitoring-custom][vpa]  check if the application fits on the current node if it applies new vpa values.

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#7143]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes there is a situation where Prometheus has the size of the allocated vpa's larger than the current nodes and restarting does not allow it to start.

### Proposed Solution

It is necessary to take vpa metrics, the size of the node on which the linked pod is launched and then display an alert if the vpa value exceeds 95% of the current node size.

**Comment by konstantin-axenov** [comment]
Solution for this problem is described [here](https://github.com/deckhouse/deckhouse/issues/4617#issuecomment-1844812759).
