### ISSUE TITLE
[external-module-manager] modules releases of a same module but with different weights appear as different modules on file system

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#7215]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.+

### Expected Behavior

previous module releases with different weight values, after getting superseeded, shouldn't appear on the d8 file system as different modules

### Actual Behavior

multiple releases with different weights of a module represent different modules on the d8 file system

### Steps To Reproduce

1. create a module release of foobar module with weight x
2. deploy module release
3. create a new module release of foobar module with weight y
4. there is a high change of having a collision between module releases because the modules/ dir contains
```
/x-foobar/
/y-foobar/
```
folders

### Additional Information

it seems we have to check previous module releases in case they have different weight from current one and delete the module folders of superseded releases

**Comment by konstantin-axenov** [comment]
Fixed by https://github.com/deckhouse/deckhouse/pull/7228
