### ISSUE TITLE
log-shipper doesn't start on ALT Server 10 due to missed tzdata

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#7299]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.56

### Expected Behavior

-

### Actual Behavior

-

**Comment by name212** [comment]
closed by
https://github.com/deckhouse/deckhouse/pull/7403
