### ISSUE TITLE
[node-manager] cluster-autoscaler hangs and stops creating nodes in the cluster

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#7322]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.9

### Expected Behavior

warn that cluster-autoscaler is hung or show what it is currently doing.

### Actual Behavior

The cluster-autoscaler logs show that the main thread is executing, but there are no messages about creating or deleting nodes in the cluster.

There are also pods in Pending. 

restarting cluster-autoscaler immediately leads to the creation of new nodes

### Steps To Reproduce

1. occurs after a long run.

### Additional Information

https://github.com/deckhouse/deckhouse/blob/c226e348fd4bee96d178538099068b9b3c18f691/modules/040-node-manager/templates/cluster-autoscaler/deployment.yaml#L96 There is a special cm for displaying the current state, but we have it turned off.

**Comment by meatuses** [comment]
probably not relevant, probable v1.25 kubernetes version is not supported in current DH releases
no similar incidents reported
