### ISSUE TITLE
[cloud-provider-yandex][yandexinstanceclass] If "diskType" is not specified, "network-hdd" is used

### ISSUE THREAD

**Issue by maray2208** [deckhouse/deckhouse#7344]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.56

### Expected Behavior

In the [documentation](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-yandex/cr.html#yandexinstanceclass-v1-spec-disktype) for yandexinstanceclass, the default diskType parameter is network-ssd, but network-hdd is installed

### Actual Behavior

When installing a cluster, the default disk network-ssd must be ordered

### Steps To Reproduce

1. Install the cluster via [quick start](https://deckhouse.io/gs/yandex/step2.html)
2. We do not specify the diskType parameter in yandexinstanceclass

**Comment by konstantin-axenov** [comment]
Just fix the documentation, please.
