### ISSUE TITLE
remove support for os debian 9 and 10

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#7350]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

we do not need to support os that have already expired. 

### Proposed Solution

we need to clean up scripts from debian 9 and 10.

### Additional Information

 https://wiki.debian.org/LTS

**Comment by alexey-gavrilov-flant** [comment]
![image](https://github.com/deckhouse/deckhouse/assets/53515419/d5a5fbf1-21c0-44be-84d2-b9292de466a0)

**Comment by konstantin-axenov** [comment]
Are there any problems with current support of Debian 9/10? Or the only reason is end of support?

**Comment by alexey-gavrilov-flant** [comment]
There are a couple months left of debian 10 support

**Comment by raabdullaev** [comment]
Support Debian 9 will be removed in #7710.
10 - later after deprecation.
