### ISSUE TITLE
 Describe how to verify requirements for VMware vSphere

### ISSUE THREAD

**Issue by qw1mb0** [deckhouse/deckhouse#7416]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are [requirements](https://deckhouse.io/gs/vsphere/step3.html#list-of-required-vsphere-resources) to install DKP on VMware vSphere, however we have no way to verify that these requirements are met. Therefore, often the client cannot even answer whether the requirements are fully met in his VMware vSphere and he learns about problems during the installation of DKP.

### Proposed Solution

It is necessary to describe the commands/script/images how you can check the fulfillment of each requirement.

**Comment by asviel** [comment]
Due to the variety of possible implementations of the physical layer of the infrastructure, it is difficult to implement sufficient checks.
