### ISSUE TITLE
[node-manager] Update alert about yandex ru-central-c zone deprecation and prepare a migration manual

### ISSUE THREAD

**Issue by raabdullaev-fl** [deckhouse/deckhouse#7439]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

ru-central1-с zone in Yandex.Cloud will be [deprecated](https://cloud.yandex.com/en-ru/docs/overview/concepts/ru-central1-c-deprecation). Resources from it can be moved to a new availability zone - ru-central1-d.
Theres is an old alert about zone deprecation developed in #6614.

### Proposed Solution

The deprecation alert needs to be updated and migration manual prepared.

**Comment by name212** [comment]
closed by
https://github.com/deckhouse/deckhouse/pull/6736/files
and
https://github.com/deckhouse/deckhouse/pull/7514/files
