### ISSUE TITLE
[user-authn] when OnlyInURI is enabled in dex for redirects, the protocol is not correct.

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#7444]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.56.9

### Expected Behavior

there should be https links on requests to dex

### Actual Behavior

http links are created when making requests to dex

### Steps To Reproduce

1. ingress only http 
2. enable OnlyInURI

**Comment by konstantin-axenov** [comment]
Add to the documentation that when mode `OnlyInURI` is used, there have to be external load balancer with redirect from `http` to `https`.

**Comment by meatuses** [comment]
Right now documentation [says](https://deckhouse.io/documentation/v1/modules/300-prometheus/configuration.html#parameters-https-mode) `All the links in the user-authn will be generated using the HTTPS scheme.` So this is misleading?
