### ISSUE TITLE
Cilium HA egress IP support

### ISSUE THREAD

**Issue by qw1mb0** [deckhouse/deckhouse#7499]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Currently, DKP has support for [cilium egress gateway](https://docs.cilium.io/en/stable/network/egress-gateway/), however, this solution is not fault-tolerant and requires manual intervention if the gateway node fails where the traffic comes from.

### Proposed Solution

Implement a mechanism that allows you to automatically switch outgoing traffic to a live cluster node and describe the limitations of this solution (TCP session interruption, traffic drop, switching time, examples of use)

### Additional Information

OpenSource solution to this problem [It is simple k8s operator based on Flant shell-operator for egress HA-mode of Cilium. ](https://github.com/nikatar/egress-cilium-node-ha-operator)

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by apolovov** [comment]
https://deckhouse.io/products/kubernetes-platform/documentation/v1/modules/021-cni-cilium/examples.html#egress-gateway
