### ISSUE TITLE
Add a linter that validates exported fields in a FilterFunc in Go hooks

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#75]
We rely on proper JSON marshaling to [calculate a checksum](https://github.com/flant/shell-operator/blob/master/pkg/kube_events_manager/filter.go#L43). JSON marshaller won't work with unexported struct fields.

**Comment by nabokihms** [comment]
Fixed in 005e6526c28cca9fdf49409ea6ed9daf76aaadf3
