### ISSUE TITLE
Access to cloud provider api with ServiceAccount tokens

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#761]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Some applications may need to access cloud provider API (e.g. [AWS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)) using Kubernetes service accounts.

### Proposed Solution

Add option to configure Kubernetes API server to be identity provider for cloud providers. And there probably should be parameters to set custom `api-audiences`. Special proxy needed to allow external unauthenticated requests to Kubernetes API jwks endpoint.

**Comment by raabdullaev** [comment]
Implemented with configs in cloud-controller-manager.
