### ISSUE TITLE
Provide information about all FS directories that DKP uses

### ISSUE THREAD

**Issue by qw1mb0** [deckhouse/deckhouse#7695]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Clients quite often request information about the required file system mount points in the operating system used for DKP and the required amount of disk space in them with an explanation of why these directories are needed. This information partially overlaps with https://deckhouse.ru/documentation/v1/security_software_setup.html.

At the moment, we managed to collect the following list with approximately the required disk space:
Master node:
```
/var/lib/etcd - 10 GB
/var/lib/deckhouse - 5 GB
/var/lib/upmeter - 1 GB
/etc/kubernetes - 1 GB
/var/lib/bashible - 1 GB
/var/lib/containerd - 30 GB
/mnt/vector-data - 1 GB
/var/log/containers - 1 GB
/var/log/pods - 2 GB
/var/lib/kubelet - 5 GB
/opt/cni/bin - 1 GB
/opt/deckhouse/bin - 1 GB
/etc/cni - 1 GB
/etc/containerd - 1 GB
/tmp - 1 GB
/run/containerd - 1 GB
/root/.kube - 1 GB
/var/log/kube-audit - 2 GB
/var/lib/cni - 1 GB
```

Worker node:
```
/etc/kubernetes - 1 GB
/var/lib/bashible - 1 GB
/var/lib/containerd - 30 GB
/mnt/vector-data - 1 GB
/var/log/containers - 1 GB
/var/log/pods - 2 GB
/var/lib/kubelet - 5 GB
/opt/cni/bin - 1 GB
/opt/deckhouse/bin - 1 GB
/etc/cni - 1 GB
/etc/containerd - 1 GB
/tmp - 1 GB
/run/containerd - 1 GB
/var/lib/cni - 1 GB
/opt/local-path-provisioner - 40 GB (but depends on the amount of user data required)
```

### Proposed Solution

Create a page similar to https://deckhouse.ru/documentation/v1/security_software_setup.html with recommendations for mount points.

**Comment by konstantin-axenov** [comment]
Research and provide valid numbers.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by z9r5** [comment]
Done in https://github.com/deckhouse/deckhouse/pull/5818
