### ISSUE TITLE
Manage ingress-nginx cipher directly and do not rely on defaults

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#77]
It is set in two places:
1. https://github.com/deckhouse/deckhouse/blob/main/modules/402-ingress-nginx/templates/controller/configmap.yaml#L76
2. https://github.com/kubernetes/ingress-nginx/blob/9a9ad4785704ef7ec0f6428e5cfb2a32d9af5cf3/internal/ingress/controller/config/config.go#L69 (upstream defaults)

Both of these are being contradicted by a constantly updated list of SSL ciphers: https://wiki.mozilla.org/Security/Server_Side_TLS

We could also provide a way for users to override the list or append to it.

**Comment by trublast** [comment]
We wants to use TLS> = 1.2 for the requirements of integration with JIRA
At the same time, another our partner, who works with our service, used TLS 1.2, but with the Windows Server 2012 operating system. Which does not support the latest ciphers. 
And it is necessary to enable TLS 1.2 with some of weak ciphers

**Comment by nabokihms** [comment]
> We could also provide a way for users to override the list or append to it.

@zuzzas, I don't think we have an issue here. From my point of view, defaults for ciphers should be maintained by ingress-controller, not Deckhouse. Deckhouse, on its side, needs to keep the list of ingress-controller versions up-to-date. If users need a custom setup and know what they are doing, they can still override TLS ciphers through the ingress controller's `config` option.

**Comment by zuzzas** [comment]
But we don't provide an option to change the list of ciphers. Should we?

**Comment by nabokihms** [comment]
It is possible to change default ciphers like this.
```
apiVersion: deckhouse.io/v1alpha1
kind: IngressNginxController
spec:
  ...
  config:
     ssl-ciphers: "DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256"
```

**Comment by zuzzas** [comment]
Well, I'll be damned.
