### ISSUE TITLE
[module-manager] Deployed and installed `external` modules aren't deleted if relevant modules configs are deleted

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#7734]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58

### Expected Behavior

Have to be decided on yet.

### Actual Behavior

If an external module is running and its module config is deleted, then nothing happens, the module's resources keep running even though the modules is marked as Disabled. Deckhouse restart doesn't help

### Steps To Reproduce

1. deploy a module
2. add its module config with enabled: true
3. delete module config
4. check the module's status and resources

**Comment by raabdullaev** [comment]
Will be fixed in #8285

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
