### ISSUE TITLE
[grafana] The Ingress Nginx Controllers dashboard fails when there are pods in different NS with the same name, but different app label

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#774]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.30

### Expected Behavior

The dashboard should work.

### Actual Behavior

When there are pods with the same name and different app label, there is an error in `Kubernetes Cluster / Ingress Nginx Controllers` dashboard:
```
found duplicate series for the match group {pod="memcached-0"} on the right hand-side of the operation: [{app="memcached", pod="memcached-0"}, {app="memcached-node", pod="memcached-0"}];many-to-many matching not allowed: matching labels must be unique on one side
```

### Steps To Reproduce

Create pods in different namespaces:
```
# kubectl get pods -A --show-labels | grep memcached-0
ns1  memcached-0  2/2     Running     0          128d    app=memcached,...
ns2  memcached-0  2/2     Running     2          177d    app=memcached-node,...
```
Go to dashboard `Kubernetes Cluster / Ingress Nginx Controllers` and open the `[Containers Resources (Content Kind filter is ignored)]()` section. There will be an error:
```
found duplicate series for the match group {pod="memcached-0"} on the right hand-side of the operation: [{app="memcached", pod="memcached-0"}, {app="memcached-node", pod="memcached-0"}];many-to-many matching not allowed: matching labels must be unique on one side
```

**Comment by duckhawk** [comment]
Already resolved
