### ISSUE TITLE
[grafana] Main / Namespace / Controller longterm average CPU is wrong

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#775]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.30

### Expected Behavior

Avg. CPU in the `Pods` table and avg. CPU in `Usage by Pod` graph should be equal when watching 30-day longterm period.

### Actual Behavior

Avg. CPU in the `Pods` table and avg. CPU in `Usage by Pod` graph are different when watching 30-day longterm period.

### Steps To Reproduce

1. Open `Main / Namespace / Controller` dashboard for namespace d8-system and controller deploy/deckhouse-web-authenticator.
2. Choose longterm data source and 30-day period.

**Comment by EvgenySamoylov** [comment]
Linked with #199

**Comment by nabokihms** [comment]
It seems like a part of a bigger problem that statefulset values are show incorrectly on the Main dashboard.
