### ISSUE TITLE
[candi] Deckhouse version rollback

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#7762]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.58

### Expected Behavior

alpha version installer, but in the cluster-configuration cluster the release is early access 
after installing deckhosue the release rolled back to 1.57.5 after a while 
but it looks like if release channel is set in module config deckhouse then deckhouserelease should not rollback

### Actual Behavior

alpha version installer but in cluster-configuration releasechanel early access 
after installing deckhosue after a while the release rolled back to 1.57.5 and errors appeared 
```
1 error occurred:
	* withNATInstance.natInstanceResources is a forbidden property
```

### Steps To Reproduce

1. docker run deckhouse/installer/alpha
2. releasechannel = earlyaccess in clusterconfiguration config.yml
3. boostrap
4. deckhouse rollback

### Logs

```shell
"Module hook failed, requeue task to retry after delay. Failed count is 5. Error: module hook '030-cloud-provider-yandex/hooks/yandex_cluster_configuration.go' failed: validate cloud-provider-cluster-configuration.yaml: config validation
```
```

**Comment by alexey-gavrilov-flant** [comment]
https://github.com/deckhouse/deckhouse/issues/7450

**Comment by name212** [comment]
Probably resolved [here](https://github.com/deckhouse/deckhouse/pull/8143)
