### ISSUE TITLE
[candi][cloud-provider-yandex] Provide the ability to set coreFraction for masterNodeGroup

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#7787]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Provide the ability to set `coreFraction` for `masterNodeGroup`

The main goal is to reduce costs for small clusters that are used exclusively for testing (training) purposes.

An example of a case from our practice:

Deployment of mass clusters for teaching students

The cost of a typical master is RUB 5,862.00 per month, including `Intel Cascade Lake. 100% virtual CPU` RUB 3,427.20

Reducing coreFraction from 100% to 20% (while D8 performs satisfactorily) will reduce CPU costs to `Intel Cascade Lake. 20% vCPU` 1,411.20 RUR (total cost 3,846.00 RUR)

That is, a reduction in the cost of one master instance by ~35%

### Proposed Solution

Provide the ability to set `coreFraction` for `masterNodeGroup`

### Additional Information

https://cloud.yandex.com/en/docs/compute/concepts/performance-levels

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by RomanenkoDenys** [comment]
we cannot plan to set coreFraction for master node groups because this setting can affect control-plane functionality. If you need you can setup master node on static isntance with corresponding coreFraction set.
