### ISSUE TITLE
[user-authn] Add ability to set multiple domains for DexAuthenticator

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#7846]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The main goal is to reduce the number of objects. Makes it easier to understand and support

Now we have scheme "one domain - one authenticator". Wants "multiple domains - one authenticator".

### Proposed Solution

For this we need ability to set multiple domains in `applicationDomain`.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by name212** [comment]
The feature is implementable. 

We expected settings to look like this:
```
applications:
- domain: aaa
  ingressSecretName: ingres-tls
- domain: bbb
  ingressSecretName: bbb-tls
 ```
 
 For each application we need to add separated ingress resource.
