### ISSUE TITLE
Report error if NodeUser failed to create

### ISSUE THREAD

**Issue by marriva** [deckhouse/deckhouse#7852]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

`NodeUser` creation fails silently without any error. We can only find out about this from bashible logs.

```
Mar 20 15:48:09 cmdr-a-master-0 bashible.sh[275632]: Failed to execute step /var/lib/bashible/bundle_steps/000_add_node_users.sh ... retry in 10 seconds.
```

### Proposed Solution

Post `NodeUser` creation status to kubernetes resource or node events

### Additional Information

How to reproduce? 

Create `NodeUser` resource with existing user name

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by RomanenkoDenys** [comment]
This was solved in https://github.com/deckhouse/deckhouse/pull/8054
