### ISSUE TITLE
[ingress-nginx] HTTP/3 support

### ISSUE THREAD

**Issue by konstantin-axenov** [deckhouse/deckhouse#7865]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

HTTP/3 provides better performance.

### Proposed Solution

Upgrade to 1.10 nginx-ingress controller that [was released](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.10.0) recently.

**Comment by konstantin-axenov** [comment]
https://github.com/kubernetes/ingress-nginx/pull/11172

**Comment by raabdullaev** [comment]
Duplicate of https://github.com/deckhouse/deckhouse/issues/8114
