### ISSUE TITLE
[user-authz] webhook reports a kube api request error for some resources

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#7911]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.0

### Expected Behavior

no errors should be reported

### Actual Behavior

```
➜  ~ kubectl --insecure-skip-tls-verify auth can-i watch moduleconfigs
Warning: resource 'moduleconfigs' is not namespace scoped in group 'deckhouse.io'

yes
➜  ~ kubectl --insecure-skip-tls-verify auth can-i watch moduleconfigs -A
no - webhook: kubernetes api request error
➜  ~
```

### Additional Information

It seems there is an issue related to GVK of a requested resource in the webhook.

### Logs

```shell
2024/03/26 08:18:07 renew namespaced cache: kube response error: 404 404 page not found
: exceeded retry limit
```

```
2024/03/26 09:31:06 resource deckhouse.io/v1/modules is not found in cluster
```
```

**Comment by yalosev** [comment]
Unconfirmed. Works ok everywhere:
```
# kubectl --insecure-skip-tls-verify auth can-i watch moduleconfigs
Warning: resource 'moduleconfigs' is not namespace scoped in group 'deckhouse.io'

yes
# kubectl --insecure-skip-tls-verify auth can-i watch moduleconfigs -A
yes
```
