### ISSUE TITLE
[prometheus-metrics-adapter] The highAvailability configuration parameter isn't implemented

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#794]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

1.30

### Expected Behavior

The highAvailability parameter should work.

### Actual Behavior

The highAvailability parameter isn't implemented at all.

**Comment by nabokihms** [comment]
It is implemented. If HA is enabled, Deckhouse creates as many pods as there are master nodes (as it does for webhooks).
https://github.com/deckhouse/deckhouse/blob/d035ca35c38e3f19ccd6f1d775bf0fee33608583/modules/301-prometheus-metrics-adapter/templates/deployment.yaml#L25

Could you elaborate more on the behavior you have expected?

**Comment by apolovov** [comment]
OMG, i forgot about this template.
