### ISSUE TITLE
[node-manager] RollingUpdate doesn't work with static nodes

### ISSUE THREAD

**Issue by raabdullaev** [deckhouse/deckhouse#7948]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.x

### Expected Behavior

-

### Actual Behavior

RollingUpdate works as Automatic mode with static nodes.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/issues/4312
