### ISSUE TITLE
[candi] dhctl bootstrap when OS have preinstall containerd

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#7960]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

when OS have preinstalled containerd. dhcl boostrap static cluster (bare metal) finished is OK
but bashible in master node stucked in 032_configure_and_start_containerd.sh.tpl install containerd etc 
```
28 19:59:38 master-0 bashible.sh[7925]: === Step: /var/lib/bashible/bundle_steps/032_configure_and_start_containerd.sh
28 19:59:38 master-0 bashible.sh[7925]: ===
28 19:59:39 master-0 bashible.sh[16369]: bash [WARNING] 'containerd-need-restart' flag was set. Containerd should be restarted!
28 20:01:09 master-0 bashible.sh[16369]: Job for containerd-deckhouse.service failed because a timeout was exceeded.
28 20:01:09 master-0 bashible.sh[16369]: See "systemctl status containerd-deckhouse.service" and "journalctl -xeu containerd-deckhouse.service" for details.
28 20:01:09 master-0 bashible.sh[7925]: Failed to execute step /var/lib/bashible/bundle_steps/032_configure_and_start_containerd.sh ... retry in 10 seconds.
```
Containerd was working. kubelet used containerd socket and control-plane components went up and the cluster looked alive 
But kubelet couldn't get logs with the error
```
 x509: cannot validate certificate for 192.168.12.12 because it doesn't contain any IP SANs
```
Because bashible didn't complete its node configuration steps.

### Proposed Solution
Notification that we do not support working with embedded containerd and abort the installation.
OR add preflight check to the OS preinstalled containerd and turn it off or masked

**Comment by konstantin-axenov** [comment]
Add preflight check for this case.
