### ISSUE TITLE
[dhctl] Add to dhctl-mirror ability to download specific release

### ISSUE THREAD

**Issue by hugik-88** [deckhouse/deckhouse#7962]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The client needs to download a specific version of DKP for his registry. At the moment, a bunch of images are being downloaded, which causes difficulties in deleting unnecessary ones

### Proposed Solution

Add the ability to download a specific version of a DKP release up to the patch version, for example 1.57.4 instead of 1.57

**Comment by raabdullaev** [comment]
Duplicate - https://github.com/deckhouse/deckhouse/issues/7408
Developed in #8063.
