### ISSUE TITLE
[monitoring] [flant-integration] Add ssh annotations to alerts when using the flant-integration module

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#8139]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Engineers do not have exact address of server, when reading the alert in monitoring system.
Having a direct link to the master server in alerts saves time for support engineers in finding the required information.

### Proposed Solution

I suggest to add the following annotations to alerts when the flant-integration module is configured and the master server address is provided:

```
annotations:
  plk_incident_link_url/ssh: "ssh://flant-integration.master.ssh.address"
  plk_incident_link_icon/ssh: "fa-terminal"
```
This change will only affect users who utilize the flant-integration module, providing them with additional functionality to simplify alert management.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse/blob/main/ee/be/modules/600-flant-integration/images/madison-proxy/src/madison-proxy.go

**Comment by sprait** [comment]
resolved together with migration to a separate module #8392
