### ISSUE TITLE
[monitoring] Add CPU steal time to the "Node" dashboard

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#8164]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.9

### Expected Behavior

All CPU states are present on the CPU graph.

### Actual Behavior

CPU steal time is missing.

### Additional Information

CPU steal time is a critical piece of information regarding CPU performance of a Node. We've tripped into missing CPU steal time while debugging a Node that seemed to have a slow CPU despite everything being fine on the graph.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
