### ISSUE TITLE
[dhctl][kube-dns] kube-dns is rarely not created when creating a cluster

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#8165]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

global hook should take into account absence of dns in the cluster and allow to install kube-dns module.

### Actual Behavior

we face a situation when [hook](https://github.com/deckhouse/deckhouse/blob/f9220fca03b4d42d8a5c2815e52bde31671e3940/global-hooks/discovery/cluster_dns_address.go) is triggered during cluster installation and blocks installation until dns service is created manually.

### Logs

```shell
2024-04-16T17:24:08Z - [INFO] - │ │ 	/: Global hook failed, requeue task to retry after delay. Failed count is 1. Error: global hook                   ↵
2024-04-16T17:24:08Z - [INFO] - │ │ 'discovery/cluster_dns_address.go' failed: DNS addresses not found
```

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
