### ISSUE TITLE
[monitoring] RemoteWrite add headers to CRD

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#8172]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Deckhouse with Grafana Mimir, with a large number of tenants, it is necessary to divide the metrics by the necessary tenants.
For this purpose in the official specification [remotewrite](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)
There is a possibility to configure headers, in order to add headers to metrics and they went to the right tenant.

Example official docks:
To configure the X-Scope-OrgID header directly, the remote write configuration block includes the following parameters:
```
# Custom HTTP headers to be sent along with each remote write request.
# Be aware that headers that are set by Prometheus itself can't be overwritten.
headers:
  ["X-Scope-OrgID": <TENANT ID>]
  [ <string>:<string> ... ]
  ```

### Proposed Solution

Add the ability to configure the headers field in the `prometheusremotewrites.deckhouse.io` CRD

**Comment by vladimirGuryanov** [comment]
Done ip PR: https://github.com/deckhouse/deckhouse/pull/10317
