### ISSUE TITLE
[log-shipper] Update vector to actual version

### ISSUE THREAD

**Issue by wowsel** [deckhouse/deckhouse#8178]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The version of vector that is currently in use was released almost a year ago and is noticeably outdated both morally and in terms of security. The recent release of loki version 3.0 no longer works properly on the current version of the vector.
I have found opened PR https://github.com/deckhouse/deckhouse/pull/7916 , but not found relative issue. 
Thanks

### Proposed Solution

I suggest updating the vector version to the current 0.37.1 (or current at the time of working on the task)

**Comment by alexey-gavrilov-flant** [comment]
update also allow to not block sending of logs when pod's data cannot be obtained
https://github.com/vectordotdev/vector/pull/18904

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.

**Comment by alexey-gavrilov-flant** [comment]
Close: https://github.com/deckhouse/deckhouse/pull/9520
update to 0.40.1 in dh 1.64.0
