### ISSUE TITLE
[loki] add the ability to customize the configuration

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#8331]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

`caller=scheduler_processor.go:182 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9875666 vs. 4194304)" frontend=10.111.1.77:9095`
sometimes log messages are too large and loki refuses to accept them. 

### Proposed Solution

Make it possible to customize the value for `grpc_server_max_recv_msg_size` and `grpc_server_max_send_msg_size`.

### Additional Information

https://github.com/deckhouse/deckhouse/blob/main/modules/462-loki/templates/configmap.yaml

**Comment by nabokihms** [comment]
Also 
* Limits config
* Migrate to TSDB index

**Comment by melnikovio** [comment]
@nabokihms How should this configuration look? Loki has an extensive [configuration](https://grafana.com/docs/loki/latest/configure/examples/configuration-examples/), and fully replicating its parameters in the CRD seems difficult. Would it be more optimal to allow inserting your own configuration file or part of it?

**Comment by vladimirGuryanov** [comment]
We have increased the number of parameters, this solves the current problem.
https://github.com/deckhouse/deckhouse/pull/9437
