### ISSUE TITLE
[cloud-discovery] kubernetes api token not work sometimes

### ISSUE THREAD

**Issue by kirill-kashin** [deckhouse/deckhouse#8365]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes a token expires and you can't connect to the api.
and we're not picking up a new one.
```
{"level":"error","msg":"Attempt 1 of 3. Failed to get PersistentVolumes from cluster: Unauthorized","time":"2024-05-08T05:54:15Z"}
```

### Proposed Solution

renew and take new token for connect to api

**Comment by RomanenkoDenys** [comment]
we do not see problem anymore.
