### ISSUE TITLE
[prometheus] When calculating retention, we need to take into account the reserved space on the disk partition

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#8399]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.59.11

### Expected Behavior

When calculating retention, the percentage of reserved space on a disk partition is taken into account.

### Actual Behavior

Currently, the retention size is calculated based only on the PVC size. Because of this, PersistentVolumeClaimBytesUsage alerts are triggered.

### Additional Information

```yaml
  prometheusMain:
    diskSizeGigabytes: 440
    retentionGigabytes: 390
```

```shell
df -PB1 /prometheus/
Filesystem         1-blocks         Used   Available Capacity Mounted on
/dev/vdd       464690995200 419322511360 25788534784      95% /prometheus

df -hP /prometheus/
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdd        433G  391G   25G  95% /prometheus
```

**Comment by RomanenkoDenys** [comment]
we removed reserved partition in the all clouds.
