### ISSUE TITLE
[bashible] Duplicate repositories on CentOS

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#84]
In some cases on Centos/Redhat systems, we see duplicate repositories for Kubernetes and Docker.

It is not a Deckhouse problem, but we need additional testing steps in bashible to avoid problems with duplicate repositories.

**Comment by konstantin-axenov** [comment]
We consider a better solution for this issue https://github.com/deckhouse/deckhouse/issues/126.
