### ISSUE TITLE
[deckhouse-controller] add a convenient way of resolving which deckhouse pod is current leader

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#8403]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It's required to provide our users with a universal (considering HA mode and multiple pods) kubectl one-liner to get all necessary debug information from the current running deckhouse pod.

### Proposed Solution

todo

**Comment by nabokihms** [comment]
One way to solve the problem is to label the pod if it is a leader and remove this label from other pods. THen we will be able to exec using labels selector, e.g., `kubectl -n d8-system exec -l deckhouse-leader="" -it -- bash`

Another way is to use the `d8` tool.
