### ISSUE TITLE
[cloud-provider-yandex] add etcd disktype parameter

### ISSUE THREAD

**Issue by ishtarov** [deckhouse/deckhouse#8411]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

etcd is very sensible to disk IOPS, so you must use the fastest disk.
Now network-ssd disktype hardcoded, but Yandex.Cloud has new, fast types of disks that are more suitable for etcd in some cases (network-ssd-io-m3, for example)

### Proposed Solution

add an option to choose etcd disktype ([now only size is available](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-yandex/cluster_configuration.html#yandexclusterconfiguration-masternodegroup-instanceclass-etcddisksizegb)) - `network-ssd`, `network-ssd-nonreplicated`, `network-ssd-io-m3`

### Additional Information

https://yandex.cloud/en/docs/compute/concepts/disk
https://deckhouse.io/documentation/v1/modules/030-cloud-provider-yandex/cluster_configuration.html#yandexclusterconfiguration-masternodegroup-instanceclass-etcddisksizegb
https://github.com/deckhouse/deckhouse/blob/734a4a11a0106d685ac221d7ae73cfed082e7db1/candi/cloud-providers/yandex/terraform-modules/master-node/main.tf#L82

**Comment by raabdullaev** [comment]
Duplicate https://github.com/deckhouse/deckhouse/issues/7349.
