### ISSUE TITLE
[candi] rm support centos 7, 8 EOL

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#8414]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Since the OS will no longer be updated our customers will not be fully protected from future vulnerabilities of the aging OS.

### Proposed Solution

Support for these versions will expire in the coming months. For security reasons, it is necessary to terminate support from our side

### Additional Information

https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

**Comment by RomanenkoDenys** [comment]
We have clients which uses centos 7. So we cannot remove support now.
