### ISSUE TITLE
[candi] Azure VMs are getting change state out of nowhere

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#842]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30.10

### Expected Behavior

Azure VMs' state is not changed once terraform is applied.

### Actual Behavior

Unknown state change is applied, presumably, by the cloud itself. Needs investigation.

``` 
     - identity {
          - identity_ids = [] -> null
          - principal_id = "censored-censored-censored-censored-censored" -> null
          - tenant_id    = "censored-censored-censored-censored-censored" -> null
          - type         = "SystemAssigned" -> null
        }
```

**Comment by vitaliy-sn** [comment]
This bug is not reproducible.
