### ISSUE TITLE
In cluster with multiple ingress controllers vhosts are not filtered by ingress controller in 'VHost Detail' Grafana Dashboard

### ISSUE THREAD

**Issue by fatalwithin** [deckhouse/deckhouse#8438]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10 CE

### Expected Behavior

Choosing the ingress controller in "Controller" drop-down list should filter the available vhosts in "VHost" drop-down list by vhosts related to this controller.

### Actual Behavior

Choosing any ingress controller in "Controller" drop-down list does not affect the available vhosts in "VHost" drop-down list - all available vhosts in the cluster are shown there.

### Steps To Reproduce

Create more than one nginx ingress controllers in the cluster
Go to the Grafana -> Ingress Nginx/VHost Detail dashboard
Try to choose any of the available ingress controllers in the "Controller" drop-down list
Look at the list of the available vhosts in the "VHost" drop-down list

### Additional Information

I suggest to modify the query for `vhost` variable in this dashboard with the following:
`label_values(ingress_nginx_${metric}_info{job="nginx-ingress-controller",controller=~"$controller"}, vhost)`

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
