### ISSUE TITLE
Node network CIDR is not listed in NO_PROXY env variable

### ISSUE THREAD

**Issue by asviel** [deckhouse/deckhouse#8528]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.60.0

### Expected Behavior

If I use a proxy, requests to the master nodes will not attempt to use `http[s]_proxy`.

### Actual Behavior

Requests to master nodes go through `http[s]_proxy`.

### Additional Information

I think we should add private IP address ranges to no_proxy by default:
```
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
```

**Comment by z9r5** [comment]
Please revert the [PR](https://github.com/deckhouse/deckhouse/pull/8496) when the issue will be resolved.
