### ISSUE TITLE
[dhctl] Mirror pull modules without images

### ISSUE THREAD

**Issue by hugik-88** [deckhouse/deckhouse#8547]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We encountered a situation where the image pull was interrupted due to the lack of images in a certain module
```bash
┌ 🪞 ~ Mirror: Pull Deckhouse images from registry to local filesystem
│ ┌ 🪞 ~ Mirror: Looking for required Deckhouse releases
│ │ Deckhouse releases to pull: [1.60.1 1.59.12]
│ └ 🪞 ~ Mirror: Looking for required Deckhouse releases (1.14 seconds)
│ 
│ ┌ 🪞 ~ Mirror: Pull images
│ │ Fetching Deckhouse modules list...  ✅
│ │ Creating OCI Image Layouts...       ✅
│ │ Searching for Deckhouse modules images...   🪞 ~ Mirror: Pull images (4.60 seconds) FAILED
└ 🪞 ~ Mirror: Pull Deckhouse images from registry to local filesystem (6.15 seconds) FAILED

find Deckhouse modules images: get digests for "registry.deckhouse.ru/deckhouse/fe/modules/deckhouse-delivery:v0.0.37" version:            ↵
images_digests.json: file does not exist
```
We can add a flag to disable module pulling, but without specifying a specific one, only all modules

### Proposed Solution

Add the ability to skip the pull of modules that do not have an image

**Comment by mvasl** [comment]
Fixed in deckhouse/deckhouse-cli#18
