### ISSUE TITLE
[metallb] Provide ability to specify interfaces for speakers

### ISSUE THREAD

**Issue by unreturned** [deckhouse/deckhouse#8565]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The main goal is to solve problems on nodes with multiple network interfaces. In L2 mode, by default a metallb speaker announces the LoadBalancer IP from all the network interfaces of a node. We have a case on a node with several interfaces condensed into one switch, when this led to the inaccessibility of the ingress, since the metallb IP address had several MAC addresses.

### Proposed Solution

Provide ability to specify interfaces https://metallb.universe.tf/configuration/_advanced_l2_configuration/#specify-network-interfaces-that-lb-ip-can-be-announced-from

**Comment by apolovov** [comment]
The problem solved in new module L2LoadBalancer. metallb in l2 mode is deprecated.
