### ISSUE TITLE
[deckhouse] Refactor update settings

### ISSUE THREAD

**Issue by nabokihms** [deckhouse/deckhouse#8572]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

There are two options now: for update approval and for desruptive update approval. Customers reported that the API is puzzling because of too many options and their combinations. Major problems:

1. Two options for updates.
2. Manual is not really manual. Deckhouse applies patches automatically, which is unwanted behavior for some customers. Removing release channel it the only way to make deckhouse updates truly manual.

### Proposed Solution

1. Make the `releaseChannel` required. There are no cases when users do not need the releases info in their clusters.
2. Migrate to a single option for update mode with the following enum:

* `Manual` - deckhouse downloads releases info, but does not apply them
* `AutoPatch` (default) - deckhouse automatically applies patch releases, but asks for approval of minor releases
* `Auto` - deckhouse automatically applies all releases
* ~~`UnsafeAuto` - deckhouse automatically applies all releases including probably desruptive updates ~~

3. Leave only one way to approve releases (abstein from using the `release.deckhouse.io/disruption-approved=true` annotation).

4. Add `UnsafeAuto` for modules and their releases (introduce the option to provide the info about an update being unsafe for modules).

**Comment by shvgn** [comment]
@nabokihms  Maybe it would be better to change the tone, because `Auto` does not apply _all releases_ as you state in the post, all releases are automatically applied with `UsafeAuto`. 

That would better describe limitations right in the name:

```
Auto        -> SafeAuto
UnsafeAuto  -> Auto
```

**Comment by nabokihms** [comment]
I like the `UsafeAuto` because it clearly states that the option is unsafe to enable. I would consider even not introducing UnsafeAuto at all and add later if users really need it.

**Comment by shvgn** [comment]
@nabokihms one more idea to make it clear: Manual is the opposite to Auto, and Auto is divided into levels of automation:

* mode=Manual
* mode=AutoPatch 
* mode=AutoRelease
* mode=AutoReleaseUnsafe
