### ISSUE TITLE
Consider making early OOM kills dynamic based 

### ISSUE THREAD

**Issue by zuzzas** [deckhouse/deckhouse#877]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Memory thrashing that leads to node lockup may differ on differently sized nodes. If early OOM triggers too early, it'll happily kill innocent processes.

### Proposed Solution

Since there is no working implementation of the oomd (or similar projects) in the Kubernetes environment, let us tune the simple implementation for differently-sized nodes.

### Additional Information

Current 512 MiB for MemAvailable threshold (and, thus, memory trashing) was empirical and had to to be verified via multiple experiments,

**Comment by EvgenySamoylov** [comment]
Fixed in #876
