### ISSUE TITLE
When removing the ModuleUpdatePolicy, some modules has error "ModuleUpdatePolicy deckhouse not found" in ModuleRelease

### ISSUE THREAD

**Issue by trofimovdals** [deckhouse/deckhouse#8827]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.60.6

### Expected Behavior

I do not create a [ModuleUpdatePolicy](https://deckhouse.ru/documentation/v1/cr.html#moduleupdatepolicy) for module and remove `ModuleUpdatePolicy` `deckhouse` - `ModuleRelease` take release channel and update policy from the deckhouse `spec.update` [docs](https://deckhouse.ru/documentation/latest/module-development/run/#%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F)
I create [ModuleUpdatePolicy](https://deckhouse.ru/documentation/v1/cr.html#moduleupdatepolicy) - release channel and update policy modules take from already created `ModuleUpdatePolicy`

### Actual Behavior

When `ModuleUpdatePolicy`deckhouse  delete from cluster, we get the error that the Update Policy does not exist for undeployed module in `ModuleRelease` status

**Comment by raabdullaev** [comment]
Will be fixed in https://github.com/deckhouse/deckhouse/issues/8988.
