### ISSUE TITLE
[cloud-providers] [Azure] Add Microsoft.CognitiveServices to serviceEndpoints in AzureClusterConfiguration

### ISSUE THREAD

**Issue by trofimovdals** [deckhouse/deckhouse#8933]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases may need to use `Microsoft.CognitiveServices` values for `serviceEndpoints` in `AzureClusterConfiguration`

### Proposed Solution

Add `Microsoft.CognitiveServices` in allowed [values](https://deckhouse.io/documentation/v1/modules/030-cloud-provider-azure/cluster_configuration.html#azureclusterconfiguration-serviceendpoints-element) for `serviceEndpoints` in `AzureClusterConfiguration`

**Comment by raabdullaev** [comment]
In which cases? Need more details.
