### ISSUE TITLE
[user-authn] Add ability to show client IP in Dex logs

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#8987]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Sometimes we want to see IP addresses in successful or failed authorization request log entries, but we don't have this option.

### Proposed Solution

Add new spec in user-authn moduleconfig where we can enable this feature.
Maybe we need to add sider-car nginx container or parse logs forward from Ingress Controller.

**Comment by raabdullaev** [comment]
https://github.com/dexidp/dex/issues/1788
