### ISSUE TITLE
[deckhouse-controller] module graph building is not verbose enough

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#8995]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

If some module contains an error and graph couldn't be calculated it gives an error like:
```
{"event.id":"8d772155-ebf1-4c3a-a34e-8b572b169338","level":"warning","msg":"Module Scheduler: Graph converge failed with errors: 0.0.0 is less than 1.65.7","operator.component":"ModuleManager.RefreshEnabledState","source":"KubeConfigExtenderChanged","task.id":"6348d6dd-9795-4160-8594-316952750d62","time":"2024-07-09T10:03:19Z","type":"ModuleScheduler event"}
{"event.id":"8d772155-ebf1-4c3a-a34e-8b572b169338","level":"error","msg":"ConvergeModules failed in phase 'WaitBeforeAll', requeue task to retry after delay. Failed count is 5. Error: couldn't recalculate graph: 0.0.0 is less than 
```

but from this error we couldn't understand, who invokes it

### Proposed Solution

Have to add module name and module path to the error, like extra labels

**Comment by raabdullaev** [comment]
Fixed in https://github.com/flant/shell-operator/pull/625.
