### ISSUE TITLE
[dhctl] Preflight check scripts are not removed from ssh-user home dir

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#9060]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.61.5

### Expected Behavior

Preflight check scripts like `~/xxx-check_ports.sh` are removed after the check has completed

### Actual Behavior

Preflight check scripts are uploaded in home directory of user set as `ssh-user`, and not removed after execution. Multiple cluster re-setups could result in cluttered home folder.

Maybe we can use `DeckhouseNodeTmpPath` for these scripts as well: https://github.com/deckhouse/deckhouse/blob/main/dhctl/pkg/system/ssh/frontend/upload-script.go#L94-L96

### Steps To Reproduce

1. Start installing DH on a single static node
2. After cluster is set up, PC scripts are left in ssh-user home directory

### Additional Information

```
oleg@ob-preflight-master-0:~$ ls -dlh "$PWD"/*
-rwxrwxr-x 1 oleg oleg  168 Jul 16 09:53 /home/oleg/1045743925-check_localhost.sh
-rwxrwxr-x 1 oleg oleg 2.5K Jul 16 09:53 /home/oleg/208344586-check_ports.sh
-rwxrwxr-x 1 oleg oleg 2.5K Jul 16 10:23 /home/oleg/2598212317-check_ports.sh
-rwxrwxr-x 1 oleg oleg 1.9K Jul 16 09:53 /home/oleg/2695778541-detect_bundle.sh
-rwxrwxr-x 1 oleg oleg 2.5K Jul 16 10:12 /home/oleg/551769077-check_ports.sh
```

**Comment by raabdullaev** [comment]
Scripts should be created in /opt/deckhouse/
