### ISSUE TITLE
[terraform-state-exporter] sends invalid metrics after delete static NodeGroup

### ISSUE THREAD

**Issue by vitaliy-sn** [deckhouse/deckhouse#91]
Steps to reproduce:
1. Сreate static node via provider-cluster-configuration.
2. Change something in the node settings so that the D8TerraformStateExporterNodeStateChanged alert fires.
3. Remove static NodeGroup from provider-cluster-configuration and run dhctl converge.

**Comment by name212** [comment]
I tried to reproduce this problem but I didn't reproduce it and I didn't find any issues in the code.
I need more information.

Terraform-exporter exports metrics periodically with 10 minutes interval.
Did you wait 10 minutes for update metrics?

Anyway, I will add additional logs for the process of setting metrics.

**Comment by nabokihms** [comment]
Changes were made there https://github.com/deckhouse/deckhouse/commit/ca07d5852a9553de7bec4d55efdcfbd4f8ae11c7

Closing for now.
