### ISSUE TITLE
[secret-copier] queue may  get stuck when a namespace is deleted

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#9152]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.62.0

### Expected Behavior

secret-copier should forget about deleted namespaces
```
Queue '/modules/secret-copier': length 1, status: 'sleep after fail for 32s (28s left of 32s delay)'

 1. ModuleHookRun:/modules/secret-copier:kubernetes:600-secret-copier/hooks/handler.go:secrets:Kubernetes:failures 10:module hook '600-secret-copier/hooks/handler.go' failed: can't create secret object `d8-istio/my-secret`: namespaces "d8-istio" not found

Summary:
- 'main' queue: empty.
- 96 other queues (1 active, 95 empty): 1 task.
- total 1 task to handle.
```

### Actual Behavior

sometimes the secret-copier's queue gets stuck after disabling a module

### Steps To Reproduce

1. get a secret copied by secret-copier
2. enable some module with its own namespace
3. disable the module
4. check the secret-copier's queue

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
