### ISSUE TITLE
[descheduler] update version

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [deckhouse/deckhouse#9172]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

The current version is too old we may have unknown consequences from this.

### Proposed Solution

Upgrade the module version to the minimum Kubernetes version we support.
Now we have minimum kube 1.26, and the module supports compatibility for two versions. Therefore we can safely take version 0.28.1    https://github.com/kubernetes-sigs/descheduler/tree/v0.28.1?tab=readme-ov-file

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
