### ISSUE TITLE
Shell-operator reports wrong version

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#9178]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.62.0

### Expected Behavior
```
[root@prod-logging-52d6fa2d-5886f-6b26q /]# /shell-operator version
shell-operator v1.4.10
jqFilter implementation: use embedded libjq-go
```
### Actual Behavior

```
[root@prod-logging-52d6fa2d-5886f-6b26q /]# /shell-operator version
shell-operator v1.2.0-dev
jqFilter implementation: use embedded libjq-go
```

### Steps To Reproduce

1. exec into a container, running shell-operator, like webhook-handler in d8-system
2. ./shell-operator version

### Additional Information

Apparently, it should be fixed [there](https://github.com/deckhouse/deckhouse/blob/11ed11d137eaf8094fc8dad794ec37b800a862dc/modules/000-common/images/shell-operator/werf.inc.yaml#L56) when building. Currently, it always takes default value of 'v1.2.0-dev'

**Comment by alexey-gavrilov-flant** [comment]
[breadcrumb](https://github.com/flant/shell-operator/blob/3ee594e7e63f4befb409aedc31212d2c5751836b/pkg/app/app.go#L15)
