### ISSUE TITLE
Issue: Support for Single-zone Clusters in Yandex Cloud

### ISSUE THREAD

**Issue by petqa** [deckhouse/deckhouse#9240]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We frequently operate clusters that utilize only one availability zone in Yandex Cloud. However, the current implementation of Deckhouse mandates the use of three availability zones. To better manage our network configurations, we need the flexibility to deploy clusters using a single availability zone when required.

### Proposed Solution

We propose that during the cluster installation process, Deckhouse should offer an option to specify the number of availability zones to be used. This should include the ability to configure clusters to operate within a single availability zone.

Key Features:

- Configuration Options: Add a setting in the Deckhouse installation configuration to specify the desired number of availability zones.
- Single-zone Support: Allow users to choose a single availability zone during the cluster setup process.

By implementing these changes, we can achieve more straightforward network management and deployment processes for our single-zone clusters in Yandex Cloud.

**Comment by raabdullaev** [comment]
Need to be discussed.

**Comment by RomanenkoDenys** [comment]
We divide network for nodes to parts for every zone due to ability to scale cluster to multiple zones.
