### ISSUE TITLE
[System registry] The ability to import deckhouse-cli to run its commands from dhctl

### ISSUE THREAD

**Issue by vadimartynov** [deckhouse/deckhouse#9307]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

To bootstrap a Deckhouse cluster with the system registry enabled (in mirror mode), you need to execute `d8 mirror push` during the cluster bootstrap process. To run `d8 mirror push` during bootstrap, the ability to import code into dhctl is required. Currently, deckhouse-cli is in an internal package without the possibility of code import.

### Proposed Solution

Possible solutions:
- move part of the internal package to the pkg package to enable code import;
- move some functionality to go_lib in the Deckhouse project;

**Comment by raabdullaev** [comment]
https://github.com/deckhouse/deckhouse-cli/pull/36
