### ISSUE TITLE
Destroy static master nodes without using SSH connection to them

### ISSUE THREAD

**Issue by mvasl** [deckhouse/deckhouse#9334]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

We are in progress of implementing ssh-less bootstrap and destruction of master nodes, but current mechanism of static master nodegroup destruction relies on using ssh to call `/var/lib/bashible/cleanup_static_node.sh` scripts on each master node in the cluster. We should use a different way since we are expecting SSH is not available to us.

### Proposed Solution

We may use NodeGroupConfiguration to call `/var/lib/bashible/cleanup_static_node.sh` instead of SSH.

**Comment by deckhouse-BOaTswain** [comment]
This issue has been automatically put in the triage queue because it has not had
recent activity. The team will reconsider the status of this issue. Thank you
for your contributions.
