### ISSUE TITLE
Update ElasticSearch Dashboard

### ISSUE THREAD

**Issue by Ivelok** [deckhouse/deckhouse#936]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

I need an extended ElasticSearch Grafana dashboard. The current ES dashboard is very simple.

### Proposed Solution

Maybe we can implement this Grafana Dashboard: https://grafana.com/grafana/dashboards/2322 ?

**Comment by nabokihms** [comment]
@Ivelok, yeah, you are right. The current dashboard is a little bit outdated (and not detailed).

Do you want to go ahead and make the changes to adapt the community dashboard?
1. The old dashboard is lying here https://github.com/deckhouse/deckhouse/blob/main/ee/fe/modules/340-monitoring-applications/monitoring/grafana-dashboards/applications/elasticsearch/elasticsearch.json 
2. There is a guide on how to cook dashboards for Deckhouse https://github.com/deckhouse/deckhouse/blob/main/modules/300-prometheus/docs/internal/GRAFANA_DASHBOARD_DEVELOPMENT.md
