### ISSUE TITLE
[secret-copier] Copy annotations from secrets

### ISSUE THREAD

**Issue by haosb** [deckhouse/deckhouse#9378]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Module does not copy annotations from main secret, in some cases we need to copy annotations. 

### Proposed Solution

Copied secrets have annotations from main secret too.

**Comment by raabdullaev** [comment]
In cases with argocd you should not use secret-copier because there will be two sources of truth.
