### ISSUE TITLE
[kube-dns] need a way to switch off the upstream nameservers

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#939]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases, we need to prevent external dns-queries. One solution is to turn off the forward in coredns.

### Proposed Solution

There is `kubeDns.upstreamNameservers` argument. If i set it to `[]`, the helm determines it as `false` in [this](https://github.com/deckhouse/deckhouse/blob/83162a4cd8e8792ea0258821735e607289e57166/modules/042-kube-dns/templates/configmap.yaml#L28) default expression.
It is appropriate to add a condition that turns off the `forward` section for empty `kubeDns.upstreamNameservers` array.
Or we could use `null` for it.

**Comment by konstantin-axenov** [comment]
You can use NodeGroupConfiguration to configure resolve.conf on node.
