### ISSUE TITLE
[kubelet] need a way to control resolv.conf in containers

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#940]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Mostly we don't need special search domains or any other resolv.conf options from the Node in Pods. Maybe in some cloud provider controllers. So there should be a way not to blindly inherit the resolv.conf options from host Node. 

### Proposed Solution

There is a kubelet option `resolvConf`. We could set the default minimal conf-file for regular nodes and overwrite it according to the NodeGroup spec option.

**Comment by konstantin-axenov** [comment]
You should either use [Pod's DNS Config](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config) feature or create NodeGroupConfiguration to configure resolve.conf on node.
