### ISSUE TITLE
[testing] Need a linter to force labeling CRDs deployed by deckhouse

### ISSUE THREAD

**Issue by apolovov** [deckhouse/deckhouse#9446]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is impossible to detect if CRD was deployed by d8 or not.

### Proposed Solution

Add a linter which checks if there are heritage/module labels in CRDs manifests.

**Comment by name212** [comment]
we already set labels in ensure_crds hook
https://github.com/deckhouse/deckhouse/blob/699630ccd158425168b114fe0f9c94e5cccc2de7/go_lib/hooks/ensure_crds/hook.go#L215-L214
