### ISSUE TITLE
An ability to view current cost of cloud components

### ISSUE THREAD

**Issue by coolyashow** [deckhouse/deckhouse#945]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

To easily see how much our infrastructure costs, we need something like https://github.com/kubecost implemented. This is to easily determine our part in a monthly bill.

### Proposed Solution

https://github.com/kubecost -like utility.

**Comment by EvgenySamoylov** [comment]
OpenCost as an option: https://github.com/opencost/opencost
