### ISSUE TITLE
Dex expects DexProvider.oidc.rootCAData to be a file path

### ISSUE THREAD

**Issue by MaksimKlepikov** [deckhouse/deckhouse#9455]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.2 CE

### Expected Behavior

The provided value in DexProvider.oidc.rootCAData should be passed to dex through its config without error, as specified in the documentation:
https://deckhouse.ru/products/kubernetes-platform/documentation/v1/modules/150-user-authn/cr.html#dexprovider-v1-spec-oidc-rootcadata
```
rootCAData: |
  -----BEGIN CERTIFICATE-----
  MIIFaDC...
  -----END CERTIFICATE-----
```

### Actual Behavior

There is an error in the dex logs:
```
failed to initialize server: server: Failed to open connector keycloak: failed to open connector: failed to create connector keycloak: failed to read root-ca: open -----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
: file name too long
```
It looks like the rootCAs in config.yaml, which is stored in the dex secret, should be a file path rather than a plain text value.

### Additional Information

It works in v1.61.5 CE. There is no error with the same config.yaml

**Comment by nabokihms** [comment]
Fixed in 1.64
