### ISSUE TITLE
[deckhouse] Prohibiting users from editing DKP resources

### ISSUE THREAD

**Issue by DaNnNiS** [deckhouse/deckhouse#9623]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

It is necessary to prohibit users from editing and deleting DKP resources, leaving this option only for the deckhouse service account. This is necessary to avoid cases of editing or deleting DKP resources necessary for the proper operation of the kubernetes cluster.

### Proposed Solution

Implement the ability to edit DCP resources exclusively with the deckhouse account of the deckhouse module.

**Comment by yalosev** [comment]
https://github.com/deckhouse/deckhouse/pull/9852
