### ISSUE TITLE
[deckhouse] Changing registry leaves trailing '/' in image

### ISSUE THREAD

**Issue by meatuses** [deckhouse/deckhouse#9624]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.7

### Expected Behavior

When changing registry via `deckhouse-controller helper change-registry`, if `new-registry` argument has a trailing `/`, it either should stripped automatically or the check should fail.

### Actual Behavior

If `deckhouse-controller helper change-registry` is executed with `new-registry` having a trailing slash but otherwise being a correct registry url, is applies invalid image name to deckhouse deployment (note `/` before tag/digest):
```
root@k8s-master-0:~# kubectl exec -ti -n d8-system svc/deckhouse-leader -c deckhouse -- deckhouse-controller helper change-registry  registry.deckhouse.io/deckhouse/ce/ --dry-run | grep -e "image:"
        image: registry.deckhouse.io/deckhouse/ce/:v1.63.7
        image: registry.deckhouse.io/deckhouse/ce/@sha256:9e39972534549245803c003b4423cc745297af43affc2bbc4dd3c4da225e46e5
        image: registry.deckhouse.io/deckhouse/ce/@sha256:79ed551f4d0ec60799a9bd67f35441df6d86443515dd8337284fb68d97a01b3d
``` 

By the way, secret deckhouse-registry [rendered](https://github.com/deckhouse/deckhouse/blob/release-1.63/deckhouse-controller/pkg/helpers/change_registry/change_registry.go#L219) with correct path and the slash is omitted:
```
root@k8s-master-0:~# kubectl exec -ti -n d8-system svc/deckhouse-leader -c deckhouse -- deckhouse-controller helper change-registry  registry.deckhouse.io/deckhouse/ce/ --dry-run | grep "path: /"
  path: /deckhouse/ce
```

### Steps To Reproduce

1. Have a working cluster.
2. Try to change registry using our [manual](https://deckhouse.io/products/kubernetes-platform/documentation/v1/deckhouse-faq.html#how-do-i-configure-deckhouse-to-use-a-third-party-registry) but add a trailing slash by accident in the new-registry argument.
3. Deckhouse pod fails to start with `InvalidImageName` error
4. Check the deployment resource, images have a slash before tag delimiter

**Comment by meatuses** [comment]
https://github.com/deckhouse/deckhouse/issues/9410#issuecomment-2315069325

**Comment by raabdullaev** [comment]
Do not forget to check #8646.

**Comment by mvasl** [comment]
Cannot reproduce this on a fresh cluster from `main`. Seems like it was patched [here](https://github.com/deckhouse/deckhouse/commit/b548cdfd35a6b79428075a5ca3a2ffd6f2df37e8)
