### ISSUE TITLE
[deckhouse-controller] deckhouse-controller always reports dev version

### ISSUE THREAD

**Issue by miklezzzz** [deckhouse/deckhouse#9629]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.63.7

### Expected Behavior

```
/deckhouse $ deckhouse-controller version
deckhouse v1.63.7 (addon-operator v1.4.2, shell-operator v1.4.10, Golang go1.22.2)
```

### Actual Behavior

```
/deckhouse $ deckhouse-controller version
deckhouse dev (addon-operator v1.4.2, shell-operator v1.4.10, Golang go1.22.2)
```

### Steps To Reproduce

should be obvious from the above output

**Comment by yalosev** [comment]
`git symbolic-ref --short -q HEAD || git describe --tags --exact-match || echo "dev"`
