### ISSUE TITLE
[grafana] Add links from "documentation" inside the cluster to "Enabled modules"

### ISSUE THREAD

**Issue by maray2208** [deckhouse/deckhouse#9682]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In the Grafana web resource, clicking on links in "Enabled modules" leads to the resource https://deckhouse.io /, add links to "documentation" inside the cluster
![image](https://github.com/user-attachments/assets/6f4823cb-6ff5-436c-b14f-3651b83470a9)

### Proposed Solution

Add links from "documentation" inside the cluster to "Enabled modules"

**Comment by vladimirGuryanov** [comment]
Fix in PR: https://github.com/deckhouse/deckhouse/pull/10748
