### ISSUE TITLE
[ingress-nginx] use proxy-protocol for HostWithFailover inlet

### ISSUE THREAD

**Issue by yalosev** [deckhouse/deckhouse#9727]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

Theoretically, we can use proxy-protocol for HostWithFailover inlet but atm. we will lose cliend IP-address during the rollout process, when traffic is routed to the failover controller

### Proposed Solution

Need to research, could we keep the proxy protocol client headers for the failover controller

**Comment by raabdullaev** [comment]
Use l2-load-balancer/metallb instead of HostWithFailover.
