### ISSUE TITLE
[user-authz] Validate serviceaccount names in ClusterAuthorizationRules

### ISSUE THREAD

**Issue by shvgn** [deckhouse/deckhouse#976]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.30.11

### Expected Behavior

Kube API should respond with error when mentioned SA name in ClusterAuthorizationRule is invalid, i.e. not a domain name.

### Actual Behavior

The rules can be created, but deckhouse main queue is stuck if there is SA name like "A" since capital letters are forbidden in SA names. The actual error is 

> "JonhDoe": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '_' or '.' and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '...') 

The regex is 

```
[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

**Comment by nabokihms** [comment]
Closed by https://github.com/deckhouse/deckhouse/pull/1028
